μROSnode
Low-level functions
Base
Detailed Description
Functions
void uros_lld_init (void)
Initializes the low-level system.
void * uros_lld_alloc (size_t size)
Allocates a memory block.
void uros_lld_free (void *chunkp)
Deallocates a memory block.
Function Documentation
void uros_lld_init (void)
Initializes the low-level system.
Precondition
The low-level system has not been initialized yet.
Definition at line 67 of file uros_lld_base.c.
Referenced by urosInit().
void* uros_lld_alloc (size_t size)
Allocates a memory block.
This function tries to allocate a memory block of the required size inside the default heap of the operating system.
See Also
urosAlloc()
Precondition
There is enough contiguous free space inside the default heap.
Parameters
[in] size Size of the memory block to be allocated, in bytes.
Returns
The address of the allocated memory chunk.
Return values
NULL There is not enough contiguous free memory to allocate a memory block of the requested size.
Definition at line 88 of file uros_lld_base.c.
Referenced by urosAlloc().
void uros_lld_free (void * chunkp)
Deallocates a memory block.
See Also
urosFree()
Precondition
The block pointed by chunkp must have been allocated with urosAlloc().
Postcondition
chunkp points to an invalid address.
Parameters
[in] chunkp Pointer to the memory block to be deallocated. A NULL value will simply be ignored.
Definition at line 107 of file uros_lld_base.c.
Referenced by urosFree().