μROSnode
Functions
Connectivity
Detailed Description
Functions
uros_err_t urosHostnameToIp (const UrosString *hostnamep, UrosIp *ipp)
Resolves an hostname to an IP address.
uros_err_t urosUriToAddr (const UrosString *urip, UrosAddr *addrp)
Resolves an URI to a connection address.
void urosConnObjectInit (UrosConn *cp)
Initializes a connection object.
uros_bool_t urosConnIsValid (UrosConn *cp)
Checks if pointing to a valid connection object.
uros_err_t urosConnCreate (UrosConn *cp, uros_connproto_t protocol)
Creates a new connection.
uros_err_t urosConnBind (UrosConn *cp, const UrosAddr *locaddrp)
Binds to a local address.
uros_err_t urosConnAccept (UrosConn *cp, UrosConn *spawnedp)
Accepts an incoming connection.
uros_err_t urosConnListen (UrosConn *cp, uros_cnt_t backlog)
Initializes the listening mode.
uros_err_t urosConnConnect (UrosConn *cp, const UrosAddr *remaddrp)
Connects to a remote address.
uros_err_t urosConnRecv (UrosConn *cp, void **bufpp, size_t *buflenp)
Receives some data.
uros_err_t urosConnRecvFrom (UrosConn *cp, void **bufpp, size_t *buflenp, const UrosAddr *remaddrp)
Receives some data from a remote address.
uros_err_t urosConnSend (UrosConn *cp, const void *bufp, size_t buflen)
Sends some data.
uros_err_t urosConnSendConst (UrosConn *cp, const void *bufp, size_t buflen)
Sends some data.
uros_err_t urosConnSendTo (UrosConn *cp, const void *bufp, size_t buflen, const UrosAddr *remaddrp)
Sends some data to a remote address.
uros_err_t urosConnSendToConst (UrosConn *cp, const void *bufp, size_t buflen, const UrosAddr *remaddrp)
Sends some data to a remote address.
uros_err_t urosConnShutdown (UrosConn *cp, uros_bool_t rx, uros_bool_t tx)
Terminates soem ends of a full-duplex channel.
uros_err_t urosConnClose (UrosConn *cp)
Closes a connection.
uros_err_t urosConnGetTcpNoDelay (UrosConn *cp, uros_bool_t *enablep)
Gets the Nagle algorithm state.
uros_err_t urosConnSetTcpNoDelay (UrosConn *cp, uros_bool_t enable)
Sets the Nagle algorithm state.
uros_err_t urosConnGetRecvTimeout (UrosConn *cp, uint32_t *msp)
Gets the receiver timeout.
uros_err_t urosConnSetRecvTimeout (UrosConn *cp, uint32_t ms)
Sets the receiver timeout.
uros_err_t urosConnGetSendTimeout (UrosConn *cp, uint32_t *msp)
Gets the sender timeout.
uros_err_t urosConnSetSendTimeout (UrosConn *cp, uint32_t ms)
Sets the sender timeout.
const char * urosConnLastErrorText (const UrosConn *cp)
Gets the last low-level connectivity library error text.
Function Documentation
uros_err_t urosHostnameToIp (const UrosString * hostnamep, UrosIp * ipp)
Resolves an hostname to an IP address.
Executes a DNS call to resolve the hostname string to an IP address which can be used by the connectivity library.
Parameters
[in] hostnamep Pointer to a hostname string.
[out] ipp Pointer to an allocated UrosIp object.
Returns
Error code.
Definition at line 75 of file urosConn.c.
References uros_lld_hostnametoip().
Referenced by urosUriToAddr().
uros_err_t urosUriToAddr (const UrosString * urip, UrosAddr * addrp)
Resolves an URI to a connection address.
The provided URI is converted into a connection address. The URI has the following structure:
protocol://hostname:port[/...]
where:
the protocol is ignored and supposed to be http (ROS XMLRPC over HTTP)
the hostname can also be an IPv4 address
the remainder after the port is simply ignored.
Parameters
[in] urip Pointer to the URI string.
[out] addrp Pointer to an annlocated UrosAddr descriptor.
Returns
Error code.
Definition at line 100 of file urosConn.c.
References UrosString::datap, UrosAddr::ip, UrosString::length, UrosAddr::port, UROS_ERR_PARSE, UROS_OK, UROS_STRARG, urosAssert, urosError, urosErrorText(), urosHostnameToIp(), and urosStringNotEmpty().
Referenced by urosNodeFindNewPublishers().
void urosConnObjectInit (UrosConn * cp)
Initializes a connection object.
Invalidates the connection fields and initializes the low-level ones.
See Also
uros_lld_conn_objectinit()
Parameters
[in,out] cp Pointer to an allocated UrosConn object.
Definition at line 160 of file urosConn.c.
References UrosIp::dword, UrosAddr::ip, UrosConn::locaddr, UrosAddr::port, UrosConn::protocol, UrosConn::remaddr, UROS_ANY_IP, UROS_ANY_PORT, uros_lld_conn_objectinit(), UROS_PROTO__LENGTH, and urosAssert.
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_bool_t urosConnIsValid (UrosConn * cp)
Checks if pointing to a valid connection object.
cp points to a valid connection if it is not NULL and its low-level fields are in a valid state.
See Also
uros_lld_conn_isvalid()
Parameters
[in] cp Pointer to a presumed valid UrosConn object.
Returns
true if cp addresses a valid UrosConn object.
Definition at line 185 of file urosConn.c.
References uros_lld_conn_isvalid().
Referenced by uros_lld_conn_accept(), uros_lld_conn_bind(), uros_lld_conn_connect(), uros_lld_conn_getrecvtimeout(), uros_lld_conn_getsendtimeout(), uros_lld_conn_gettcpnodelay(), uros_lld_conn_listen(), uros_lld_conn_recv(), uros_lld_conn_recvfrom(), uros_lld_conn_send(), uros_lld_conn_sendconst(), uros_lld_conn_sendto(), uros_lld_conn_sendtoconst(), uros_lld_conn_setrecvtimeout(), uros_lld_conn_setsendtimeout(), uros_lld_conn_settcpnodelay(), uros_lld_conn_shutdown(), urosTcpRosExpect(), urosTcpRosListenerThread(), urosTcpRosRecv(), and urosTcpRosSkip().
uros_err_t urosConnCreate (UrosConn * cp, uros_connproto_t protocol)
Creates a new connection.
The connection object is initialized for a new connection.
See Also
uros_lld_conn_create()
Note
Conceptually equivalent to POSIX create().
Precondition
The connection object is initialized but no connection has been created with it.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] protocol Connection protocol.
Returns
Error code.
Definition at line 206 of file urosConn.c.
References uros_lld_conn_create().
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_err_t urosConnBind (UrosConn * cp, const UrosAddr * locaddrp)
Binds to a local address.
The local side of a connection object is bound to the provided address.
See Also
uros_lld_conn_bind()
Note
Conceptually equivalent to POSIX bind().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] locaddrp Pointer to the local address descriptor to be bound.
Returns
Error code.
Definition at line 227 of file urosConn.c.
References uros_lld_conn_bind().
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_err_t urosConnAccept (UrosConn * cp, UrosConn * spawnedp)
Accepts an incoming connection.
A listener connection waits until a remote connection is instantiated. A new dedicated connection channel is spawned and returned, and the spawning connection is put back into listening state.
See Also
uros_lld_conn_accept()
Note
Conceptually equivalent to POSIX accept().
Precondition
The cp connection object is listening.
Parameters
[in,out] cp Pointer to the listener connection object.
[out] spawnedp Pointer to an allocated UrosConn object with which the new dedicated communication channel is created.
Returns
Error code.
Definition at line 251 of file urosConn.c.
References uros_lld_conn_accept().
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_err_t urosConnListen (UrosConn * cp, uros_cnt_t backlog)
Initializes the listening mode.
The connection object is initialized for listening.
See Also
uros_lld_conn_listen()
Note
Conceptually equivalent to POSIX listen().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] backlog Maximum number of incoming connection simultaneously waiting to be accepdted with urosConnAccept().
Returns
Error code.
Definition at line 272 of file urosConn.c.
References uros_lld_conn_listen().
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_err_t urosConnConnect (UrosConn * cp, const UrosAddr * remaddrp)
Connects to a remote address.
See Also
uros_lld_conn_connect()
Note
Conceptually equivalent to POSIX connect().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] remaddrp Pointer to the remote address descriptor to connect to.
Returns
Error code.
Definition at line 291 of file urosConn.c.
References uros_lld_conn_connect().
uros_err_t urosConnRecv (UrosConn * cp, void ** bufpp, size_t * buflenp)
Receives some data.
The connection object waits until some data is received from the remote address. The pointer to the received data is returned, with a length up to the requested one.
See Also
uros_lld_conn_recv()
Warning
Not conceptually equivalent to POSIX connect(), as the buffer is not provided by the user, but by the middleware.
Precondition
The connection must be open and working.
Postcondition
Either data is received, or an UROS_ERR_EOF is returned when there is no more pending data (connection closed by remote).
Parameters
[in,out] cp Pointer to a communicating connection object.
[out] bufpp Indirect pointer to the received data buffer.
[in,out] buflenp Pointer to the buffer length in bytes, with the following meaning:
At call, it indicates the maximum length of the received data.
At return, it is the actual length of the received data.
Returns
Error code.
Definition at line 320 of file urosConn.c.
References uros_lld_conn_recv().
Referenced by urosRpcParserRefill(), urosTcpRosExpect(), urosTcpRosRecv(), and urosTcpRosSkip().
uros_err_t urosConnRecvFrom (UrosConn * cp, void ** bufpp, size_t * buflenp, const UrosAddr * remaddrp)
Receives some data from a remote address.
The connection object waits until some data is received from the remote address. The pointer to the received data is returned, with a length up to the requested one.
See Also
uros_lld_conn_recvfrom()
Note
Not available for TCP connections.
Warning
Not conceptually equivalent to POSIX connect(), as the buffer is not provided by the user, but by the middleware.
Parameters
[in,out] cp Pointer to a communicating connection object.
[out] bufpp Indirect pointer to the received data buffer.
[in,out] buflenp Pointer to the buffer length in bytes, with the following meaning:
At call, it indicates the maximum length of the received data.
At return, it is the actual length of the received data.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 349 of file urosConn.c.
References uros_lld_conn_recvfrom().
uros_err_t urosConnSend (UrosConn * cp, const void * bufp, size_t buflen)
Sends some data.
Sends the buffered data to the remote address. The data is copied to an internal buffer while streaming.
See Also
uros_lld_conn_send()
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
Returns
Error code.
Definition at line 377 of file urosConn.c.
References uros_lld_conn_send().
Referenced by urosRpcStreamerFlush(), and urosTcpRosSend().
uros_err_t urosConnSendConst (UrosConn * cp, const void * bufp, size_t buflen)
Sends some data.
Sends the buffered data to the remote address. The data is not copied to internal buffers.
See Also
uros_lld_conn_sendconst()
Note
If the low-level connectivity library does not support no-copy streaming, this is simply an alias to urosConnSend().
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The buffered data is granted not to change while it is still being streamed by the asynchronous low-level library thread.
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
Returns
Error code.
Definition at line 408 of file urosConn.c.
References uros_lld_conn_sendconst().
uros_err_t urosConnSendTo (UrosConn * cp, const void * bufp, size_t buflen, const UrosAddr * remaddrp)
Sends some data to a remote address.
Sends the buffered data to the remote address. The data is copied to an internal buffer while streaming.
See Also
uros_lld_conn_sendto()
Note
Not available for TCP connections.
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 438 of file urosConn.c.
References uros_lld_conn_sendto().
uros_err_t urosConnSendToConst (UrosConn * cp, const void * bufp, size_t buflen, const UrosAddr * remaddrp)
Sends some data to a remote address.
Sends the buffered data to the remote address. The data is not copied to internal buffers.
See Also
uros_lld_conn_sendtoconst()
Note
Not available for TCP connections.
If the low-level connectivity library does not support no-copy streaming, this is simply an alias to urosConnSend().
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The buffered data is granted not to change while it is still being streamed by the asynchronous low-level library thread.
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 473 of file urosConn.c.
References uros_lld_conn_sendtoconst().
uros_err_t urosConnShutdown (UrosConn * cp, uros_bool_t rx, uros_bool_t tx)
Terminates soem ends of a full-duplex channel.
The reception or the transission channels are closed.
See Also
uros_lld_conn_shutdown
Note
Conceptually equivalent to POSIX shutdown().
Warning
The connection is not actually closed after a call to this function, even with both rx and tx true.
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating UrosConn object.
[in] rx Close the receiver channel.
[in] tx Close the reansmitter channel.
Returns
Error code.
Definition at line 500 of file urosConn.c.
References uros_lld_conn_shutdown().
uros_err_t urosConnClose (UrosConn * cp)
Closes a connection.
Terminates all connection channels and releases any internal buffers.
See Also
uros_lld_conn_close()
Note
Conceptually equivalent to POSIX close().
Precondition
The connection must be open and working.
Postcondition
The connection is closed.
Any internal buffers are freed.
Parameters
[in,out] cp Pointer to a communicating UrosConn object.
Returns
Error code.
Definition at line 522 of file urosConn.c.
References uros_lld_conn_close().
Referenced by urosRpcSlaveListenerThread(), urosRpcSlaveServerThread(), urosTcpRosListenerThread(), and urosTcpRosServerThread().
uros_err_t urosConnGetTcpNoDelay (UrosConn * cp, uros_bool_t * enablep)
Gets the Nagle algorithm state.
Checks if the Nagle algorithm is enabled on the provided connection.
Note
Available only for TCP connections.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] enablep Pointer to the check result.
Returns
Error code.
Definition at line 540 of file urosConn.c.
References uros_lld_conn_gettcpnodelay().
uros_err_t urosConnSetTcpNoDelay (UrosConn * cp, uros_bool_t enable)
Sets the Nagle algorithm state.
When the Nagle algorithm is enabled, small packets are not immediately sent, but possibl enqueued, so that the TCP overhead is minimized. When it is disabled, even one-byte packets are immediately sent, to minimize latency despite the TCP overhead.
Note
Available only for TCP connections.
Parameters
[in,out] cp Pointer to a valid UrosConn object.
[in] enable Nagle algorithm activation switch.
Returns
Error code.
Definition at line 560 of file urosConn.c.
References uros_lld_conn_settcpnodelay().
uros_err_t urosConnGetRecvTimeout (UrosConn * cp, uint32_t * msp)
Gets the receiver timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] msp Pointer to the timeout value, in milliseconds.
Returns
Error code.
Definition at line 576 of file urosConn.c.
References uros_lld_conn_getrecvtimeout().
uros_err_t urosConnSetRecvTimeout (UrosConn * cp, uint32_t ms)
Sets the receiver timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] ms Timeout value, in milliseconds.
Returns
Error code.
Definition at line 592 of file urosConn.c.
References uros_lld_conn_setrecvtimeout().
Referenced by urosRpcSlaveListenerThread().
uros_err_t urosConnGetSendTimeout (UrosConn * cp, uint32_t * msp)
Gets the sender timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] msp Pointer to the timeout value, in milliseconds.
Returns
Error code.
Definition at line 608 of file urosConn.c.
References uros_lld_conn_getsendtimeout().
uros_err_t urosConnSetSendTimeout (UrosConn * cp, uint32_t ms)
Sets the sender timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] ms Timeout value, in milliseconds.
Returns
Error code.
Definition at line 624 of file urosConn.c.
References uros_lld_conn_setsendtimeout().
Referenced by urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
const char* urosConnLastErrorText (const UrosConn * cp)
Gets the last low-level connectivity library error text.
Parameters
[in] cp Pointer to the connection which generated the error to be analyzed.
Returns
Textural description of the last low-level connectovity error, null-terminated string.
Definition at line 638 of file urosConn.c.
References uros_lld_conn_lasterrortext().