μROSnode
Functions
User
Detailed Description
Functions
void urosUserErrPrintf (const char *formatp,...)
Prints a formatted error message.
void urosUserAllocMemPools (UrosNode *np)
Initializes and allocates memory pools.
void urosUserRegisterStaticMsgTypes (void)
Registers static message types.
void urosUserCreateListeners (void)
Creates the listener threads.
uros_err_t urosUserShutdown (const UrosString *msgp)
Shutdown callback function.
uros_err_t urosUserParamUpdate (const UrosString *keyp, const UrosRpcParam *paramp)
Updates a subscribed ROS parameter locally.
Function Documentation
void urosUserErrPrintf (const char * formatp, ...)
Prints a formatted error message.
User-defined callback function to print an error message on the desired output stream.
Parameters
[in] formatp Format string.
[in] ... printf() style arguments.
Definition at line 61 of file urosUser.c.
References urosAssert.
void urosUserAllocMemPools (UrosNode * np)
Initializes and allocates memory pools.
Function called at boot time, with platform-dependent stack size and alignment declarations.
Precondition
The memory pools of np have not been initialized yet.
Parameters
[in,out] np Pointer to an UrosNode object being initialized.
Definition at line 79 of file urosUser.c.
References urosAssert.
Referenced by urosNodeObjectInit().
void urosUserRegisterStaticMsgTypes (void)
Registers static message types.
This callback function is called at boot time to initialize the set of message types recognized by the system.
Precondition
The global static message type set has not been initialized yet.
Definition at line 95 of file urosUser.c.
void urosUserCreateListeners (void)
Creates the listener threads.
This callback function is called at boot time to create the listener threads of the middleware.
Precondition
The listener threads have not been created before.
Definition at line 107 of file urosUser.c.
Referenced by urosInit().
uros_err_t urosUserShutdown (const UrosString * msgp)
Shutdown callback function.
This callback function notifies the user that a shutdown() XMLRPC call was issued by the Master node, and has to be handled.
Parameters
[in] msgp Pointer to a string which explains the reason why it is asked to be shutdown.
Returns
Error code.
Definition at line 123 of file urosUser.c.
References UROS_OK, and urosAssert.
uros_err_t urosUserParamUpdate (const UrosString * keyp, const UrosRpcParam * paramp)
Updates a subscribed ROS parameter locally.
This callback function notifies the user that the value of a subscribed ROS parameter has changed.
Parameters
[in] keyp Pointer to the parameter name string.
[in] paramp Pointer to the parameter value.
Returns
Error code.
Definition at line 144 of file urosUser.c.
References UROS_OK, urosAssert, and urosStringNotEmpty().