μROSnode
Functions
Threading
Detailed Description
Semaphore
void urosSemObjectInit (UrosSem *semp, uros_cnt_t n)
Initializes a semaphore.
void urosSemClean (UrosSem *semp)
Cleans a semaphore.
void urosSemWait (UrosSem *semp)
Waits for a semaphore signal.
void urosSemSignal (UrosSem *semp)
Semaphore signal.
uros_cnt_t urosSemValue (UrosSem *semp)
Gets the semaphore value.
Mutex
void urosMutexObjectInit (UrosMutex *mtxp)
Initializes a mutex.
void urosMutexClean (UrosMutex *mtxp)
Cleans a mutex.
void urosMutexLock (UrosMutex *mtxp)
Locks a mutex.
void urosMutexUnlock (UrosMutex *mtxp)
Unlocks a mutex.
Condition variable
void urosCondVarObjectInit (UrosCondVar *cvp)
Initializes a condvar.
void urosCondVarClean (UrosCondVar *cvp)
Cleans a condvar.
void urosCondVarWait (UrosCondVar *cvp, UrosMutex *mtxp)
Waits for a condvar signal.
void urosCondVarSignal (UrosCondVar *cvp)
Single condvar signal.
void urosCondVarBroadcast (UrosCondVar *cvp)
Broadcast condvar signal.
Thread pool
uros_err_t urosThreadPoolObjectInit (UrosThreadPool *poolp, UrosMemPool *stackpoolp, uros_proc_f routine, const char *namep, uros_prio_t priority)
Initializes a thread pool.
void urosThreadPoolClean (UrosThreadPool *poolp)
Cleans a thread pool.
uros_err_t urosThreadPoolCreateAll (UrosThreadPool *poolp)
Creates all the thread pool threads.
uros_err_t urosThreadPoolJoinAll (UrosThreadPool *poolp)
uros_err_t urosThreadPoolStartWorker (UrosThreadPool *poolp, void *argp)
Starts a worker thread.
uros_err_t urosThreadPoolWorkerThread (UrosThreadPool *poolp)
Worker thread.
Thread
UrosThreadId urosThreadSelf (void)
Gets the current thread identifier.
const char * urosThreadGetName (UrosThreadId id)
Gets the name of the thread.
uros_err_t urosThreadCreateStatic (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, void *stackp, size_t stacksize)
Creates a thread with a static stack.
uros_err_t urosThreadCreateFromMemPool (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, UrosMemPool *mempoolp)
Creates a thread allocating the stack from a memory pool.
uros_err_t urosThreadCreateFromHeap (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, size_t stacksize)
Creates a thread allocating the stack on the deafult heap.
uros_err_t urosThreadJoin (UrosThreadId id)
Joins a thread.
void urosThreadSleepSec (uint32_t sec)
Sleeps for some seconds.
void urosThreadSleepMsec (uint32_t msec)
Sleeps for some milliseconds.
void urosThreadSleepUsec (uint32_t usec)
Sleeps for some microseconds.
uint32_t urosGetTimestampMsec (void)
Current timestamp in milliseconds.
Function Documentation
void urosSemObjectInit (UrosSem * semp, uros_cnt_t n)
Initializes a semaphore.
The semaphore object is initialized, and an initial count is assigned.
Precondition
The semaphore is not initialized.
Parameters
[in,out] semp Pointer to an allocated UrosSem object.
n Initial semaphore count.
Definition at line 80 of file urosThreading.c.
References uros_lld_sem_objectinit().
void urosSemClean (UrosSem * semp)
Cleans a semaphore.
Deallocates any memory chunks allocated by the object itself.
Precondition
The semaphore is initialized.
Postcondition
The semaphore is not initialized, call urosSemObjectInit() to use it again.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 96 of file urosThreading.c.
References uros_lld_sem_clean().
void urosSemWait (UrosSem * semp)
Waits for a semaphore signal.
Waits until the semaphore counter is positive. When positive, it is decremented and the procedure returns the control to the caller.
Note
Depending on the low-level implementation, it may support a priority inversion mechanism.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 111 of file urosThreading.c.
References uros_lld_sem_wait().
void urosSemSignal (UrosSem * semp)
Semaphore signal.
Increments a semaphore counter.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 123 of file urosThreading.c.
References uros_lld_sem_signal().
uros_cnt_t urosSemValue (UrosSem * semp)
Gets the semaphore value.
Reads the current semaphore value.
Warning
Thread-safe, but the value may not be consistent after a call to this function.
Parameters
[in] semp Pointer to an initialized UrosSem object.
Returns
Current semaphore count.
Definition at line 139 of file urosThreading.c.
References uros_lld_sem_value().
void urosMutexObjectInit (UrosMutex * mtxp)
Initializes a mutex.
The mutex object is initialized, and set as unlocked.
Precondition
The mutex is not initialized.
Postcondition
The mutex is unlocked.
Parameters
[in,out] mtxp Pointer to an allocated UrosMutex object.
Definition at line 161 of file urosThreading.c.
References uros_lld_mutex_objectinit().
Referenced by urosMemPoolObjectInit(), urosNodeObjectInit(), urosThreadPoolObjectInit(), and urosTpcRosStatusObjectInit().
void urosMutexClean (UrosMutex * mtxp)
Cleans a mutex.
Deallocates any memory chunks allocated by the object itself.
Precondition
The mutex is initialized.
Postcondition
The mutex is not initialized, call urosMutexObjectInit() to use it again.
Parameters
[in,out] mtxp Pointer to an initialized UrosMutex object.
Definition at line 177 of file urosThreading.c.
References uros_lld_mutex_clean().
Referenced by urosThreadPoolClean().
void urosMutexLock (UrosMutex * mtxp)
Locks a mutex.
Tries to lock a mutex. If the mutex is already locked, it waits until it is unlocked.
Note
Depending on the low-level implementation, it may support a priority inversion mechanism.
Postcondition
The mutex is locked.
Parameters
[in,out] mtxp Pointer to an initialized UrosMutex object.
Definition at line 194 of file urosThreading.c.
References uros_lld_mutex_lock().
Referenced by urosMemPoolAlloc(), urosMemPoolFree(), urosMemPoolNumFree(), urosNodeFindNewPublishers(), urosNodePublishService(), urosNodePublishServiceByDesc(), urosNodePublishTopic(), urosNodePublishTopicByDesc(), urosNodeSubscribeParam(), urosNodeSubscribeParamByDesc(), urosNodeSubscribeTopic(), urosNodeSubscribeTopicByDesc(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeParam(), urosNodeUnsubscribeTopic(), urosRpcSlaveListenerThread(), urosTcpRosServerThread(), urosTcpRosServiceDone(), urosTcpRosStatusCheckExit(), urosTcpRosStatusIssueExit(), urosTcpRosTopicPublisherDone(), urosTcpRosTopicSubscriberDone(), urosThreadPoolCreateAll(), urosThreadPoolJoinAll(), urosThreadPoolStartWorker(), and urosThreadPoolWorkerThread().
void urosMutexUnlock (UrosMutex * mtxp)
Unlocks a mutex.
Precondition
The mutex is locked.
Postcondition
The mutex is unlocked.
Parameters
[in,out] mtxp Pointer to a locked UrosMutex object.
Definition at line 208 of file urosThreading.c.
References uros_lld_mutex_unlock().
Referenced by urosMemPoolAlloc(), urosMemPoolFree(), urosMemPoolNumFree(), urosNodeFindNewPublishers(), urosNodePublishService(), urosNodePublishTopic(), urosNodeSubscribeParam(), urosNodeSubscribeTopic(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeTopic(), urosRpcSlaveListenerThread(), urosTcpRosServerThread(), urosTcpRosServiceDone(), urosTcpRosStatusCheckExit(), urosTcpRosStatusIssueExit(), urosTcpRosTopicPublisherDone(), urosTcpRosTopicSubscriberDone(), urosThreadPoolCreateAll(), urosThreadPoolJoinAll(), urosThreadPoolStartWorker(), and urosThreadPoolWorkerThread().
void urosCondVarObjectInit (UrosCondVar * cvp)
Initializes a condvar.
Precondition
The condvar is not initialized.
Postcondition
The condvar is initialized.
Parameters
[in,out] cvp Pointer to an allocated UrosCondVar object.
Definition at line 229 of file urosThreading.c.
References uros_lld_condvar_objectinit().
Referenced by urosThreadPoolObjectInit().
void urosCondVarClean (UrosCondVar * cvp)
Cleans a condvar.
Deallocates any memory chunks allocated by the object itself.
Precondition
The condvar is initialized.
Postcondition
The condvar is not initialized, call urosConvVarObjectInit() to use it again.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 245 of file urosThreading.c.
References uros_lld_condvar_clean().
Referenced by urosThreadPoolClean().
void urosCondVarWait (UrosCondVar * cvp, UrosMutex * mtxp)
Waits for a condvar signal.
Waits until the condvar is signalled.
Note
This procedure must be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
[in,out] mtxp Pointer to the mutex guarding this condvar.
Definition at line 261 of file urosThreading.c.
References uros_lld_condvar_wait().
Referenced by urosThreadPoolCreateAll(), urosThreadPoolJoinAll(), urosThreadPoolStartWorker(), and urosThreadPoolWorkerThread().
void urosCondVarSignal (UrosCondVar * cvp)
Single condvar signal.
Signals a condvar to a single waiting thread.
Note
This procedure may be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 275 of file urosThreading.c.
References uros_lld_condvar_signal().
Referenced by urosThreadPoolStartWorker(), and urosThreadPoolWorkerThread().
void urosCondVarBroadcast (UrosCondVar * cvp)
Broadcast condvar signal.
Signals a condvar to all of the waiting threads.
Note
This procedure may be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 289 of file urosThreading.c.
References uros_lld_condvar_broadcast().
Referenced by urosThreadPoolJoinAll().
uros_err_t urosThreadPoolObjectInit (UrosThreadPool * poolp, UrosMemPool * stackpoolp, uros_proc_f routine, const char * namep, uros_prio_t priority)
Initializes a thread pool.
The thread pool is initialized with the related attributes, and any private members.
Precondition
The thread pool is not initialized.
Parameters
[in,out] poolp Pointer to an allocated UrosThreadPool object.
[in] stackpoolp Pointer to an initialized memory pool.
[in] routine Routine of the worker threads.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Default worker thread priority.
Returns
Error code.
Definition at line 322 of file urosThreading.c.
References UrosThreadPool::argp, UrosThreadPool::busyCnt, UrosThreadPool::busyCond, UrosThreadPool::busyMtx, UrosThreadPool::exitFlag, UrosThreadPool::namep, UrosThreadPool::priority, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::routine, UrosThreadPool::size, UrosThreadPool::stackPoolp, UrosThreadPool::threadsp, UROS_ERR_NOMEM, UROS_FALSE, UROS_OK, urosAlloc(), urosAssert, urosCondVarObjectInit(), urosMemPoolBlockSize(), urosMemPoolNumFree(), and urosMutexObjectInit().
Referenced by urosNodeObjectInit().
void urosThreadPoolClean (UrosThreadPool * poolp)
Cleans a thread pool.
Deinitializes private members, and deallocates any allocated objects.
Note
The related memory pool is not deallocated nor uninitialized.
Precondition
The thread pool is initialized.
No worker thread is running.
Postcondition
The thread pool is not initialized, call urosThreadPoolObjectInit() to use it again.
Parameters
[in,out] poolp Pointer to an initialized memory pool.
Definition at line 365 of file urosThreading.c.
References UrosThreadPool::argp, UrosThreadPool::busyCnt, UrosThreadPool::busyCond, UrosThreadPool::busyMtx, UrosThreadPool::exitFlag, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::routine, UrosThreadPool::size, UrosThreadPool::stackPoolp, UrosThreadPool::threadsp, UROS_FALSE, urosAssert, urosCondVarClean(), urosFree(), and urosMutexClean().
uros_err_t urosThreadPoolCreateAll (UrosThreadPool * poolp)
Creates all the thread pool threads.
The thread pool is filled with new worker threads. The fucntion waits until all the worker threads are ready.
See Also
urosThreadPoolJoinAll()
urosThreadPoolClean()
Precondition
The thread pools has no allocated worker threads.
Postcondition
All the worker threads are ready.
Parameters
[in,out] poolp Pointer to an initialized UrosThreadPool object.
Returns
Error code.
Definition at line 398 of file urosThreading.c.
References UrosThreadPool::exitFlag, UrosThreadPool::namep, UrosThreadPool::priority, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::size, UrosThreadPool::stackPoolp, UrosThreadPool::threadsp, UROS_ERR_NOMEM, UROS_FALSE, UROS_OK, urosAssert, urosCondVarWait(), urosError, urosMutexLock(), urosMutexUnlock(), urosThreadCreateFromMemPool(), and urosThreadPoolWorkerThread().
Referenced by urosInit().
uros_err_t urosThreadPoolJoinAll (UrosThreadPool * poolp)
brief Joins all the worker threads.
Waits for all the worker threads to terminate.
See Also
urosThreadPoolClean()
Precondition
The worker threads are created.
Postcondition
The worker threads have terminated and cannot be started again.
Parameters
[in,out] poolp Pointer to an initialized UrosThreadPool object.
Returns
Error code.
Definition at line 443 of file urosThreading.c.
References UrosThreadPool::busyCnt, UrosThreadPool::busyCond, UrosThreadPool::busyMtx, UrosThreadPool::exitFlag, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::size, UrosThreadPool::stackPoolp, UrosThreadPool::threadsp, UROS_OK, UROS_TRUE, urosAssert, urosCondVarBroadcast(), urosCondVarWait(), urosMutexLock(), urosMutexUnlock(), and urosThreadJoin().
uros_err_t urosThreadPoolStartWorker (UrosThreadPool * poolp, void * argp)
Starts a worker thread.
Waits until there is a ready worker thread in the pool, selects it, passes the argument provided by the user to it, and lets it run.
Precondition
The worker threads are created.
Postcondition
The worker thread is running the routine assigne to the pool, with the argument provided by the user.
Parameters
[in,out] poolp Pointer to an initialized UrosThreadPool object.
[in] argp Argument passed to the thread routine.
Returns
Error code.
Definition at line 492 of file urosThreading.c.
References UrosThreadPool::argp, UrosThreadPool::busyCnt, UrosThreadPool::busyCond, UrosThreadPool::busyMtx, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::stackPoolp, UROS_OK, urosAssert, urosCondVarSignal(), urosCondVarWait(), urosMutexLock(), and urosMutexUnlock().
Referenced by urosRpcSlaveConnectToPublishers(), urosRpcSlaveListenerThread(), and urosTcpRosListenerThread().
uros_err_t urosThreadPoolWorkerThread (UrosThreadPool * poolp)
Worker thread.
This is the actual thread function created by urosThreadPoolCreateAll(). After creation, it waits until the user starts this thread by calling urosThreadPoolStartWorker(), when this is the first ready thread selected.
After executing the routine defined with urosThreadPoolObjectInit(), this thread goes back into the waiting state.
To exit from this thread, it first has to be put back into the waiting state. Then, the exitFlag of the pool must be set to true, so that by calling urosThreadPoolStartWorker() again on this thread, the latter knows it must exit and not execute the user routine.
Parameters
[in] poolp Pointer to the UrosThreadPool which created this thread.
Returns
Error code returned by the user routine.
Definition at line 535 of file urosThreading.c.
References UrosThreadPool::argp, UrosThreadPool::busyCnt, UrosThreadPool::busyCond, UrosThreadPool::busyMtx, UrosThreadPool::exitFlag, UrosThreadPool::readyCnt, UrosThreadPool::readyCond, UrosThreadPool::readyMtx, UrosThreadPool::routine, UROS_OK, urosAssert, urosCondVarSignal(), urosCondVarWait(), urosMutexLock(), and urosMutexUnlock().
Referenced by urosThreadPoolCreateAll().
UrosThreadId urosThreadSelf (void)
Gets the current thread identifier.
Returns
The current thread identifier.
Definition at line 590 of file urosThreading.c.
References uros_lld_thread_self().
Referenced by urosRpcSlaveListenerThread().
const char* urosThreadGetName (UrosThreadId id)
Gets the name of the thread.
Parameters
[in] id Thread identifier.
Returns
Pointer to the name of the thread string, null-terminated.
Return values
NULL No name assigned to the thread.
Definition at line 605 of file urosThreading.c.
References uros_lld_thread_getname().
uros_err_t urosThreadCreateStatic (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, void * stackp, size_t stacksize)
Creates a thread with a static stack.
Creates a new thread. The memory chunk for the stack is externally declared, and is simply referenced. It is usually allocated as a static buffer.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] stackp Pointer to the externally allocated stack buffer.
[in] stacksize Stack size, in bytes.
Returns
Error code.
Definition at line 637 of file urosThreading.c.
References uros_lld_thread_createstatic(), UROS_NOP, UROS_OK, urosError, and urosErrorText().
uros_err_t urosThreadCreateFromMemPool (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, UrosMemPool * mempoolp)
Creates a thread allocating the stack from a memory pool.
Creates a new thread. The memory chunk for the stack is allocated from a memory pool.
Warning
The thread creation is suspended until there is a free slot in the memory pool.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] mempoolp Pointer to the memory pool where to allocate a stack.
Returns
Error code.
Definition at line 678 of file urosThreading.c.
References uros_lld_thread_createfrommempool(), UROS_NOP, UROS_OK, urosError, and urosErrorText().
Referenced by urosThreadPoolCreateAll().
uros_err_t urosThreadCreateFromHeap (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, size_t stacksize)
Creates a thread allocating the stack on the deafult heap.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] stacksize Stack size, in bytes.
Returns
Error code.
Definition at line 715 of file urosThreading.c.
References uros_lld_thread_createfromheap(), UROS_NOP, UROS_OK, urosError, and urosErrorText().
uros_err_t urosThreadJoin (UrosThreadId id)
Joins a thread.
Waits until the required thread has exited, and releases its allocated memory.
Postcondition
The required thread does not exist anymore.
Any resources allocated by the thread creation are released (e.g. stack).
Parameters
[in] id Identifier of the thread being joined.
Returns
Error code.
Definition at line 744 of file urosThreading.c.
References uros_lld_thread_join(), UROS_NOP, UROS_OK, urosError, and urosErrorText().
Referenced by urosThreadPoolJoinAll().
void urosThreadSleepSec (uint32_t sec)
Sleeps for some seconds.
Puts the thread in sleep state for the provided amount of time.
Parameters
[in] sec Number of seconds to sleep.
Definition at line 761 of file urosThreading.c.
void urosThreadSleepMsec (uint32_t msec)
Sleeps for some milliseconds.
Puts the thread in sleep state for the provided amount of time.
Parameters
[in] sec Number of milliseconds to sleep.
Definition at line 773 of file urosThreading.c.
void urosThreadSleepUsec (uint32_t usec)
Sleeps for some microseconds.
Puts the thread in sleep state for the provided amount of time.
Parameters
[in] sec Number of microseconds to sleep.
Definition at line 785 of file urosThreading.c.
uint32_t urosGetTimestampMsec (void)
Current timestamp in milliseconds.
Note
The resolution is in milliseconds, but the precision may not be.
Returns
The current timestamp, with a resolution of one millisecond.
Definition at line 797 of file urosThreading.c.