μROSnode
Functions
Node
Detailed Description
Functions
void urosNodeObjectInit (UrosNode *np)
Initializes a node object.
void urosNodeConfigLoadDefaults (UrosNodeConfig *cfgp)
Loads the default node configuration.
void urosNodeConfigLoad (UrosNodeConfig *cfgp)
Loads node configuration.
void urosNodeConfigSave (const UrosNodeConfig *cfgp)
Saves the node configuration.
uros_err_t urosNodePublishTopic (const UrosString *namep, const UrosString *typep, uros_proc_f procf)
uros_err_t urosNodePublishTopicSZ (const char *namep, const char *typep, uros_proc_f procf)
uros_err_t urosNodePublishTopicByDesc (UrosTopic *topicp)
Publishes a topic by its descriptor.
uros_err_t urosNodeUnpublishTopic (const UrosString *namep)
Unpublishes a topic.
uros_err_t urosNodeSubscribeTopic (const UrosString *namep, const UrosString *typep, uros_proc_f procf)
uros_err_t urosNodeSubscribeTopicSZ (const char *namep, const char *typep, uros_proc_f procf)
uros_err_t urosNodeSubscribeTopicByDesc (UrosTopic *topicp)
Subscribes to a topic by its descriptor.
uros_err_t urosNodeUnsubscribeTopic (const UrosString *namep)
Unsubscribes to a topic.
uros_err_t urosNodePublishService (const UrosString *namep, const UrosString *typep, uros_proc_f procf)
uros_err_t urosNodePublishServiceSZ (const char *namep, const char *typep, uros_proc_f procf)
uros_err_t urosNodePublishServiceByDesc (const UrosTopic *servicep)
Publishes a service by its descriptor.
uros_err_t urosNodeUnpublishService (const UrosString *namep)
Unpublishes a service.
uros_err_t urosNodeSubscribeParam (const UrosString *namep)
uros_err_t urosNodeSubscribeParamSZ (const char *namep)
uros_err_t urosNodeSubscribeParamByDesc (const UrosTopic *paramp)
Subscribes to a parameter by its descriptor.
uros_err_t urosNodeUnsubscribeParam (const UrosString *namep)
Subscribes to a parameter.
uros_err_t urosNodeFindNewPublishers (const UrosString *topicnamep, const UrosRpcParam *publishersp, UrosList *newpubsp)
Find new publishers for a given topic.
Function Documentation
void urosNodeObjectInit (UrosNode * np)
Initializes a node object.
This procedure:
loads a nullified configuration
initializes the status lists
initializes the status locks
initializes and allocates memory pools
initializes thread pools
Precondition
The node has not been initialized yet.
Parameters
[in,out] np Pointer to the UrosNode to be initialized.
Definition at line 90 of file urosNode.c.
References UrosNode::config, UrosNodeStatus::pubServiceList, UrosNodeStatus::pubServiceListLock, UrosNodeStatus::pubTcpList, UrosNodeStatus::pubTcpListLock, UrosNodeStatus::pubTopicList, UrosNodeStatus::pubTopicListLock, UrosNodeStatus::slaveMemPool, UrosNodeStatus::slaveThdPool, UrosNode::status, UrosNodeStatus::subParamList, UrosNodeStatus::subParamListLock, UrosNodeStatus::subTcpList, UrosNodeStatus::subTcpListLock, UrosNodeStatus::subTopicList, UrosNodeStatus::subTopicListLock, UrosNodeStatus::tcpcliMemPool, UrosNodeStatus::tcpcliThdPool, UrosNodeStatus::tcpsvrMemPool, UrosNodeStatus::tcpsvrThdPool, UROS_TCPROS_CLIENT_PRIO, UROS_TCPROS_SERVER_PRIO, UROS_XMLRPC_SLAVE_PRIO, urosAssert, urosListObjectInit(), urosMutexObjectInit(), urosRpcSlaveServerThread(), urosTcpRosClientThread(), urosTcpRosServerThread(), urosThreadPoolObjectInit(), urosUserAllocMemPools(), UrosNodeStatus::xmlrpcPid, and UrosNodeStatus::xmlrpcPidLock.
Referenced by urosInit().
void urosNodeConfigLoadDefaults (UrosNodeConfig * cfgp)
Loads the default node configuration.
Any previously allocated data is freed, then the default node configuration is loaded.
Precondition
The related UrosNode is initialized.
Parameters
[in,out] cfgp Pointer to the target configuration descriptor.
Definition at line 147 of file urosNode.c.
References UrosIp::dword, UrosAddr::ip, UrosNodeConfig::masterAddr, UrosNodeConfig::masterUri, UrosNodeConfig::nodeName, UrosAddr::port, UrosNodeConfig::tcprosAddr, UrosNodeConfig::tcprosUri, UROS_STRINGIFY2, UROS_TCPROS_LISTENER_IP, UROS_TCPROS_LISTENER_IP_SZ, UROS_TCPROS_LISTENER_PORT, UROS_XMLRPC_LISTENER_IP, UROS_XMLRPC_LISTENER_IP_SZ, UROS_XMLRPC_LISTENER_PORT, UROS_XMLRPC_MASTER_IP, UROS_XMLRPC_MASTER_IP_SZ, UROS_XMLRPC_MASTER_PORT, urosAssert, urosStringClean(), urosStringCloneZ(), UrosNodeConfig::xmlrpcAddr, and UrosNodeConfig::xmlrpcUri.
void urosNodeConfigLoad (UrosNodeConfig * cfgp)
Loads node configuration.
Any previously allocated data is freed, then the configuration is loaded from a static non-volatile memory chunk.
See Also
uros_lld_nodeconfig_load()
Precondition
The related UrosNode is initialized.
Parameters
[in,out] cfgp Pointer to the target configuration descriptor.
Definition at line 187 of file urosNode.c.
References uros_lld_nodeconfig_load().
Referenced by urosInit().
void urosNodeConfigSave (const UrosNodeConfig * cfgp)
Saves the node configuration.
The node configuration is saved to a static non-volatile memory chunk.
See Also
uros_lld_nodeconfig_save()
Precondition
The related UrosNode is initialized.
Parameters
[in] cfgp Pointer to the configuration descriptor to be saved.
Definition at line 203 of file urosNode.c.
References uros_lld_nodeconfig_save().
uros_err_t urosNodePublishTopic (const UrosString * namep, const UrosString * typep, uros_proc_f procf)
TODO
Definition at line 211 of file urosNode.c.
References UrosTopic::name, UrosTopic::procf, UrosNodeStatus::pubTopicList, UrosNodeStatus::pubTopicListLock, UrosNode::status, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, UROS_STRARG, urosAssert, urosError, urosFindStaticMsgType(), urosMutexLock(), urosMutexUnlock(), urosNew, urosNodePublishTopicByDesc(), urosStringClone(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and urosTopicObjectInit().
Referenced by urosNodePublishTopicSZ().
uros_err_t urosNodePublishTopicSZ (const char * namep, const char * typep, uros_proc_f procf)
TODO
Definition at line 253 of file urosNode.c.
References urosAssert, urosNodePublishTopic(), and urosStringAssignZ().
uros_err_t urosNodePublishTopicByDesc (UrosTopic * topicp)
Publishes a topic by its descriptor.
Issues a publishTopic() call to the XMLRPC Master.
See Also
urosRpcCallRegisterPublisher()
Warning
The access to the topic registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to publish/unpublish any topics.
Precondition
The topic is not published.
The topic descriptor must have the service flag set to 0.
Postcondition
- If successful, the topic descriptor is referenced by the topic registry, and is no longer modifiable by the caller function.
If unsuccessful, the topic descriptor can be deallocated by the caller function.
Parameters
[in] topicp Pointer to the topic descriptor to be published and registered.
Returns
Error code.
Definition at line 290 of file urosNode.c.
References UrosRpcResponse::code, UrosNode::config, UrosNodeConfig::masterAddr, UrosMsgType::name, UrosTopic::name, UrosNodeConfig::nodeName, UrosNodeStatus::pubTopicListLock, UrosTopic::refcnt, UrosNode::status, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_OK, UROS_RPCC_SUCCESS, UROS_STRARG, urosAssert, urosError, urosErrorText(), urosMutexLock(), urosRpcCallRegisterPublisher(), urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosNodeConfig::xmlrpcUri.
Referenced by urosNodePublishTopic().
uros_err_t urosNodeUnpublishTopic (const UrosString * namep)
Unpublishes a topic.
Issues an unpublishTopic() call to the XMLRPC Master.
See Also
urosRpcCallUnregisterPublisher()
Warning
The access to the topic registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to publish/unpublish any topics.
Precondition
The topic is published.
Postcondition
If successful, the topic descriptor is dereferenced by the topic registry, and will be freed:
by this function, if there are no publishing TCPROS threads, or
by the last publishing TCPROS thread which references the topic.
Parameters
[in] namep Pointer to a string which names the topic.
Returns
Error code.
Definition at line 361 of file urosNode.c.
References UrosNode::config, UrosListNode::datap, uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosTopic::flags, UrosList::headp, UrosList::length, UrosNodeConfig::masterAddr, UrosListNode::nextp, UrosNodeConfig::nodeName, UrosNodeStatus::pubTcpList, UrosNodeStatus::pubTcpListLock, UrosNodeStatus::pubTopicList, UrosNodeStatus::pubTopicListLock, uros_topicflags_t::service, UrosNode::status, UrosTcpRosStatus::threadExit, UrosTcpRosStatus::threadExitMtx, UrosTcpRosStatus::topicp, UROS_ERR_BADPARAM, UROS_NOP, UROS_OK, UROS_STRARG, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosListNodeDelete(), urosListRemove(), urosMutexLock(), urosMutexUnlock(), urosRpcCallUnregisterPublisher(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and UrosNodeConfig::xmlrpcUri.
uros_err_t urosNodeSubscribeTopic (const UrosString * namep, const UrosString * typep, uros_proc_f procf)
TODO
Definition at line 425 of file urosNode.c.
References UrosTopic::name, UrosTopic::procf, UrosNode::status, UrosNodeStatus::subTopicList, UrosNodeStatus::subTopicListLock, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, UROS_STRARG, urosAssert, urosError, urosFindStaticMsgType(), urosMutexLock(), urosMutexUnlock(), urosNew, urosNodeSubscribeTopicByDesc(), urosStringClone(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and urosTopicObjectInit().
Referenced by urosNodeSubscribeTopicSZ().
uros_err_t urosNodeSubscribeTopicSZ (const char * namep, const char * typep, uros_proc_f procf)
TODO
Definition at line 467 of file urosNode.c.
References urosAssert, urosNodeSubscribeTopic(), and urosStringAssignZ().
uros_err_t urosNodeSubscribeTopicByDesc (UrosTopic * topicp)
Subscribes to a topic by its descriptor.
Issues a registerSubscriber() call to the XMLRPC Master, and connects to known publishers.
See Also
urosRpcCallRegisterSubscriber()
urosNodeFindNewPublishers()
urosRpcSlaveConnectToPublishers()
Warning
The access to the topic registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to subscribe/unsubscribe to any topics.
Precondition
The topic is not subscribed.
The topic descriptor must have the service flag set to 0.
Postcondition
- If successful, the topic descriptor is referenced by the topic registry, and is no longer modifiable by the caller function.
If unsuccessful, the topic descriptor can be deallocated by the caller function.
Connects to known publishers listed by a successful response.
Parameters
[in] topicp Pointer to the topic descriptor to be subscribed to and registered.
Returns
Error code.
Definition at line 508 of file urosNode.c.
References UrosRpcResponse::code, UrosNode::config, UrosNodeConfig::masterAddr, UrosMsgType::name, UrosTopic::name, UrosNodeConfig::nodeName, UrosTopic::refcnt, UrosNode::status, UrosNodeStatus::subTopicListLock, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_OK, UROS_RPCC_SUCCESS, UROS_STRARG, urosAssert, urosError, urosListObjectInit(), urosMutexLock(), urosRpcCallRegisterSubscriber(), urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosNodeConfig::xmlrpcUri.
Referenced by urosNodeSubscribeTopic().
uros_err_t urosNodeUnsubscribeTopic (const UrosString * namep)
Unsubscribes to a topic.
Issues an unregisterSubscriber() call to the XMLRPC Master.
See Also
urosRpcCallUnregisterSubscriber()
Warning
The access to the topic registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to publish/unpublish any topics.
Precondition
The topic is published.
Postcondition
If successful, the topic descriptor is dereferenced by the topic registry, and will be freed:
by this function, if there are no subscribing TCPROS threads, or
by the last subscribing TCPROS thread which references the topic.
Parameters
[in] namep Pointer to a string which names the topic.
Returns
Error code.
Definition at line 593 of file urosNode.c.
References UrosNode::config, UrosListNode::datap, uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosTopic::flags, UrosList::headp, UrosList::length, UrosNodeConfig::masterAddr, UrosListNode::nextp, UrosNodeConfig::nodeName, uros_topicflags_t::service, UrosNode::status, UrosNodeStatus::subTcpList, UrosNodeStatus::subTcpListLock, UrosNodeStatus::subTopicList, UrosNodeStatus::subTopicListLock, UrosTcpRosStatus::threadExit, UrosTcpRosStatus::threadExitMtx, UrosTcpRosStatus::topicp, UROS_ERR_BADPARAM, UROS_NOP, UROS_OK, UROS_STRARG, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosListNodeDelete(), urosListRemove(), urosMutexLock(), urosMutexUnlock(), urosRpcCallUnregisterSubscriber(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and UrosNodeConfig::xmlrpcUri.
uros_err_t urosNodePublishService (const UrosString * namep, const UrosString * typep, uros_proc_f procf)
TODO
Definition at line 657 of file urosNode.c.
References UrosTopic::name, UrosTopic::procf, UrosNodeStatus::pubServiceList, UrosNodeStatus::pubServiceListLock, UrosNode::status, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, UROS_STRARG, urosAssert, urosError, urosFindStaticSrvType(), urosMutexLock(), urosMutexUnlock(), urosNew, urosNodePublishServiceByDesc(), urosStringClone(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and urosTopicObjectInit().
Referenced by urosNodePublishServiceSZ().
uros_err_t urosNodePublishServiceSZ (const char * namep, const char * typep, uros_proc_f procf)
TODO
Definition at line 700 of file urosNode.c.
References urosAssert, urosNodePublishService(), and urosStringAssignZ().
uros_err_t urosNodePublishServiceByDesc (const UrosTopic * servicep)
Publishes a service by its descriptor.
Issues a registerService() call to the XMLRPC Master.
Warning
The access to the service registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to publish/unpublish any services.
See Also
urosRpcCallRegisterService()
Precondition
The service is not published.
The service descriptor must have the service flag set to 1.
Postcondition
- If successful, the service descriptor is referenced by the service registry, and is no longer modifiable by the caller function.
If unsuccessful, the service descriptor can be deallocated by the caller function.
Parameters
[in] servicep Pointer to the service descriptor to be published and registered.
Returns
Error code.
Definition at line 738 of file urosNode.c.
References UrosRpcResponse::code, UrosNode::config, UrosNodeConfig::masterAddr, UrosMsgType::name, UrosTopic::name, UrosNodeConfig::nodeName, UrosNodeStatus::pubServiceListLock, UrosNode::status, UrosNodeConfig::tcprosUri, UrosTopic::typep, UROS_ERR_BADPARAM, UROS_OK, UROS_RPCC_SUCCESS, UROS_STRARG, urosAssert, urosError, urosMutexLock(), urosRpcCallRegisterService(), urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosNodeConfig::xmlrpcUri.
Referenced by urosNodePublishService().
uros_err_t urosNodeUnpublishService (const UrosString * namep)
Unpublishes a service.
Issues an unregisterService() call to the XMLRPC Master.
See Also
urosRpcCallUnregisterService()
Warning
The access to the service registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to publish/unpublish any services.
Precondition
The service is published.
Postcondition
If successful, the service descriptor is dereferenced by the service registry, and will be freed:
by this function, if there are no publishing TCPROS threads, or
by the last publishing TCPROS thread which references the service.
Parameters
[in] namep Pointer to a string which names the service.
Returns
Error code.
Definition at line 809 of file urosNode.c.
References UrosNode::config, UrosListNode::datap, uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosTopic::flags, UrosList::headp, UrosList::length, UrosNodeConfig::masterAddr, UrosListNode::nextp, UrosNodeConfig::nodeName, UrosNodeStatus::pubServiceList, UrosNodeStatus::pubServiceListLock, UrosNodeStatus::pubTcpList, UrosNodeStatus::pubTcpListLock, uros_topicflags_t::service, UrosNode::status, UrosTcpRosStatus::threadExit, UrosTcpRosStatus::threadExitMtx, UrosTcpRosStatus::topicp, UROS_ERR_BADPARAM, UROS_NOP, UROS_OK, UROS_STRARG, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosListNodeDelete(), urosListRemove(), urosMutexLock(), urosMutexUnlock(), urosRpcCallUnregisterService(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and UrosNodeConfig::xmlrpcUri.
uros_err_t urosNodeSubscribeParam (const UrosString * namep)
TODO
Definition at line 874 of file urosNode.c.
References UrosTopic::name, UrosNode::status, UrosNodeStatus::subParamList, UrosNodeStatus::subParamListLock, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, UROS_STRARG, urosAssert, urosError, urosMutexLock(), urosMutexUnlock(), urosNew, urosNodeSubscribeParamByDesc(), urosStringClone(), urosStringNotEmpty(), urosTopicDelete(), urosTopicListFindByName(), and urosTopicObjectInit().
Referenced by urosNodeSubscribeParamSZ().
uros_err_t urosNodeSubscribeParamSZ (const char * namep)
TODO
Definition at line 904 of file urosNode.c.
References urosAssert, urosNodeSubscribeParam(), and urosStringAssignZ().
uros_err_t urosNodeSubscribeParamByDesc (const UrosTopic * paramp)
Subscribes to a parameter by its descriptor.
Issues a subscribeParam() call to the XMLRPC Master, and connects to known publishers.
See Also
urosRpcCallSubscribeParam()
Warning
The access to the parameter registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to subscribe/unsubscribe to any parameters.
Precondition
The parameter has not been registered yet.
Postcondition
- If successful, the parameter descriptor is referenced by the parameter registry, and is no longer modifiable by the caller function.
If unsuccessful, the parameter descriptor can be deallocated by the caller function.
Parameters
[in] paramp Pointer to the parameter descriptor to be subscribed to and registered.
Returns
Error code.
Definition at line 937 of file urosNode.c.
References UrosRpcResponse::code, UrosNode::config, UrosNodeConfig::masterAddr, UrosTopic::name, UrosNodeConfig::nodeName, UrosNode::status, UrosNodeStatus::subParamListLock, UROS_ERR_BADPARAM, UROS_OK, UROS_RPCC_SUCCESS, UROS_STRARG, urosAssert, urosError, urosMutexLock(), urosRpcCallSubscribeParam(), urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosNodeConfig::xmlrpcUri.
Referenced by urosNodeSubscribeParam().
uros_err_t urosNodeUnsubscribeParam (const UrosString * namep)
Subscribes to a parameter.
Issues an unsubscribeParam() call to the XMLRPC Master, and connects to known publishers.
See Also
urosRpcCallUnubscribeParam()
Warning
The access to the parameter registry is thread-safe, but delays of the XMLRPC communication will delay also any other threads trying to subscribe/unsubscribe to any parameters.
Precondition
The parameter has been registered.
Postcondition
If successful, the parameter descriptor is unreferenced and deleted by the parameter registry.
Parameters
[in] namep Pointer to a string which names the parameter to be unregistered.
Returns
Error code.
Definition at line 1003 of file urosNode.c.
References UrosRpcResponse::code, UrosNode::config, UrosNodeConfig::masterAddr, UrosNodeConfig::nodeName, UrosNode::status, UrosNodeStatus::subParamList, UrosNodeStatus::subParamListLock, UROS_ERR_BADPARAM, UROS_OK, UROS_RPCC_SUCCESS, UROS_STRARG, urosAssert, urosError, urosMutexLock(), urosRpcCallUnsubscribeParam(), urosRpcResponseObjectInit(), urosStringNotEmpty(), urosTopicListFindByName(), and UrosNodeConfig::xmlrpcUri.
uros_err_t urosNodeFindNewPublishers (const UrosString * topicnamep, const UrosRpcParam * publishersp, UrosList * newpubsp)
Find new publishers for a given topic.
Scans through the provided publishers list to look for any new publishers.
Parameters
[in] topicnamep Pointer to a non-empty string which names the targeted topic.
[in] publishersp Pointer to an UrosRpcParam with UROS_RPCP_ARRAY class. It contains the list of current publishers, received for example through a XMLRPC call to subscribeTopic(). Each publisher is addressed by its URI.
[out] newpubsp Pointer to an empty list which will be populated by the newly discovered publishers, if any.
Returns
Error code.
Definition at line 1072 of file urosNode.c.
References UrosRpcParam::class, UrosTcpRosStatus::csp, UrosListNode::datap, UrosIp::dword, UrosTcpRosStatus::flags, UrosRpcParamList::headp, UrosList::headp, UrosAddr::ip, UrosList::length, UrosRpcParam::listp, UrosTopic::name, UrosRpcParamNode::nextp, UrosListNode::nextp, UrosRpcParamNode::param, UrosAddr::port, UrosConn::remaddr, uros_topicflags_t::service, UrosNode::status, UrosRpcParam::string, UrosNodeStatus::subTcpList, UrosNodeStatus::subTcpListLock, UrosTcpRosStatus::topicp, UROS_FALSE, UROS_OK, UROS_RPCP_ARRAY, urosAssert, urosListAdd(), urosListIsValid(), urosMutexLock(), urosMutexUnlock(), urosNew, urosStringCmp(), urosStringNotEmpty(), urosUriToAddr(), and UrosRpcParam::value.