μROSnode
Functions
TCPROS
Detailed Description
Functions
void urosTopicSubParamsDelete (uros_tcpcliargs_t *parp)
Deletes topic subscription parameters.
void urosTpcRosStatusObjectInit (UrosTcpRosStatus *tcpstp, UrosConn *csp)
Initializes a TCPROS status record.
void urosTpcRosStatusClean (UrosTcpRosStatus *tcpstp, uros_bool_t deep)
Cleans a TCPROS status record.
void urosTpcRosStatusDelete (UrosTcpRosStatus *tcpstp, uros_bool_t deep)
Deallocates a TCPROS status record.
void urosTcpRosStatusIssueExit (UrosTcpRosStatus *tcpstp)
Raises the exit flag.
uros_bool_t urosTcpRosStatusCheckExit (UrosTcpRosStatus *tcpstp)
Checks if the exit flag is raised.
void urosTcpRosArrayObjectInit (UrosTcpRosArray *arrayp)
Initializes a TCPROS array descriptor.
void urosTcpRosArrayClean (UrosTcpRosArray *arrayp)
Cleans a TCPROS array.
void urosTcpRosArrayDelete (UrosTcpRosArray *arrayp, uros_bool_t deep)
Deallocates a TCPROS array descriptor.
uros_err_t urosTcpRosSkip (UrosTcpRosStatus *tcpstp, size_t length)
Skips a number of bytes from the incoming TCPROS stream.
uros_err_t urosTcpRosExpect (UrosTcpRosStatus *tcpstp, void *tokp, size_t toklen)
Expects a token from the incoming TCPROS stream.
uros_err_t urosTcpRosRecv (UrosTcpRosStatus *tcpstp, void *bufp, size_t buflen)
Reads some data from the incoming TCPROS stream.
uros_err_t urosTcpRosRecvString (UrosTcpRosStatus *tcpstp, UrosString *strp)
Reads a string from the incoming TCPROS stream.
uros_err_t urosTcpRosSend (UrosTcpRosStatus *tcpstp, const void *bufp, size_t buflen)
Writes some data to the outgoing TCPROS stream.
uros_err_t urosTcpRosSendString (UrosTcpRosStatus *tcpstp, const UrosString *strp)
Writes a string to the outgoing TCPROS stream.
uros_err_t urosTcpRosSendStringSZ (UrosTcpRosStatus *tcpstp, const char *strp)
Writes a string to the outgoing TCPROS stream.
uros_err_t urosTcpRosSendError (UrosTcpRosStatus *tcpstp)
Sends the error string.
uros_err_t urosTcpRosListenerThread (void *data)
TCPROS Listener thread.
uros_err_t urosTcpRosServerThread (UrosConn *csp)
TCPROS Server worker thread.
uros_err_t urosTcpRosClientThread (uros_tcpcliargs_t *argsp)
TCPROS Client worker thread.
void urosTcpRosTopicSubscriberDone (UrosTcpRosStatus *tcpstp)
Notifies that a TCPROS topic subscriber thread has terminated.
void urosTcpRosTopicPublisherDone (UrosTcpRosStatus *tcpstp)
Notifies that a TCPROS topic publisher thread has terminated.
void urosTcpRosServiceDone (UrosTcpRosStatus *tcpstp)
Notifies that a TCPROS service thread has terminated.
Function Documentation
void urosTopicSubParamsDelete (uros_tcpcliargs_t * parp)
Deletes topic subscription parameters.
Deallocates the memory chunk of the string data, and the object itself.
See Also
urosFree()
Precondition
The parameters must have been allocated with urosAlloc().
The parameter data must have been allocated with urosAlloc().
Postcondition
parp points to an invalid address.
Parameters
[in] parp Pointer to an allocated uros_tcpcliargs_t object.
Definition at line 707 of file urosTcpRos.c.
References uros_tcpcliargs_t::topicName, urosFree(), and urosStringClean().
Referenced by urosRpcSlaveConnectToPublishers(), and urosTcpRosClientThread().
void urosTpcRosStatusObjectInit (UrosTcpRosStatus * tcpstp, UrosConn * csp)
Initializes a TCPROS status record.
Precondition
The record is not initialized.
Postcondition
The record is initialized.
Parameters
[in,out] tcpstp Pointer to an allocated UrosTcpRosStatus object.
[in] csp Pointer to an allocated connection.
Definition at line 726 of file urosTcpRos.c.
References UrosTcpRosStatus::csp, UrosTcpRosStatus::err, UrosTcpRosStatus::threadExitMtx, UROS_OK, urosAssert, and urosMutexObjectInit().
Referenced by urosTcpRosServerThread().
void urosTpcRosStatusClean (UrosTcpRosStatus * tcpstp, uros_bool_t deep)
Cleans a TCPROS status record.
Invalidates the private members. Optionally, deallocates their data.
Precondition
The record is initialized.
Postcondition
tcpstp points to an uninitialized UrosTcpRosStatus object.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
[in] deep Performs deallocation of private members.
Definition at line 754 of file urosTcpRos.c.
References UrosTcpRosStatus::callerId, UrosTcpRosStatus::csp, UrosTcpRosStatus::errstr, urosAssert, urosFree(), and urosStringClean().
Referenced by urosTpcRosStatusDelete().
void urosTpcRosStatusDelete (UrosTcpRosStatus * tcpstp, uros_bool_t deep)
Deallocates a TCPROS status record.
Invalidates the private members. Optionally, deallocates their data.
Precondition
The record is initialized.
Postcondition
tcpstp points to an invalid address.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
[in] deep Performs deallocation of private members.
Definition at line 780 of file urosTcpRos.c.
References urosFree(), and urosTpcRosStatusClean().
Referenced by urosTcpRosServerThread().
void urosTcpRosStatusIssueExit (UrosTcpRosStatus * tcpstp)
Raises the exit flag.
Sets the exitFlag to true, so that the user handler will exit the loop and therefore the TCPROS worker thread can exit.
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Definition at line 796 of file urosTcpRos.c.
References UrosTcpRosStatus::threadExit, UrosTcpRosStatus::threadExitMtx, UROS_TRUE, urosAssert, urosMutexLock(), and urosMutexUnlock().
uros_bool_t urosTcpRosStatusCheckExit (UrosTcpRosStatus * tcpstp)
Checks if the exit flag is raised.
Parameters
[in] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Returns
Exit flag status.
Definition at line 813 of file urosTcpRos.c.
References UrosTcpRosStatus::threadExit, UrosTcpRosStatus::threadExitMtx, urosAssert, urosMutexLock(), and urosMutexUnlock().
void urosTcpRosArrayObjectInit (UrosTcpRosArray * arrayp)
Initializes a TCPROS array descriptor.
The array is initialized as empty.
Precondition
The array is not initialized.
Postcondition
The array is empty.
Parameters
[in,out] arrayp Pointer to an allocated UrosTcpRosArray object.
Definition at line 835 of file urosTcpRos.c.
References UrosTcpRosArray::entriesp, UrosTcpRosArray::length, and urosAssert.
void urosTcpRosArrayClean (UrosTcpRosArray * arrayp)
Cleans a TCPROS array.
Invalidates the private members, and deallocates their data.
Precondition
The array is initialized.
Postcondition
arrayp points to an empty array descriptor.
Private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] arrayp Pointer to an initialized UrosTcpRosArray object.
Definition at line 855 of file urosTcpRos.c.
References UrosTcpRosArray::entriesp, UrosTcpRosArray::length, urosAssert, and urosFree().
Referenced by urosTcpRosArrayDelete().
void urosTcpRosArrayDelete (UrosTcpRosArray * arrayp, uros_bool_t deep)
Deallocates a TCPROS array descriptor.
Invalidates the private members. Optionally, deallocates their data.
Precondition
The array is initialized.
Postcondition
arrayp points to an invalid address.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] arrayp Pointer to an initialized UrosTcpRosArray object.
[in] deep Performs deallocation of private members.
Definition at line 878 of file urosTcpRos.c.
References urosFree(), and urosTcpRosArrayClean().
uros_err_t urosTcpRosSkip (UrosTcpRosStatus * tcpstp, size_t length)
Skips a number of bytes from the incoming TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] length Length of the data to skip, in bytes. Can be 0.
Returns
Error code.
Definition at line 898 of file urosTcpRos.c.
References UrosTcpRosStatus::csp, UrosTcpRosStatus::err, UROS_OK, urosAssert, urosConnIsValid(), urosConnRecv(), urosError, and urosErrorText().
uros_err_t urosTcpRosExpect (UrosTcpRosStatus * tcpstp, void * tokp, size_t toklen)
Expects a token from the incoming TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] tokp Pointer to the token string. Can be NULL only if toklen is 0.
[in] toklen Token length, in bytes. Can be 0.
Returns
Error code.
Return values
UROS_ERR_PARSE Token not found.
Definition at line 931 of file urosTcpRos.c.
References UrosTcpRosStatus::csp, UrosTcpRosStatus::err, UROS_ERR_PARSE, UROS_OK, urosAssert, urosConnIsValid(), urosConnRecv(), urosError, and urosErrorText().
uros_err_t urosTcpRosRecv (UrosTcpRosStatus * tcpstp, void * bufp, size_t buflen)
Reads some data from the incoming TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] bufp Pointer to the read buffer.
[in] buflen Length of the data to be read, in bytes. Can be 0.
Returns
Error code.
Definition at line 974 of file urosTcpRos.c.
References UrosTcpRosStatus::csp, UrosTcpRosStatus::err, UROS_OK, urosAssert, urosConnIsValid(), urosConnRecv(), urosError, and urosErrorText().
Referenced by urosTcpRosRecvString().
uros_err_t urosTcpRosRecvString (UrosTcpRosStatus * tcpstp, UrosString * strp)
Reads a string from the incoming TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] strp Pointer to an allcoated UrosString object to be read.
Returns
Error code.
Definition at line 1010 of file urosTcpRos.c.
References UrosString::datap, UrosTcpRosStatus::err, UrosString::length, UROS_ERR_NOMEM, UROS_OK, urosAlloc(), urosAssert, urosStringClean(), urosStringObjectInit(), urosTcpRosRecv(), and urosTcpRosRecvRaw.
uros_err_t urosTcpRosSend (UrosTcpRosStatus * tcpstp, const void * bufp, size_t buflen)
Writes some data to the outgoing TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] bufp Pointer to the buffered data to be written.
[in] buflen Length of the data to be written, in bytes. Can be 0.
Returns
Error code.
Definition at line 1052 of file urosTcpRos.c.
References UrosTcpRosStatus::csp, UrosTcpRosStatus::err, UROS_OK, urosAssert, urosConnSend(), urosError, and urosErrorText().
Referenced by urosTcpRosSendError(), urosTcpRosSendString(), urosTcpRosSendStringSZ(), and urosTcpRosServerThread().
uros_err_t urosTcpRosSendString (UrosTcpRosStatus * tcpstp, const UrosString * strp)
Writes a string to the outgoing TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] strp Pointer to a valid UrosString object to be written.
Returns
Error code.
Definition at line 1078 of file urosTcpRos.c.
References UrosString::datap, UrosTcpRosStatus::err, UrosString::length, UROS_OK, urosAssert, urosStringIsValid(), and urosTcpRosSend().
uros_err_t urosTcpRosSendStringSZ (UrosTcpRosStatus * tcpstp, const char * strp)
Writes a string to the outgoing TCPROS stream.
Parameters
[in,out] tcpstp Pointer to a TCPROS status with a working connection.
[in] strp Pointer to a null-terminated string. Can be NULL.
Returns
Error code.
Definition at line 1108 of file urosTcpRos.c.
References UrosTcpRosStatus::err, UROS_OK, urosAssert, and urosTcpRosSend().
uros_err_t urosTcpRosSendError (UrosTcpRosStatus * tcpstp)
Sends the error string.
The error string is tcpstp->errstr.
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Returns
Error code.
Definition at line 1136 of file urosTcpRos.c.
References UrosTcpRosStatus::err, UrosTcpRosStatus::errstr, UrosString::length, UrosMsgType::md5str, UrosMsgType::name, UrosTcpRosStatus::topicp, UrosTopic::typep, UROS_OK, urosAssert, and urosTcpRosSend().
Referenced by urosTcpRosServerThread().
uros_err_t urosTcpRosListenerThread (void * data)
TCPROS Listener thread.
This thread listens for incoming TCPROS connections by TCPROS clients.
An incoming connection is accepted by he Listener, and then handled by a new TCPROS Server thread, allocated from a dedicated thread pool. If no threads are free, it waits until one becomes available again.
See Also
urosThreadPoolStartWorker()
Precondition
There are no other TCPROS listener threads with the same connection port.
Parameters
[in] data Ignored.
Returns
Error code.
Definition at line 1195 of file urosTcpRos.c.
References UrosNode::config, UrosIp::dword, UrosAddr::ip, UrosAddr::port, UrosNode::status, UrosNodeConfig::tcprosAddr, UrosNodeStatus::tcpsvrThdPool, UROS_ANY_IP, UROS_OK, UROS_PROTO_TCP, UROS_TCPROS_LISTENER_BACKLOG, UROS_TCPROS_SENDTIMEOUT, UROS_TRUE, urosAssert, urosConnAccept(), urosConnBind(), urosConnClose(), urosConnCreate(), urosConnIsValid(), urosConnListen(), urosConnObjectInit(), urosConnSetSendTimeout(), urosFree(), urosNew, urosNode, and urosThreadPoolStartWorker().
uros_err_t urosTcpRosServerThread (UrosConn * csp)
TCPROS Server worker thread.
This thread processes an incoming TCPROS topic or service request.
     The TCPROS header is received, and the toipc/service handler is
     called for processing by the user-defined routine inside the
     related descriptor.
Precondition
The provided connection was accepted by the TCPROS Listener.
The connection was alloacted with urosAlloc().
Postcondition
The connection is closed and deallocated, and csp points to an invalid address.
Parameters
[in] csp Pointer to the incoming connection.
Returns
Error code.
Definition at line 1261 of file urosTcpRos.c.
References UrosString::datap, UrosTcpRosStatus::err, UrosTcpRosStatus::errstr, UrosTcpRosStatus::flags, UrosString::length, UrosTopic::procf, UrosNodeStatus::pubServiceListLock, UrosNodeStatus::pubTopicListLock, uros_topicflags_t::service, UrosNode::status, UrosTcpRosStatus::topicp, UROS_ERR_NOMEM, UROS_FALSE, UROS_OK, UROS_TRUE, urosAssert, urosConnClose(), urosErrorText(), urosMutexLock(), urosMutexUnlock(), urosNew, urosNode, urosStringClean(), urosStringCloneZ(), urosTcpRosSend(), urosTcpRosSendError(), urosTcpRosServiceDone(), urosTcpRosTopicPublisherDone(), urosTpcRosStatusDelete(), and urosTpcRosStatusObjectInit().
Referenced by urosNodeObjectInit().
uros_err_t urosTcpRosClientThread (uros_tcpcliargs_t * argsp)
TCPROS Client worker thread.
This thread routine subscribes to remote TCPROS topics or services.
The TCPROS header is sent, and the toipc/service handler is called for processing by the user-defined routine inside the related descriptor.
Precondition
The thread arguments addressed by argsp are allocated with urosAlloc().
Postcondition
The thread arguments are deallocated, and argsp points to an invalid address.
Parameters
[in] argsp Pointer to the TCPROS Client worker thread arguments.
Returns
Error code.
Definition at line 1360 of file urosTcpRos.c.
References uros_tcpcliargs_t::topicName, UROS_OK, urosAssert, urosStringNotEmpty(), and urosTopicSubParamsDelete().
Referenced by urosNodeObjectInit().
void urosTcpRosTopicSubscriberDone (UrosTcpRosStatus * tcpstp)
Notifies that a TCPROS topic subscriber thread has terminated.
Releases a topic reference. If the topic was deleted and this was its last reference, free its descriptor.
Precondition
Called by a TCPROS topic subscriber handler thread which has finished its job.
Postcondition
The topic has one reference less.
If this is the last topic reference, the topic descriptor is deleted.
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Definition at line 1397 of file urosTcpRos.c.
References uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosNode::status, UrosNodeStatus::subTopicListLock, UrosTcpRosStatus::topicp, urosAssert, urosMutexLock(), urosMutexUnlock(), urosNode, urosTopicDelete(), and urosTopicRefDec().
void urosTcpRosTopicPublisherDone (UrosTcpRosStatus * tcpstp)
Notifies that a TCPROS topic publisher thread has terminated.
Releases a topic reference. If the topic was deleted and this was its last reference, free its descriptor.
Precondition
Called by a TCPROS topic publisher handler thread which has finished its job.
Postcondition
The topic has one reference less.
If this is the last topic reference, the topic descriptor is deleted.
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Definition at line 1428 of file urosTcpRos.c.
References uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosNodeStatus::pubTopicListLock, UrosNode::status, UrosTcpRosStatus::topicp, urosAssert, urosMutexLock(), urosMutexUnlock(), urosNode, urosTopicDelete(), and urosTopicRefDec().
Referenced by urosTcpRosServerThread().
void urosTcpRosServiceDone (UrosTcpRosStatus * tcpstp)
Notifies that a TCPROS service thread has terminated.
Releases a service reference. If the ervice was deleted and this was its last reference, free its descriptor.
Precondition
Called by a TCPROS service thread which has finished its job.
Postcondition
The service has one reference less.
If this is the last service reference, the service descriptor is deleted.
Parameters
[in,out] tcpstp Pointer to an initialized UrosTcpRosStatus object.
Definition at line 1458 of file urosTcpRos.c.
References uros_topicflags_t::deleted, UrosTcpRosStatus::flags, UrosNodeStatus::pubServiceListLock, UrosNode::status, UrosTcpRosStatus::topicp, urosAssert, urosMutexLock(), urosMutexUnlock(), urosNode, urosTopicDelete(), and urosTopicRefDec().
Referenced by urosTcpRosServerThread().