μROSnode
Low-level functions
Node
Detailed Description
Functions
void uros_lld_nodeconfig_load (UrosNodeConfig *cfgp)
Loads node configuration.
void uros_lld_nodeconfig_save (const UrosNodeConfig *cfgp)
Saves the node configuration.
Function Documentation
void uros_lld_nodeconfig_load (UrosNodeConfig * cfgp)
Loads node configuration.
Any previously allocated data is freed, then the configuration is loaded from a static non-volatile memory chunk.
See Also
uros_lld_nodeconfig_load()
Precondition
The related UrosNode is initialized.
Parameters
[in,out] cfgp Pointer to the target configuration descriptor.
Definition at line 74 of file uros_lld_node.c.
References UrosNodeConfig::masterUri, UrosNodeConfig::nodeName, UrosNodeConfig::tcprosUri, urosAssert, urosStringClean(), and UrosNodeConfig::xmlrpcUri.
Referenced by urosNodeConfigLoad().
void uros_lld_nodeconfig_save (const UrosNodeConfig * cfgp)
Saves the node configuration.
The node configuration is saved to a static non-volatile memory chunk.
See Also
uros_lld_nodeconfig_save()
Precondition
The related UrosNode is initialized.
Parameters
[in] cfgp Pointer to the configuration descriptor to be saved.
Definition at line 98 of file uros_lld_node.c.
Referenced by urosNodeConfigSave().