μROSnode
Functions
Base
Detailed Description
System
~~~ SYSTEM ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void urosInit (void)
Middleware initialization.
const char * urosErrorText (uros_err_t err)
Text of an error code.
void * urosAlloc (size_t size)
Allocates a memory block.
void urosFree (void *chunkp)
Deallocates a memory block.
Memory pool
void urosMemPoolObjectInit (UrosMemPool *poolp, size_t blocksize, uros_alloc_f allocator)
Initializes a memory pool ojbect.
void * urosMemPoolAlloc (UrosMemPool *poolp)
Requests a free block from a memory pool.
void urosMemPoolFree (UrosMemPool *poolp, void *objp)
Releases a memory pool block.
uros_cnt_t urosMemPoolNumFree (UrosMemPool *poolp)
Gets the number of free memory pool blocks.
void urosMemPoolLoadArray (UrosMemPool *poolp, void *arrayp, uros_cnt_t n)
Adds free memory pool blocks from an array.
size_t urosMemPoolBlockSize (UrosMemPool *poolp)
Gets the memory pool block size.
String
UrosString * urosStringNew (const char *szp)
Allocates a new string object.
void urosStringObjectInit (UrosString *strp)
Initializes a string object.
UrosString urosStringAssignN (const char *datap, size_t datalen)
String pointing to a memory chunk.
UrosString urosStringAssignZ (const char *szp)
The string object points to a memory chunk.
UrosString urosStringClone (const UrosString *strp)
Clones a string object.
UrosString urosStringCloneN (const char *datap, size_t datalen)
Clones a string object from a memory chunk.
UrosString urosStringCloneZ (const char *szp)
Clones a string object from a null-terminated string.
void urosStringClean (UrosString *strp)
Cleans a string object.
void urosStringDelete (UrosString *strp)
Deallocates a string object.
uros_bool_t urosStringIsValid (const UrosString *strp)
Checks if pointing to a valid string object.
uros_bool_t urosStringNotEmpty (const UrosString *strp)
Checks if a string is not empty.
int urosStringCmp (const UrosString *str1, const UrosString *str2)
Compares two string objects.
Message type
void urosMsgTypeObjectInit (UrosMsgType *typep)
Initializes a message type descriptor.
void urosMsgTypeClean (UrosMsgType *typep)
Cleans a message type descriptor.
void urosMsgTypeDelete (UrosMsgType *typep)
Deallocates a message type descriptor.
uros_bool_t urosMsgTypeNodeHasName (const UrosListNode *nodep, const UrosString *namep)
Checks if the list node links to a message type with the requested name.
void urosRegisterStaticMsgType (const UrosString *namep, const UrosString *descp, const UrosString *md5sump)
Registers a message type to the static global list.
void urosRegisterStaticMsgTypeSZ (const char *namep, const char *descp, const char *md5sump)
Registers a message type to the static global list.
const UrosMsgType * urosFindStaticMsgType (const UrosString *namep)
Gets the message type descriptor with the requested name.
const UrosMsgType * urosFindStaticMsgTypeSZ (const char *namep)
Gets the message type descriptor with the requested name.
Service type
void urosRegisterStaticSrvType (const UrosString *namep, const UrosString *descp, const UrosString *md5sump)
Registers a service type to the static global list.
void urosRegisterStaticSrvTypeSZ (const char *namep, const char *descp, const char *md5sump)
Registers a service type to the static global list.
const UrosMsgType * urosFindStaticSrvType (const UrosString *namep)
Gets the service type descriptor with the requested name.
const UrosMsgType * urosFindStaticSrvTypeSZ (const char *namep)
Gets the service type descriptor with the requested name.
Topic
void urosTopicObjectInit (UrosTopic *tp)
Initializes a topic descriptor.
void urosTopicClean (UrosTopic *tp)
Cleans a topic descriptor.
void urosTopicDelete (UrosTopic *tp)
Deallocates a topic descriptor.
uros_cnt_t urosTopicRefInc (UrosTopic *tp)
Incrememts the topic reference count.
uros_cnt_t urosTopicRefDec (UrosTopic *tp)
Decrememts the topic reference count.
List
void urosListNodeObjectInit (UrosListNode *np)
Initializes a list node.
void urosListNodeDelete (UrosListNode *np, uros_delete_f datadelf)
Deallocates a list node.
void urosListObjectInit (UrosList *lstp)
Initializes a list object.
void urosListClean (UrosList *lstp, uros_delete_f datadelf)
Cleans a list.
void urosListDelete (UrosList *lstp, uros_delete_f datadelf)
Deallocates a list object.
uros_cnt_t urosListLength (const UrosList *lstp)
List length.
uros_bool_t urosListIsValid (const UrosList *lstp)
Checks if pointing to a valid list object.
uros_bool_t urosListNotEmpty (const UrosList *lstp)
Checks if a list is not empty.
uros_bool_t urosListContains (const UrosList *lstp, const UrosListNode *np)
Checks if the list contains the references node.
UrosListNode * urosListFind (const UrosList *lstp, uros_cmp_f filter, const void *featurep)
First matching node occurrence of the list.
void urosListAdd (UrosList *lstp, UrosListNode *np)
Adds a node to the list.
UrosListNode * urosListRemove (UrosList *lstp, const UrosListNode *np)
Removes a node from the list.
uros_bool_t urosTopicListNodeHasTopic (const UrosListNode *np, const UrosTopic *topicp)
Checks if the list node is linked to the referenced topic.
uros_bool_t urosTopicListNodeHasName (const UrosListNode *np, const UrosString *namep)
Checks if the list node links to a topic with the requested name.
UrosListNode * urosTopicListFindByTopic (const UrosList *lstp, const UrosTopic *topicp)
Gets the list node referencing a specific topic.
UrosListNode * urosTopicListFindByName (const UrosList *lstp, const UrosString *namep)
Gets the list node referencing a topic with the requested name.
Function Documentation
void urosInit (void)
Middleware initialization.
This procedure initializes the middleware at system start-up.
Precondition
The operating system is working.
The middleware was not initialized.
Postcondition
The urosNode singleton is initialized and configured.
Static types are registered.
The thread pools are filled with ready threads.
Definition at line 98 of file urosBase.c.
References UrosNode::config, UrosNodeStatus::slaveThdPool, UrosNode::status, UrosNodeStatus::tcpcliThdPool, UrosNodeStatus::tcpsvrThdPool, uros_lld_init(), urosListObjectInit(), urosNode, urosNodeConfigLoad(), urosNodeObjectInit(), urosThreadPoolCreateAll(), and urosUserCreateListeners().
const char* urosErrorText (uros_err_t err)
Text of an error code.
Parameters
[in] err Error code.
Returns
Text of the error code.
Definition at line 129 of file urosBase.c.
References UROS_ERR_BADCONN, UROS_ERR_BADPARAM, UROS_ERR_EOF, UROS_ERR_NOCONN, UROS_ERR_NOMEM, UROS_ERR_NOTIMPL, UROS_ERR_PARSE, UROS_ERR_TIMEOUT, and UROS_OK.
Referenced by urosNodePublishTopicByDesc(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeTopic(), urosRpcParserDouble(), urosRpcParserExpectWs(), urosRpcParserHttpRequest(), urosRpcParserHttpResponse(), urosRpcParserInt32(), urosRpcParserParamValueArray(), urosRpcParserParamValueString(), urosRpcParserRefill(), urosRpcParserSkipAfter(), urosRpcParserXmlAttrWVal(), urosRpcParserXmlHeader(), urosRpcParserXmlTagBeginNoName(), urosRpcSlaveConnectToPublishers(), urosRpcSlaveListenerThread(), urosRpcSlaveServerThread(), urosRpcStreamerFlush(), urosRpcStreamerWrite(), urosTcpRosExpect(), urosTcpRosRecv(), urosTcpRosSend(), urosTcpRosServerThread(), urosTcpRosSkip(), urosThreadCreateFromHeap(), urosThreadCreateFromMemPool(), urosThreadCreateStatic(), urosThreadJoin(), and urosUriToAddr().
void* urosAlloc (size_t size)
Allocates a memory block.
This function tries to allocate a memory block of the required size inside the default heap of the operating system.
Precondition
There is enough contiguous free space inside the default heap.
Parameters
[in] size Size of the memory block to be allocated, in bytes.
Returns
The address of the allocated memory chunk.
Return values
NULL There is not enough contiguous free memory to allocate a memory block of the requested size.
Definition at line 163 of file urosBase.c.
References uros_lld_alloc(), and urosError.
Referenced by urosRpcParserParamValueString(), urosStringClone(), urosStringCloneN(), urosStringCloneZ(), urosTcpRosRecvString(), and urosThreadPoolObjectInit().
void urosFree (void * chunkp)
Deallocates a memory block.
Precondition
The block addressed by chunkp must have been allocated with urosAlloc().
Postcondition
chunkp points to an invalid address.
Parameters
[in] chunkp Pointer to the memory block to be deallocated. A NULL value will simply be ignored.
Definition at line 186 of file urosBase.c.
References uros_lld_free().
Referenced by urosListDelete(), urosListNodeDelete(), urosMsgTypeDelete(), urosNodeFindNewPublishers(), urosRpcCallParamUpdate(), urosRpcCallPublisherUpdate(), urosRpcCallRequestTopic(), urosRpcCallSetParam(), urosRpcCallSubscribeParam(), urosRpcParamClean(), urosRpcParamDelete(), urosRpcParamListDelete(), urosRpcParamNodeDelete(), urosRpcParserClean(), urosRpcParserParam(), urosRpcSlaveListenerThread(), urosRpcSlaveServerThread(), urosRpcStreamerClean(), urosStringClean(), urosStringDelete(), urosTcpRosArrayClean(), urosTcpRosArrayDelete(), urosTcpRosListenerThread(), urosThreadPoolClean(), urosTopicDelete(), urosTopicSubParamsDelete(), urosTpcRosStatusClean(), and urosTpcRosStatusDelete().
void urosMemPoolObjectInit (UrosMemPool * poolp, size_t blocksize, uros_alloc_f allocator)
Initializes a memory pool ojbect.
See Also
uros_alloc_f
Precondition
The object addressed by poolp is allocated but not initialized.
Parameters
[in,out] poolp Pointer to an allocated UrosMemPool object.
[in] blocksize Size of a memory pool block.
[in] allocator Pointer to an allocator function. If not NULL, when no blocks are free but a further one is requested, the allocator will make the pool grow by one element.
Definition at line 213 of file urosBase.c.
References UrosMemPool::allocator, UrosMemPool::blockSize, UrosMemPool::free, UrosMemPool::headp, UrosMemPool::lock, urosAssert, and urosMutexObjectInit().
void* urosMemPoolAlloc (UrosMemPool * poolp)
Requests a free block from a memory pool.
This function gets a free memory block from the memory pool, and returns its pointer. If there are no free blocks but an allocator was provided, then it tries to allocate a further block and return its pointer.
See Also
uros_alloc_f
Parameters
[in,out] poolp Pointer to an initialized UrosMemPool object.
Returns
Pointer to the allocated memory block, excluding the reserved pointer.
Return values
NULL There are no free blocks inside the memory pool. Additionally, if the allocator was defined, it cannot allocate a further block and make the pool grow by one element.
Definition at line 248 of file urosBase.c.
References UrosMemPool::allocator, UrosMemPool::blockSize, UrosMemPool::free, UrosMemPool::headp, UrosMemPool::lock, urosAssert, urosMutexLock(), and urosMutexUnlock().
void urosMemPoolFree (UrosMemPool * poolp, void * objp)
Releases a memory pool block.
The caller releases a memory block, and puts it back into the memory pool.
Precondition
The block addressed by objp was allocated with a memory pool with a compatible block size.
Postcondition
objp points to an invalid address.
Parameters
[in,out] poolp Pointer to an initialized UrosMemPool object.
[in] objp Pointer to a memory block previously allocated from a compatible memory pool (reserved pointer excluded).
Definition at line 295 of file urosBase.c.
References UrosMemPool::free, UrosMemPool::headp, UrosMemPool::lock, urosAssert, urosMutexLock(), and urosMutexUnlock().
Referenced by urosMemPoolLoadArray().
uros_cnt_t urosMemPoolNumFree (UrosMemPool * poolp)
Gets the number of free memory pool blocks.
Parameters
[in] poolp Pointer to an initialized UrosMemPool object.
Returns
Number of free memory pool blocks.
Definition at line 323 of file urosBase.c.
References UrosMemPool::free, UrosMemPool::lock, urosAssert, urosMutexLock(), and urosMutexUnlock().
Referenced by urosThreadPoolObjectInit().
void urosMemPoolLoadArray (UrosMemPool * poolp, void * arrayp, uros_cnt_t n)
Adds free memory pool blocks from an array.
An array of memory blocks is added to the free list of the provided memory pool.
Precondition
The number of elements n is positive.
A reserved pointer is stored at the very beginning of each array element. The remainder (payload) of each element is size-compatible with the memory pool block size.
Parameters
[in,out] poolp Pointer to an initialize UrosMemPool object.
[in] arrayp Pointer to the source array.
[in] n Number of array elements.
Definition at line 356 of file urosBase.c.
References UrosMemPool::blockSize, urosAssert, and urosMemPoolFree().
size_t urosMemPoolBlockSize (UrosMemPool * poolp)
Gets the memory pool block size.
Parameters
[in] poolp Pointer to an initialized UrosMemPool object.
Returns
Size of a memory pool block, including the reserved pointer.
Definition at line 384 of file urosBase.c.
References UrosMemPool::blockSize, and urosAssert.
Referenced by urosThreadPoolObjectInit().
UrosString* urosStringNew (const char * szp)
Allocates a new string object.
A new UrosString object is allocated on the heap, and its value is copied from a template null-terminated string.
Parameters
[in] szp Pointer to a template null-terminated string. Can be NULL.
Returns
Pointer to the allocated UrosString object.
Return values
NULL Not enough free memory.
Definition at line 414 of file urosBase.c.
References urosNew, and urosStringCloneZ().
Referenced by urosRpcParserMethodResponse().
void urosStringObjectInit (UrosString * strp)
Initializes a string object.
The object is set as an empty string.
Precondition
The object addressed by strp is allocated but not initialized.
Postcondition
The object has 0 (zero) length and NULL data.
Parameters
[in,out] strp Pointer to an allocated UrosString object.
Definition at line 435 of file urosBase.c.
References UrosString::datap, UrosString::length, and urosAssert.
Referenced by urosMsgTypeObjectInit(), urosTcpRosRecvString(), and urosTopicObjectInit().
UrosString urosStringAssignN (const char * datap, size_t datalen)
String pointing to a memory chunk.
Addresses the generated string descriptor to a memory chunk.
Parameters
[in] datap Pointer to a valid memory address.
[in] datalen Length of the string to be copied.
Returns
The string object (descriptor).
Definition at line 454 of file urosBase.c.
References UrosString::datap, UrosString::length, and urosAssert.
UrosString urosStringAssignZ (const char * szp)
The string object points to a memory chunk.
Addresses the generated string descriptor to a null-terminated string.
Parameters
[in] szp Pointer to a null-terminated string. Can be NULL.
Returns
The string object (descriptor).
Definition at line 475 of file urosBase.c.
References UrosString::datap, and UrosString::length.
Referenced by urosFindStaticMsgTypeSZ(), urosFindStaticSrvTypeSZ(), urosNodePublishServiceSZ(), urosNodePublishTopicSZ(), urosNodeSubscribeParamSZ(), urosNodeSubscribeTopicSZ(), urosRegisterStaticMsgTypeSZ(), and urosRegisterStaticSrvTypeSZ().
UrosString urosStringClone (const UrosString * strp)
Clones a string object.
Duplicates the contents from an existing UrosString object and returns the cloned object.
Parameters
[in] strp Pointer to an initialized UrosString object. Can be NULL.
Returns
The cloned string object (descriptor).
Return values
NULL Not enough free memory.
Definition at line 501 of file urosBase.c.
References UrosString::datap, UrosString::length, urosAlloc(), and urosAssert.
Referenced by urosNodePublishService(), urosNodePublishTopic(), urosNodeSubscribeParam(), urosNodeSubscribeTopic(), and urosRpcSlaveConnectToPublishers().
UrosString urosStringCloneN (const char * datap, size_t datalen)
Clones a string object from a memory chunk.
Duplicates the contents from an addressed memory chunk.
Parameters
[in] datap Pointer to a valid memory address.
[in] datalen Length of the string to be copied.
Returns
The cloned string object (descriptor).
Return values
NULL Not enough free memory.
Definition at line 534 of file urosBase.c.
References UrosString::datap, UrosString::length, urosAlloc(), and urosAssert.
UrosString urosStringCloneZ (const char * szp)
Clones a string object from a null-terminated string.
Duplicates the contents from a null-terminated string.
Parameters
[in] szp Pointer to a null-terminated string. Can be NULL.
Returns
The cloned string object (descriptor).
Return values
NULL Not enough free memory.
Definition at line 563 of file urosBase.c.
References UrosString::datap, UrosString::length, urosAlloc(), and urosAssert.
Referenced by urosNodeConfigLoadDefaults(), urosStringNew(), and urosTcpRosServerThread().
void urosStringClean (UrosString * strp)
Cleans a string object.
Deallocates the memory chunk of the string data, and invalidates the string.
Precondition
The string data must have been allocated with urosAlloc().
Postcondition
strp points to an empty UrosString string object.
Parameters
[in,out] strp Pointer to an initialized UrosString object.
Definition at line 594 of file urosBase.c.
References UrosString::datap, UrosString::length, urosAssert, and urosFree().
Referenced by uros_lld_nodeconfig_load(), urosMsgTypeClean(), urosNodeConfigLoadDefaults(), urosRpcParamClean(), urosTcpRosRecvString(), urosTcpRosServerThread(), urosTopicClean(), urosTopicSubParamsDelete(), and urosTpcRosStatusClean().
void urosStringDelete (UrosString * strp)
Deallocates a string object.
Deallocates the memory chunk of the string data, and the object itself.
Precondition
The string object must have been allocated with urosAlloc().
The string data must have been allocated with urosAlloc().
Postcondition
strp points to an invalid address.
Parameters
[in] strp Pointer to an initialized UrosString object.
Definition at line 617 of file urosBase.c.
References UrosString::datap, and urosFree().
Referenced by urosRpcResponseClean().
uros_bool_t urosStringIsValid (const UrosString * strp)
Checks if pointing to a valid string object.
Checks is the addressed object points to a valid memory address, and its descriptor is consistent.
Note
A string object addressed by strp is consistent when:
(strp->length == 0) == (strp->datap == NULL)
Parameters
[in] strp Pointer to a presumed consistent UrosString object.
Returns
true when strp is not NULL and the string descriptor is consistent.
Definition at line 639 of file urosBase.c.
References UrosString::datap, and UrosString::length.
Referenced by urosRpcCallShutdown(), urosStringCmp(), and urosTcpRosSendString().
uros_bool_t urosStringNotEmpty (const UrosString * strp)
Checks if a string is not empty.
Checks if the addressed string is a consistent, non-empty string.
See Also
urosStringIsValid
Parameters
[in] strp Pointer to a presumed UrosString object.
Returns
true when strp is not NULL and the string is not empty.
Definition at line 655 of file urosBase.c.
References UrosString::datap, and UrosString::length.
Referenced by urosFindStaticMsgType(), urosFindStaticSrvType(), urosNodeFindNewPublishers(), urosNodePublishService(), urosNodePublishServiceByDesc(), urosNodePublishTopic(), urosNodePublishTopicByDesc(), urosNodeSubscribeParam(), urosNodeSubscribeParamByDesc(), urosNodeSubscribeTopic(), urosNodeSubscribeTopicByDesc(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeParam(), urosNodeUnsubscribeTopic(), urosRegisterStaticMsgType(), urosRegisterStaticSrvType(), urosRpcCallDeleteParam(), urosRpcCallGetParam(), urosRpcCallLookupService(), urosRpcCallParamUpdate(), urosRpcCallPublisherUpdate(), urosRpcCallRequestTopic(), urosRpcCallSearchParam(), urosRpcCallSetParam(), urosRpcCallSubscribeParam(), urosRpcSlaveConnectToPublishers(), urosTcpRosClientThread(), urosTopicListNodeHasName(), urosUriToAddr(), and urosUserParamUpdate().
int urosStringCmp (const UrosString * str1, const UrosString * str2)
Compares two string objects.
This function starts comparing the first character of each string. If they are equal to each other, it continues with the following pairs until the characters differ or until there are no more characters in one string.
Note
This is functionally equivalent to strcmp(), but involves UrosString objects instead of null-terminated strings.
Two empty strings are equal.
If a string is empty but the other is not, then the first character is the returned value (with the appropriate sign).
Parameters
[in] str1 Pointer to the first UrosString operand, valid string.
[in] str2 Pointer to the second UrosString operand, valid string.
Returns
Integral value indicating the relationship between the strings.
Return values
0 Both strings are equal.
positive The first character that does not match has a greater value in str1 than in str2.
negative The first character that does not match has a lesser value in str1 than in str2.
Definition at line 686 of file urosBase.c.
References UrosString::datap, UrosString::length, urosAssert, and urosStringIsValid().
Referenced by urosMsgTypeNodeHasName(), urosNodeFindNewPublishers(), and urosTopicListNodeHasName().
void urosMsgTypeObjectInit (UrosMsgType * typep)
Initializes a message type descriptor.
The object is set as an empty message type descriptor.
Precondition
The object addressed by typep is allocated but not initialized.
Postcondition
The fields of the object are all empty strings.
Parameters
[in,out] typep Pointer to an allocated UrosMsgType object.
Definition at line 729 of file urosBase.c.
References UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, and urosStringObjectInit().
void urosMsgTypeClean (UrosMsgType * typep)
Cleans a message type descriptor.
Deallocates all the memory chunks allocated by the fields of the object.
Precondition
The string data must have been allocated with urosAlloc().
Postcondition
The fields of the object are deallocated, strings are empty.
typep points to an empty UrosMsgType descriptor.
Parameters
[in,out] typep Pointer to an initialized UrosMsgType object.
Definition at line 750 of file urosBase.c.
References UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, and urosStringClean().
Referenced by urosMsgTypeDelete().
void urosMsgTypeDelete (UrosMsgType * typep)
Deallocates a message type descriptor.
Deallocates the memory chunk of the object and all its fields.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
typep points to an invalid address.
Parameters
[in] typep Pointer to an initialized UrosMsgType object.
Definition at line 770 of file urosBase.c.
References urosFree(), and urosMsgTypeClean().
uros_bool_t urosMsgTypeNodeHasName (const UrosListNode * nodep, const UrosString * namep)
Checks if the list node links to a message type with the requested name.
See Also
urosStringCmp()
Parameters
[in] nodep Pointer to an initialized UrosListNode which points to an initialized UrosMsgType descriptor.
[in] namep Pointer to a non-empty UrosString.
Returns
true iif the message type of the node has the requested name.
Definition at line 792 of file urosBase.c.
References UrosListNode::datap, and urosStringCmp().
Referenced by urosFindStaticMsgType(), urosFindStaticMsgTypeSZ(), urosFindStaticSrvType(), and urosFindStaticSrvTypeSZ().
void urosRegisterStaticMsgType (const UrosString * namep, const UrosString * descp, const UrosString * md5sump)
Registers a message type to the static global list.
Note
Best practice to statically register all the message types at boot time.
See Also
urosMsgTypeList
Precondition
No message type was registered with the same name before.
No publishers nor subscribers have been queried before, so that the message types list is still consistent.
Parameters
[in] namep Type name, not empty. Its contents must be valid for the whole life of the program.
[in] descp Long description, can be NULL. Its contents must be valid for the whole life of the program.
[in] md5sump MD5 sum of the type description, not empty. Its contents must be valid for the whole life of the program.
Definition at line 819 of file urosBase.c.
References UrosListNode::datap, UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, urosListAdd(), urosListNodeObjectInit(), urosNew, and urosStringNotEmpty().
void urosRegisterStaticMsgTypeSZ (const char * namep, const char * descp, const char * md5sump)
Registers a message type to the static global list.
Note
Best practice to statically register all the message types at boot time.
See Also
urosMsgTypeList
Precondition
No message type was registered with the same name before.
No publishers nor subscribers have been queried before, so that the message types list is still consistent.
Parameters
[in] namep Type name, null-terminated string, not empty. Its contents must be valid for the whole life of the program.
[in] descp Long description, null-terminated string, can be NULL. Its contents must be valid for the whole life of the program.
[in] md5sump MD5 sum of the type description, null-terminated string, not empty. Its contents must be valid for the whole life of the program.
Definition at line 862 of file urosBase.c.
References UrosListNode::datap, UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, urosListAdd(), urosListNodeObjectInit(), urosNew, and urosStringAssignZ().
const UrosMsgType* urosFindStaticMsgType (const UrosString * namep)
Gets the message type descriptor with the requested name.
Scans the message type register to get the address of the one with the requested name, if existing.
Note
This function is not thread safe, because all the message types are supposed to be registered only at boot time.
See Also
urosMsgTypeList
urosListFind
urosMsgTypeHasName
Parameters
[in] namep Requested type name, not empty.
Returns
Pointer to the registered message type descriptor with the requested name.
Return values
NULL No such type name found.
Definition at line 905 of file urosBase.c.
References UrosListNode::datap, urosAssert, urosListFind(), urosMsgTypeNodeHasName(), and urosStringNotEmpty().
Referenced by urosNodePublishTopic(), and urosNodeSubscribeTopic().
const UrosMsgType* urosFindStaticMsgTypeSZ (const char * namep)
Gets the message type descriptor with the requested name.
Scans the message type register to get the address of the one with the requested name, if existing.
Note
This function is not thread safe, because all the message types are supposed to be registered only at boot time.
See Also
urosMsgTypeList
urosListFind
urosMsgTypeHasName
Parameters
[in] namep Requested type name, null-terminated string, NULL forbidden.
Returns
Pointer to the registered message type descriptor with the requested name.
Return values
NULL No such type name found.
Definition at line 934 of file urosBase.c.
References UrosListNode::datap, urosAssert, urosListFind(), urosMsgTypeNodeHasName(), and urosStringAssignZ().
void urosRegisterStaticSrvType (const UrosString * namep, const UrosString * descp, const UrosString * md5sump)
Registers a service type to the static global list.
Note
Best practice to statically register all the service types at boot time.
See Also
urosMsgTypeList
Precondition
No service type was registered with the same name before.
No publishers nor subscribers have been queried before, so that the service types list is still consistent.
Parameters
[in] namep Type name, not empty. Its contents must be valid for the whole life of the program.
[in] descp Long description, can be NULL. Its contents must be valid for the whole life of the program.
[in] md5sump MD5 sum of the type description, not empty. Its contents must be valid for the whole life of the program.
Definition at line 975 of file urosBase.c.
References UrosListNode::datap, UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, urosListAdd(), urosListNodeObjectInit(), urosNew, and urosStringNotEmpty().
void urosRegisterStaticSrvTypeSZ (const char * namep, const char * descp, const char * md5sump)
Registers a service type to the static global list.
Note
Best practice to statically register all the service types at boot time.
See Also
urosMsgTypeList
Precondition
No service type was registered with the same name before.
No publishers nor subscribers have been queried before, so that the service types list is still consistent.
Parameters
[in] namep Type name, null-terminated string, not empty. Its contents must be valid for the whole life of the program.
[in] descp Long description, null-terminated string, can be NULL. Its contents must be valid for the whole life of the program.
[in] md5sump MD5 sum of the type description, null-terminated string, not empty. Its contents must be valid for the whole life of the program.
Definition at line 1018 of file urosBase.c.
References UrosListNode::datap, UrosMsgType::desc, UrosMsgType::md5str, UrosMsgType::name, urosAssert, urosListAdd(), urosListNodeObjectInit(), urosNew, and urosStringAssignZ().
const UrosMsgType* urosFindStaticSrvType (const UrosString * namep)
Gets the service type descriptor with the requested name.
Scans the service type register to get the address of the one with the requested name, if existing.
Note
This function is not thread safe, because all the service types are supposed to be registered only at boot time.
See Also
urosSrvTypeList
urosListFind
urosMsgTypeHasName
Parameters
[in] namep Requested type name, not empty.
Returns
Pointer to the registered service type descriptor with the requested name.
Return values
NULL No such type name found.
Definition at line 1061 of file urosBase.c.
References UrosListNode::datap, urosAssert, urosListFind(), urosMsgTypeNodeHasName(), and urosStringNotEmpty().
Referenced by urosNodePublishService().
const UrosMsgType* urosFindStaticSrvTypeSZ (const char * namep)
Gets the service type descriptor with the requested name.
Scans the service type register to get the address of the one with the requested name, if existing.
Note
This function is not thread safe, because all the service types are supposed to be registered only at boot time.
See Also
urosMsgTypeList
urosListFind
urosMsgTypeHasName
Parameters
[in] namep Requested type name, null-terminated string, NULL forbidden.
Returns
Pointer to the registered service type descriptor with the requested name.
Return values
NULL No such type name found.
Definition at line 1090 of file urosBase.c.
References UrosListNode::datap, urosAssert, urosListFind(), urosMsgTypeNodeHasName(), and urosStringAssignZ().
void urosTopicObjectInit (UrosTopic * tp)
Initializes a topic descriptor.
The object is set as an empty topic descriptor.
Precondition
The object addressed by tp is allocated but not initialized.
Postcondition
The fields of the object are all empty strings.
All the numeric values are nullified.
Parameters
[in,out] tp Pointer to an allocated UrosTopic object.
Definition at line 1122 of file urosBase.c.
References UrosTopic::flags, UrosTopic::name, UrosTopic::procf, UrosTopic::refcnt, UrosTopic::typep, urosAssert, and urosStringObjectInit().
Referenced by urosNodePublishService(), urosNodePublishTopic(), urosNodeSubscribeParam(), and urosNodeSubscribeTopic().
void urosTopicClean (UrosTopic * tp)
Cleans a topic descriptor.
Deallocates all the memory chunks allocated by the fields of the object.
Precondition
The string data must have been allocated with urosAlloc().
Postcondition
The fields of the object are deallocated, strings are empty.
tp points to a nullified UrosTopic descriptor.
Parameters
[in,out] tp Pointer to an initialized UrosTopic object.
Definition at line 1145 of file urosBase.c.
References UrosTopic::name, UrosTopic::procf, UrosTopic::refcnt, UrosTopic::typep, urosAssert, and urosStringClean().
Referenced by urosTopicDelete().
void urosTopicDelete (UrosTopic * tp)
Deallocates a topic descriptor.
Deallocates the memory chunk of the object and all its fields.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
tp points to an invalid address.
Parameters
[in] tp Pointer to an initialized UrosTopic object.
Definition at line 1167 of file urosBase.c.
References urosFree(), and urosTopicClean().
Referenced by urosNodePublishService(), urosNodePublishTopic(), urosNodeSubscribeParam(), urosNodeSubscribeTopic(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeTopic(), urosTcpRosServiceDone(), urosTcpRosTopicPublisherDone(), and urosTcpRosTopicSubscriberDone().
uros_cnt_t urosTopicRefInc (UrosTopic * tp)
Incrememts the topic reference count.
Precondition
The topic is within a locked context.
Postcondition
The topic reference count is incremented by one.
Parameters
[in,out] tp Pointer to the referenced topic descriptor.
Returns
Updated reference count.
Definition at line 1186 of file urosBase.c.
References UrosTopic::refcnt, and urosAssert.
uros_cnt_t urosTopicRefDec (UrosTopic * tp)
Decrememts the topic reference count.
Precondition
The topic is within a locked context.
There is at least one referenced counted.
Postcondition
The topic reference count is decremented by one.
Parameters
[in,out] tp Pointer to the unreferenced topic descriptor.
Returns
Updated reference count.
Definition at line 1205 of file urosBase.c.
References UrosTopic::refcnt, and urosAssert.
Referenced by urosTcpRosServiceDone(), urosTcpRosTopicPublisherDone(), and urosTcpRosTopicSubscriberDone().
void urosListNodeObjectInit (UrosListNode * np)
Initializes a list node.
Precondition
The object addressed by np is allocated but not initialized.
Postcondition
The node has no referenced data.
The node has no successor.
Parameters
[in,out] np Pointer to an allocated UrosListNode object.
Definition at line 1230 of file urosBase.c.
References UrosListNode::datap, UrosListNode::nextp, and urosAssert.
Referenced by urosRegisterStaticMsgType(), urosRegisterStaticMsgTypeSZ(), urosRegisterStaticSrvType(), and urosRegisterStaticSrvTypeSZ().
void urosListNodeDelete (UrosListNode * np, uros_delete_f datadelf)
Deallocates a list node.
Deallocates the list node object. If a data deletion function is provided, the node data is deleted through a call to it.
See Also
urosFree()
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
np points to an invalid address.
If the data deletion function is provided, the node data is deleted.
Parameters
[in] np Pointer to an initialized UrosListNode object. Can be NULL.
[in] datadelf Data deletion function. Can be NULL if only the node object np has to be deleted.
Definition at line 1256 of file urosBase.c.
References UrosListNode::datap, and urosFree().
Referenced by urosListClean(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), and urosNodeUnsubscribeTopic().
void urosListObjectInit (UrosList * lstp)
Initializes a list object.
Precondition
The object addressed by lstp is allocated but not initialized.
Postcondition
The list is empty.
Parameters
[in,out] lstp Pointer to an allocated UrosList object.
Definition at line 1275 of file urosBase.c.
References UrosList::headp, UrosList::length, and urosAssert.
Referenced by urosInit(), urosNodeObjectInit(), and urosNodeSubscribeTopicByDesc().
void urosListClean (UrosList * lstp, uros_delete_f datadelf)
Cleans a list.
Removes all the nodes from a list. If a data deletion function is provided, the node data is deleted through a call to it.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
lstp points to an empty list.
If the data deletion function is provided, each node data is deleted.
Parameters
[in] lstp Pointer to an initialized UrosList object.
[in] datadelf Data deletion function. Can be NULL if only the node objects have to be deleted, but not their referenced data.
Definition at line 1300 of file urosBase.c.
References UrosList::headp, UrosList::length, UrosListNode::nextp, urosAssert, urosListIsValid(), and urosListNodeDelete().
Referenced by urosListDelete().
void urosListDelete (UrosList * lstp, uros_delete_f datadelf)
Deallocates a list object.
Removes all the nodes from a list. If a data deletion function is provided, the node data is deleted through a call to it.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
lstp points to an invalid address.
If the data deletion function is provided, each node data is deleted.
Parameters
[in] lstp Pointer to an initialized UrosList object. Can be NULL.
[in] datadelf Data deletion function. Can be NULL if only the list object lstp and its UrosListNode objects have to be deleted, but not their referenced data.
Definition at line 1332 of file urosBase.c.
References urosFree(), and urosListClean().
uros_cnt_t urosListLength (const UrosList * lstp)
List length.
Parameters
[in] lstp Pointer to an initialized UrosList object.
Returns
List length.
Definition at line 1348 of file urosBase.c.
References UrosList::length, and urosAssert.
uros_bool_t urosListIsValid (const UrosList * lstp)
Checks if pointing to a valid list object.
Checks is the addressed object points to a valid memory address, and its descriptor is consistent.
Note
A list object addressed by lstp is consistent when:
(strp->length == 0) == (strp->headp == NULL)
Parameters
[in] lstp Pointer to a presumed consistent UrosList object.
Returns
true when lstp is not NULL and the list descriptor is consistent.
Definition at line 1369 of file urosBase.c.
References UrosList::headp, and UrosList::length.
Referenced by urosListAdd(), urosListClean(), urosListContains(), urosListFind(), urosListRemove(), and urosNodeFindNewPublishers().
uros_bool_t urosListNotEmpty (const UrosList * lstp)
Checks if a list is not empty.
Checks if the addressed list is a consistent, non-empty list.
See Also
urosListIsValid
Parameters
[in] lstp Pointer to a presumed UrosList object.
Returns
true when lstp is not NULL and the list is not empty.
Definition at line 1385 of file urosBase.c.
References UrosList::headp, and UrosList::length.
uros_bool_t urosListContains (const UrosList * lstp, const UrosListNode * np)
Checks if the list contains the references node.
Scans the list until a node with the requested address is found, or there are no more entries.
Parameters
[in] lstp Pointer to an initialized UrosList object.
[in] np Pointer to an UrosListNode supposed to belong to the list.
Returns
true if a node with the requested address is found, NULL otherwise.
Definition at line 1403 of file urosBase.c.
References UrosList::headp, UrosListNode::nextp, UROS_FALSE, UROS_TRUE, urosAssert, and urosListIsValid().
UrosListNode* urosListFind (const UrosList * lstp, uros_cmp_f filter, const void * featurep)
First matching node occurrence of the list.
Scans the list and returns the first matching node entry.
Parameters
[in] lstp Pointer to an initialized UrosList object.
[in] filter Comparison function applied to each list node, with the following signature:
uros_bool_t (*filter)(const UrosListNode *np, const void *featurep);
[in] featurep Pointer to a feature that a matching node must satisfy by passing it to filter.
Returns
Pointer to the first node which satisfies the requested feature.
Return values
NULL No such node found.
Definition at line 1437 of file urosBase.c.
References UrosList::headp, UrosListNode::nextp, urosAssert, and urosListIsValid().
Referenced by urosFindStaticMsgType(), urosFindStaticMsgTypeSZ(), urosFindStaticSrvType(), urosFindStaticSrvTypeSZ(), urosTopicListFindByName(), and urosTopicListFindByTopic().
void urosListAdd (UrosList * lstp, UrosListNode * np)
Adds a node to the list.
The node is added to the head of the list.
Precondition
No node of the list has the same address of np (it is unique).
Postcondition
The head of the list is np.
The list length is incremented by one.
Parameters
[in,out] lstp Pointer to an initialized UrosList object.
[in] np Pointer to the node to be added, NULL forbidden.
Definition at line 1466 of file urosBase.c.
References UrosList::headp, UrosList::length, UrosListNode::nextp, urosAssert, and urosListIsValid().
Referenced by urosNodeFindNewPublishers(), urosRegisterStaticMsgType(), urosRegisterStaticMsgTypeSZ(), urosRegisterStaticSrvType(), and urosRegisterStaticSrvTypeSZ().
UrosListNode* urosListRemove (UrosList * lstp, const UrosListNode * np)
Removes a node from the list.
The node, if found, is unlinked from the list and returned.
Postcondition
The node does not belong to the list.
The node has no successors.
The list is consistent.
Parameters
[in,out] lstp Pointer to an initialized UrosList object.
[in] np Pointer to the node to be removed from the list.
Returns
Pointer to the removed (unlinked) node.
Return values
np The addressed node, if found inside the list.
NULL No such node found inside the list.
Definition at line 1496 of file urosBase.c.
References UrosList::headp, UrosList::length, UrosListNode::nextp, urosAssert, and urosListIsValid().
Referenced by urosNodeUnpublishService(), urosNodeUnpublishTopic(), and urosNodeUnsubscribeTopic().
uros_bool_t urosTopicListNodeHasTopic (const UrosListNode * np, const UrosTopic * topicp)
Checks if the list node is linked to the referenced topic.
The comparison is done at reference (pointer) level.
Parameters
[in] np Pointer to an initialized UrosListNode which points to an initialized UrosTopic descriptor.
[in] topicp Pointer to an initialized UrosTopic.
Returns
true iif the topic of the node has the requested topic.
Definition at line 1530 of file urosBase.c.
References UrosListNode::datap, and urosAssert.
Referenced by urosTopicListFindByTopic().
uros_bool_t urosTopicListNodeHasName (const UrosListNode * np, const UrosString * namep)
Checks if the list node links to a topic with the requested name.
See Also
urosStringCmp()
Parameters
[in] np Pointer to an initialized UrosListNode which points to an initialized UrosTopic descriptor.
[in] namep Pointer to a non-empty UrosString.
Returns
true iif the topic of the node has the requested name.
Definition at line 1550 of file urosBase.c.
References UrosListNode::datap, urosAssert, urosStringCmp(), and urosStringNotEmpty().
Referenced by urosTopicListFindByName().
UrosListNode* urosTopicListFindByTopic (const UrosList * lstp, const UrosTopic * topicp)
Gets the list node referencing a specific topic.
Scans the list to find the node referencing a specific topic.
Note
This function is not thread safe, please lock it with a dedicated locking primitive (e.g. UrosMutex).
See Also
urosListFind
urosTopicListNodeHasTopic
Parameters
[in] lstp Pointer to an initialized UrosList with UrosTopic entries.
[in] topicp Requested topic reference, NULL forbidden.
Returns
Pointer to the registered type descriptor with the requested name.
Return values
NULL No such topic node found.
Definition at line 1576 of file urosBase.c.
References urosListFind(), and urosTopicListNodeHasTopic().
UrosListNode* urosTopicListFindByName (const UrosList * lstp, const UrosString * namep)
Gets the list node referencing a topic with the requested name.
Scans the list to find the node referencing the topic with the requested name.
Note
This function is not thread safe, please lock it with a dedicated locking primitive (e.g. UrosMutex).
See Also
urosListFind
urosTopicListNodeHasName
Parameters
[in] lstp Pointer to an initialized UrosList with UrosTopic entries.
[in] namep Requested type name, null-terminated string, NULL forbidden.
Returns
Pointer to the registered type descriptor with the requested name.
Return values
NULL No such topic node found.
Definition at line 1600 of file urosBase.c.
References urosListFind(), and urosTopicListNodeHasName().
Referenced by urosNodePublishService(), urosNodePublishTopic(), urosNodeSubscribeParam(), urosNodeSubscribeTopic(), urosNodeUnpublishService(), urosNodeUnpublishTopic(), urosNodeUnsubscribeParam(), and urosNodeUnsubscribeTopic().