μROSnode
Low-level functions
Threading
Detailed Description
Semaphore
void uros_lld_sem_objectinit (UrosSem *semp, uros_cnt_t n)
Initializes a semaphore.
void uros_lld_sem_clean (UrosSem *semp)
Cleans a semaphore.
void uros_lld_sem_wait (UrosSem *semp)
Waits for a semaphore signal.
void uros_lld_sem_signal (UrosSem *semp)
Semaphore signal.
uros_cnt_t uros_lld_sem_value (UrosSem *semp)
Gets the semaphore value.
Mutex
uros_err_t uros_lld_mutex_objectinit (UrosMutex *mtxp)
Initializes a mutex.
void uros_lld_mutex_clean (UrosMutex *mtxp)
Cleans a mutex.
void uros_lld_mutex_lock (UrosMutex *mtxp)
Locks a mutex.
void uros_lld_mutex_unlock (UrosMutex *mtxp)
Unlocks a mutex.
Condition variable
void uros_lld_condvar_objectinit (UrosCondVar *cvp)
Initializes a condvar.
void uros_lld_condvar_clean (UrosCondVar *cvp)
Cleans a condvar.
void uros_lld_condvar_wait (UrosCondVar *cvp, UrosMutex *mtxp)
Waits for a condvar signal.
void uros_lld_condvar_signal (UrosCondVar *cvp)
Single condvar signal.
void uros_lld_condvar_broadcast (UrosCondVar *cvp)
Broadcast condvar signal.
Thread
UrosThreadId uros_lld_thread_self (void)
Gets the current thread identifier.
const char * uros_lld_thread_getname (UrosThreadId id)
Gets the name of the thread.
uros_err_t uros_lld_thread_createstatic (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, void *stackp, size_t stacksize)
Creates a thread with a static stack.
uros_err_t uros_lld_thread_createfrommempool (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, UrosMemPool *mempoolp)
Creates a thread allocating the stack from a memory pool.
uros_err_t uros_lld_thread_createfromheap (UrosThreadId *idp, const char *namep, uros_prio_t priority, uros_proc_f routine, void *argp, size_t stacksize)
Creates a thread allocating the stack on the deafult heap.
uros_err_t uros_lld_thread_join (UrosThreadId id)
Joins a thread.
Function Documentation
void uros_lld_sem_objectinit (UrosSem * semp, uros_cnt_t n)
Initializes a semaphore.
The semaphore object is initialized, and an initial count is assigned.
Precondition
The semaphore is not initialized.
Parameters
[in,out] semp Pointer to an allocated UrosSem object.
n Initial semaphore count.
Definition at line 80 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosSemObjectInit().
void uros_lld_sem_clean (UrosSem * semp)
Cleans a semaphore.
Deallocates any memory chunks allocated by the object itself.
Precondition
The semaphore is initialized.
Postcondition
The semaphore is not initialized, call urosSemObjectInit() to use it again.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 100 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosSemClean().
void uros_lld_sem_wait (UrosSem * semp)
Waits for a semaphore signal.
Waits until the semaphore counter is positive. When positive, it is decremented and the procedure returns the control to the caller.
Note
Depending on the low-level implementation, it may support a priority inversion mechanism.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 118 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosSemWait().
void uros_lld_sem_signal (UrosSem * semp)
Semaphore signal.
Increments a semaphore counter.
Parameters
[in,out] semp Pointer to an initialized UrosSem object.
Definition at line 133 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosSemSignal().
uros_cnt_t uros_lld_sem_value (UrosSem * semp)
Gets the semaphore value.
Reads the current semaphore value.
Warning
Thread-safe, but the value may not be consistent after a call to this function.
Parameters
[in] semp Pointer to an initialized UrosSem object.
Returns
Current semaphore count.
Definition at line 152 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosSemValue().
uros_err_t uros_lld_mutex_objectinit (UrosMutex * mtxp)
Initializes a mutex.
The mutex object is initialized, and set as unlocked.
Precondition
The mutex is not initialized.
Postcondition
The mutex is unlocked.
Parameters
[in,out] mtxp Pointer to an allocated UrosMutex object.
Returns
Error code.
Definition at line 180 of file uros_lld_threading.c.
References UROS_ERR_NOTIMPL, and urosAssert.
Referenced by urosMutexObjectInit().
void uros_lld_mutex_clean (UrosMutex * mtxp)
Cleans a mutex.
Deallocates any memory chunks allocated by the object itself.
Precondition
The mutex is initialized.
Postcondition
The mutex is not initialized, call urosMutexObjectInit() to use it again.
Parameters
[in,out] mtxp Pointer to an initialized UrosMutex object.
Definition at line 200 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosMutexClean().
void uros_lld_mutex_lock (UrosMutex * mtxp)
Locks a mutex.
Tries to lock a mutex. If the mutex is already locked, it waits until it is unlocked.
Note
Depending on the low-level implementation, it may support a priority inversion mechanism.
Postcondition
The mutex is locked.
Parameters
[in,out] mtxp Pointer to an initialized UrosMutex object.
Definition at line 220 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosMutexLock().
void uros_lld_mutex_unlock (UrosMutex * mtxp)
Unlocks a mutex.
Precondition
The mutex is locked.
Postcondition
The mutex is unlocked.
Parameters
[in,out] mtxp Pointer to a locked UrosMutex object.
Definition at line 237 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosMutexUnlock().
void uros_lld_condvar_objectinit (UrosCondVar * cvp)
Initializes a condvar.
Precondition
The condvar is not initialized.
Postcondition
The condvar is initialized.
Parameters
[in,out] cvp Pointer to an allocated UrosCondVar object.
Definition at line 261 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosCondVarObjectInit().
void uros_lld_condvar_clean (UrosCondVar * cvp)
Cleans a condvar.
Deallocates any memory chunks allocated by the object itself.
Precondition
The condvar is initialized.
Postcondition
The condvar is not initialized, call urosConvVarObjectInit() to use it again.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 280 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosCondVarClean().
void uros_lld_condvar_wait (UrosCondVar * cvp, UrosMutex * mtxp)
Waits for a condvar signal.
Waits until the condvar is signalled.
Note
This procedure must be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
[in,out] mtxp Pointer to the mutex guarding this condvar.
Definition at line 299 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosCondVarWait().
void uros_lld_condvar_signal (UrosCondVar * cvp)
Single condvar signal.
Signals a condvar to a single waiting thread.
Note
This procedure may be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 317 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosCondVarSignal().
void uros_lld_condvar_broadcast (UrosCondVar * cvp)
Broadcast condvar signal.
Signals a condvar to all of the waiting threads.
Note
This procedure may be called within a lock zone guarded by a mutex, shared by the waiting and the signalling thread.
Parameters
[in,out] cvp Pointer to an initialized UrosCondVar object.
Definition at line 334 of file uros_lld_threading.c.
References urosAssert.
Referenced by urosCondVarBroadcast().
UrosThreadId uros_lld_thread_self (void)
Gets the current thread identifier.
Returns
The current thread identifier.
Definition at line 355 of file uros_lld_threading.c.
Referenced by urosThreadSelf().
const char* uros_lld_thread_getname (UrosThreadId id)
Gets the name of the thread.
Parameters
[in] id Thread identifier.
Returns
Pointer to the name of the thread string, null-terminated.
Return values
NULL No name assigned to the thread.
Definition at line 371 of file uros_lld_threading.c.
Referenced by urosThreadGetName().
uros_err_t uros_lld_thread_createstatic (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, void * stackp, size_t stacksize)
Creates a thread with a static stack.
Creates a new thread. The memory chunk for the stack is externally declared, and is simply referenced. It is usually allocated as a static buffer.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] stackp Pointer to the externally allocated stack buffer.
[in] stacksize Stack size, in bytes.
Returns
Error code.
Definition at line 405 of file uros_lld_threading.c.
References UROS_ERR_NOTIMPL, and urosAssert.
Referenced by urosThreadCreateStatic().
uros_err_t uros_lld_thread_createfrommempool (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, UrosMemPool * mempoolp)
Creates a thread allocating the stack from a memory pool.
Creates a new thread. The memory chunk for the stack is allocated from a memory pool.
Warning
The thread creation is suspended until there is a free slot in the memory pool.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] mempoolp Pointer to the memory pool where to allocate a stack.
Returns
Error code.
Definition at line 451 of file uros_lld_threading.c.
References UROS_ERR_NOTIMPL, and urosAssert.
Referenced by urosThreadCreateFromMemPool().
uros_err_t uros_lld_thread_createfromheap (UrosThreadId * idp, const char * namep, uros_prio_t priority, uros_proc_f routine, void * argp, size_t stacksize)
Creates a thread allocating the stack on the deafult heap.
Precondition
The stack is big enough to avoid stack overflow.
Parameters
[out] idp Pointer to the UrosThreadId where the created thread id is stored.
[in] namep Pointer to the default thread name, valid for the whole the thread life. Null-terminated string.
[in] priority Thread priority.
[in] routine Thread routine, entry point of the thread program.
[in] argp Argument passed to the thread routine. Can be NULL.
[in] stacksize Stack size, in bytes.
Returns
Error code.
Definition at line 491 of file uros_lld_threading.c.
References UROS_ERR_NOTIMPL, and urosAssert.
Referenced by urosThreadCreateFromHeap().
uros_err_t uros_lld_thread_join (UrosThreadId id)
Joins a thread.
Waits until the required thread has exited, and releases its allocated memory.
Postcondition
The required thread does not exist anymore.
Any resources allocated by the thread creation are released (e.g. stack).
Parameters
[in] id Identifier of the thread being joined.
Returns
Error code.
Definition at line 523 of file uros_lld_threading.c.
References UROS_ERR_NOTIMPL.
Referenced by urosThreadJoin().