μROSnode
Call functions
XMLRPC
Detailed Description
See Also
http://www.ros.org/wiki/ROS/Master_Slave_APIs
http://www.ros.org/wiki/ROS/Master_API
http://www.ros.org/wiki/ROS/Slave_API
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Master API calls
uros_err_t urosRpcCallRegisterService (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *service, const UrosString *service_api, const UrosString *caller_api, UrosRpcResponse *resp)
Registers the caller as a provider of the specified service.
uros_err_t urosRpcCallUnregisterService (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *service, const UrosString *service_api, UrosRpcResponse *resp)
Unregister the caller as a provider of the specified service.
uros_err_t urosRpcCallRegisterSubscriber (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosString *topic_type, const UrosString *caller_api, UrosRpcResponse *resp)
Subscribe the caller to the specified topic.
uros_err_t urosRpcCallUnregisterSubscriber (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosString *caller_api, UrosRpcResponse *resp)
Unregister the caller as a publisher of the topic.
uros_err_t urosRpcCallRegisterPublisher (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosString *topic_type, const UrosString *caller_api, UrosRpcResponse *resp)
Register the caller as a publisher the topic.
uros_err_t urosRpcCallUnregisterPublisher (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosString *caller_api, UrosRpcResponse *resp)
Unregister the caller as a publisher of the topic.
uros_err_t urosRpcCallLookupNode (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *node, UrosRpcResponse *resp)
Get the XML-RPC URI of the node with the associated name.
uros_err_t urosRpcCallGetPublishedTopics (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *subgraph, UrosRpcResponse *resp)
Get list of topics that can be subscribed to.
uros_err_t urosRpcCallGetTopicTypes (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve list topic names and their types.
uros_err_t urosRpcCallGetSystemState (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve list representation of system state.
uros_err_t urosRpcCallGetUri (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Get the URI of the the Master.
uros_err_t urosRpcCallLookupService (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *service, UrosRpcResponse *resp)
Lookup all provider of a particular service.
Parameter server API calls
uros_err_t urosRpcCallDeleteParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *key, UrosRpcResponse *resp)
Delete parameter.
uros_err_t urosRpcCallSetParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *key, const UrosRpcParam *value, UrosRpcResponse *resp)
Set parameter.
uros_err_t urosRpcCallGetParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *key, UrosRpcResponse *resp)
Retrieve parameter value from server.
uros_err_t urosRpcCallSearchParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *key, UrosRpcResponse *resp)
Search for parameter key on the Parameter Server.
uros_err_t urosRpcCallSubscribeParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *caller_api, const UrosString *key, UrosRpcResponse *resp)
Retrieve parameter value from server and subscribe to updates to that param.
uros_err_t urosRpcCallUnsubscribeParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *caller_api, const UrosString *key, UrosRpcResponse *resp)
Retrieve parameter value from server and subscribe to updates to that param.
uros_err_t urosRpcCallHasParam (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *key, UrosRpcResponse *resp)
Check if parameter is stored on server.
uros_err_t urosRpcCallGetParamNames (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Get list of all parameter names stored on this server.
Slave API calls
uros_err_t urosRpcCallGetBusStats (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve transport/topic statistics.
uros_err_t urosRpcCallGetBusInfo (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve transport/topic connection information.
uros_err_t urosRpcCallGetMasterUri (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Get the URI of the Master node.
uros_err_t urosRpcCallShutdown (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *msg, UrosRpcResponse *resp)
Stop this server.
uros_err_t urosRpcCallGetPid (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Get the PID of this server.
uros_err_t urosRpcCallGetSubscriptions (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve a list of topics that this node subscribes to.
uros_err_t urosRpcCallGetPublications (const UrosAddr *addrp, const UrosString *caller_id, UrosRpcResponse *resp)
Retrieve a list of topics that this node publishes.
uros_err_t urosRpcCallParamUpdate (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *parameter_key, const UrosRpcParam *parameter_value, UrosRpcResponse *resp)
Callback from master with updated value of subscribed parameter.
uros_err_t urosRpcCallPublisherUpdate (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosRpcParamList *publishers, UrosRpcResponse *resp)
Callback from master of current publisher list for specified topic.
uros_err_t urosRpcCallRequestTopic (const UrosAddr *addrp, const UrosString *caller_id, const UrosString *topic, const UrosRpcParamList *protocols, UrosRpcResponse *resp)
Publisher node API method called by a subscriber node.
Function Documentation
uros_err_t urosRpcCallRegisterService (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * service, const UrosString * service_api, const UrosString * caller_api, UrosRpcResponse * resp)
Registers the caller as a provider of the specified service.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] service Fully-qualified name of service. Non-empty string pointer.
[in] service_api ROSRPC Service URI. Non-empty string pointer.
[in] caller_api XML-RPC URI of caller node. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 941 of file urosRpcCall.c.
Referenced by urosNodePublishServiceByDesc().
uros_err_t urosRpcCallUnregisterService (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * service, const UrosString * service_api, UrosRpcResponse * resp)
Unregister the caller as a provider of the specified service.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] service Fully-qualified name of service. Non-empty string pointer.
[in] service_api API URI of service to unregister. Unregistration will only occur if current registration matches. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, int numUnregistered ]
Number of unregistrations (either 0 or 1). If this is zero it means that the caller was not registered as a service provider. The call still succeeds as the intended final state is reached.
Returns
Error code.
Definition at line 977 of file urosRpcCall.c.
Referenced by urosNodeUnpublishService().
uros_err_t urosRpcCallRegisterSubscriber (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosString * topic_type, const UrosString * caller_api, UrosRpcResponse * resp)
Subscribe the caller to the specified topic.
In addition to receiving a list of current publishers, the subscriber will also receive notifications of new publishers via the publisherUpdate() API.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Fully-qualified name of topic. Non-empty string pointer.
[in] topic_type Datatype for topic. Must be a package-resource name, i.e. the .msg name. Non-empty string pointer.
[in] caller_api API URI of subscriber to register. Will be used for new publisher notifications. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [str publisherN] ]
Returns
Error code.
Definition at line 1014 of file urosRpcCall.c.
Referenced by urosNodeSubscribeTopicByDesc().
uros_err_t urosRpcCallUnregisterSubscriber (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosString * caller_api, UrosRpcResponse * resp)
Unregister the caller as a publisher of the topic.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Fully-qualified name of topic. Non-empty string pointer.
[in] caller_api API URI of service to unregister. Unregistration will only occur if current registration matches. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, int numUnsubscribed ]
If numUnsubscribed is zero it means that the caller was not registered as a subscriber. The call still succeeds as the intended final state is reached.
Returns
Error code.
Definition at line 1050 of file urosRpcCall.c.
Referenced by urosNodeUnsubscribeTopic().
uros_err_t urosRpcCallRegisterPublisher (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosString * topic_type, const UrosString * caller_api, UrosRpcResponse * resp)
Register the caller as a publisher the topic.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Fully-qualified name of topic to register. Non-empty string pointer.
[in] topic_type Datatype for topic. Must be a package-resource name, i.e. the .msg name. Non-empty string pointer.
[in] caller_api API URI of publisher to register. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [str subscriberApiN] ]
Returns
Error code.
Definition at line 1084 of file urosRpcCall.c.
Referenced by urosNodePublishTopicByDesc().
uros_err_t urosRpcCallUnregisterPublisher (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosString * caller_api, UrosRpcResponse * resp)
Unregister the caller as a publisher of the topic.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Fully-qualified name of topic to unregister. Non-empty string pointer.
[in] caller_api API URI of publisher to unregister. Unregistration will only occur if current registration matches. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, int numUnregistered ]
If numUnregistered is zero it means that the caller was not registered as a publisher. The call still succeeds as the intended final state is reached.
Returns
Error code.
Definition at line 1121 of file urosRpcCall.c.
Referenced by urosNodeUnpublishTopic().
uros_err_t urosRpcCallLookupNode (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * node, UrosRpcResponse * resp)
Get the XML-RPC URI of the node with the associated name.
This API is for looking information about publishers and subscribers. Use lookupService() instead to lookup ROS-RPC URIs.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] node Name of node to lookup. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, str URI ]
Returns
Error code.
Definition at line 1151 of file urosRpcCall.c.
References UrosString::datap, UrosString::length, UROS_RPCP_STRING, and urosAssert.
uros_err_t urosRpcCallGetPublishedTopics (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * subgraph, UrosRpcResponse * resp)
Get list of topics that can be subscribed to.
This does not return topics that have no publishers.
See Also
http://www.ros.org/wiki/ROS/Master_API
urosRpcCallGetSystemState()
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] subgraph Restrict topic names to match within the specified subgraph. Subgraph namespace is resolved relative to the caller's namespace. Use emptry string to specify all names. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [[str topicN, str typeN]] ]
Returns
Error code.
Definition at line 1187 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetTopicTypes (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve list topic names and their types.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [[str topicN, str typeN]] ]
Returns
Error code.
Definition at line 1212 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetSystemState (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve list representation of system state.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage,
  [
    [ str topicN, [str topicN_publisherM] ],
    [ str topicN, [str topicN_subscriberM] ],
    [ str serviceN, [str serviceN_providerM] ]
  ]
]
Returns
Error code.
Definition at line 1244 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetUri (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Get the URI of the the Master.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, str masterURI ]
Returns
Error code.
Definition at line 1268 of file urosRpcCall.c.
References UROS_RPCP_STRING.
uros_err_t urosRpcCallLookupService (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * service, UrosRpcResponse * resp)
Lookup all provider of a particular service.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] service Fully-qualified name of service. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, str serviceURI ]
Returns
Error code.
Definition at line 1294 of file urosRpcCall.c.
References UROS_RPCP_STRING, urosAssert, and urosStringNotEmpty().
uros_err_t urosRpcCallDeleteParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * key, UrosRpcResponse * resp)
Delete parameter.
See Also
http://www.ros.org/wiki/ROS/Master_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] key Parameter name. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 1328 of file urosRpcCall.c.
References urosAssert, and urosStringNotEmpty().
uros_err_t urosRpcCallSetParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * key, const UrosRpcParam * value, UrosRpcResponse * resp)
Set parameter.
Note
If value is a dictionary it will be treated as a parameter tree, where key is the parameter namespace.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] key Parameter name. Non-empty string pointer.
[in] value Parameter value.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 1361 of file urosRpcCall.c.
References UrosRpcParam::class, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, urosAssert, urosFree(), urosNew, urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosRpcResponse::valuep.
uros_err_t urosRpcCallGetParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * key, UrosRpcResponse * resp)
Retrieve parameter value from server.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] key Parameter name. If key is a namespace, it will return a parameter tree. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any parameterValue ]
Returns
Error code.
Definition at line 1422 of file urosRpcCall.c.
References urosAssert, and urosStringNotEmpty().
uros_err_t urosRpcCallSearchParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * key, UrosRpcResponse * resp)
Search for parameter key on the Parameter Server.
Search starts in caller's namespace and proceeds upwards through parent namespaces until Parameter Server finds a matching key.
Its behavior is to search for the first partial match. For example, imagine that there are two robot_description parameters:
/robot_description
/arm
/base
/pr2
/robot_description
/base
If starting in the namespace /pr2/foo and search for robot_description, searchParam() will match /pr2/robot_description. If searching for robot_description/arm it will return /pr2/robot_description/arm, even though that parameter does not exist (yet).
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] key Parameter name to search for. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, str foundKey ]
Returns
Error code.
Definition at line 1469 of file urosRpcCall.c.
References UROS_RPCP_STRING, urosAssert, and urosStringNotEmpty().
uros_err_t urosRpcCallSubscribeParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * caller_api, const UrosString * key, UrosRpcResponse * resp)
Retrieve parameter value from server and subscribe to updates to that param.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
urosUserParamUpdate()
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] caller_api Node API URI of subscriber for urosUserParamUpdate() callbacks.
[in] key Parameter name. Non-empty string pointer. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any parameterValue ]
If code is not 1, parameterValue should be ignored. parameterValue is an empty dictionary if the parameter has not been set yet.
Returns
Error code.
Definition at line 1507 of file urosRpcCall.c.
References UROS_ERR_NOMEM, urosAssert, urosFree(), urosNew, urosRpcResponseObjectInit(), and urosStringNotEmpty().
Referenced by urosNodeSubscribeParamByDesc().
uros_err_t urosRpcCallUnsubscribeParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * caller_api, const UrosString * key, UrosRpcResponse * resp)
Retrieve parameter value from server and subscribe to updates to that param.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
urosUserParamUpdate()
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] caller_api Node API URI of subscriber. Non-empty string pointer.
[in] key Parameter name. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, int numUnsubscribed ]
If numUnsubscribed is zero, it means that the caller was not subscribed to the parameter
Returns
Error code.
Definition at line 1571 of file urosRpcCall.c.
Referenced by urosNodeUnsubscribeParam().
uros_err_t urosRpcCallHasParam (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * key, UrosRpcResponse * resp)
Check if parameter is stored on server.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] key Parameter name. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, bool hasParam ]
Returns
Error code.
Definition at line 1599 of file urosRpcCall.c.
References UrosString::datap, UrosString::length, UROS_RPCP_BOOLEAN, and urosAssert.
uros_err_t urosRpcCallGetParamNames (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Get list of all parameter names stored on this server.
See Also
http://www.ros.org/wiki/ROS/Parameter%20Server%20API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [str paramaterNameN] ]
Returns
Error code.
Definition at line 1628 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetBusStats (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve transport/topic statistics.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage,
  [ publishStats, subscribeStats, serviceStats ]
]
where
publishStats:   [ [ topicName, messageDataSent, pubConnectionData ]... ]
subscribeStats: [ [ topicName, subConnectionData ]... ]
serviceStats:   [ numRequests, bytesReceived, bytesSent ] (proposed)
pubConnectionData: [ connectionId, bytesSent, numSent, connected ]*
subConnectionData: [ connectionId, bytesReceived, dropEstimate, connected ]*
dropEstimate is -1 for no estimate.
Returns
Error code.
Definition at line 1671 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetBusInfo (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve transport/topic connection information.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, busInfo ]
where busInfo is in the form:
[ [
    connectionIdN,
    destinationIdN,
    directionN,
    transportN,
    topicN,
    connectedN
] ]
connectionId is defined by the node and is opaque,
destinationId is the XMLRPC URI of the destination,
direction is one of 'i', 'o', or 'b' (in, out, both),
transport is the transport type (e.g. 'TCPROS'),
topic is the topic name,
connected indicates connection status.
Returns
Error code.
Definition at line 1714 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetMasterUri (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Get the URI of the Master node.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, str masterURI ]
Returns
Error code.
Definition at line 1738 of file urosRpcCall.c.
References UROS_RPCP_STRING.
uros_err_t urosRpcCallShutdown (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * msg, UrosRpcResponse * resp)
Stop this server.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] msg A message describing why the node is being shutdown. Valid string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 1765 of file urosRpcCall.c.
References urosAssert, and urosStringIsValid().
uros_err_t urosRpcCallGetPid (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Get the PID of this server.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, int serverProcessPID ]
Returns
Error code.
Definition at line 1792 of file urosRpcCall.c.
References UROS_RPCP_INT.
uros_err_t urosRpcCallGetSubscriptions (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve a list of topics that this node subscribes to.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [[str topicN, str topicTypeN]] ]
Returns
Error code.
Definition at line 1816 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallGetPublications (const UrosAddr * addrp, const UrosString * caller_id, UrosRpcResponse * resp)
Retrieve a list of topics that this node publishes.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [[str topicN, str topicTypeN]] ]
Returns
Error code.
Definition at line 1840 of file urosRpcCall.c.
References UROS_RPCP_ARRAY.
uros_err_t urosRpcCallParamUpdate (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * parameter_key, const UrosRpcParam * parameter_value, UrosRpcResponse * resp)
Callback from master with updated value of subscribed parameter.
See Also
http://www.ros.org/wiki/ROS/Slave_API
urosUserParamUpdate()
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] parameter_key Parameter name, globally resolved. Non-empty string pointer.
[in] parameter_value New parameter value.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 1869 of file urosRpcCall.c.
References UROS_ERR_NOMEM, urosAssert, urosFree(), urosNew, urosRpcResponseObjectInit(), and urosStringNotEmpty().
uros_err_t urosRpcCallPublisherUpdate (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosRpcParamList * publishers, UrosRpcResponse * resp)
Callback from master of current publisher list for specified topic.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Topic name. Non-empty string pointer.
[in] publishers List of current publishers for topic in the form of XMLRPC URIs.
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, any ignore ]
Returns
Error code.
Definition at line 1928 of file urosRpcCall.c.
References UROS_ERR_NOMEM, urosAssert, urosFree(), urosNew, urosRpcResponseObjectInit(), and urosStringNotEmpty().
uros_err_t urosRpcCallRequestTopic (const UrosAddr * addrp, const UrosString * caller_id, const UrosString * topic, const UrosRpcParamList * protocols, UrosRpcResponse * resp)
Publisher node API method called by a subscriber node.
This requests that source allocate a channel for communication. Subscriber provides a list of desired protocols for communication. Publisher returns the selected protocol along with any additional params required for establishing connection. For example, for a TCP/IP-based connection, the source node may return a port number of TCP/IP server.
See Also
http://www.ros.org/wiki/ROS/Slave_API
Parameters
[in] addrp Pointer to the Master API connection address.
[in] caller_id ROS caller ID. Non-empty string pointer.
[in] topic Topic name. Non-empty string pointer.
[in] protocols List of desired protocols for communication in order of preference. Each protocol is a list of the form:
[ protocolName, protocolParam1, protocolParam2, ... ]
[out] resp Pointer to the UrosRpcResponse response object. Format:
[ int code, str statusMessage, [str protocolParamN] ]
Returns
Error code.
Definition at line 1995 of file urosRpcCall.c.
References UrosRpcParam::class, UROS_ERR_BADPARAM, UROS_ERR_NOMEM, UROS_OK, UROS_RPCP_ARRAY, urosAssert, urosFree(), urosNew, urosRpcResponseObjectInit(), urosStringNotEmpty(), and UrosRpcResponse::valuep.