μROSnode
Parser methods
XMLRPC
Detailed Description
Functions
void urosRpcParserObjectInit (UrosRpcParser *pp, UrosConn *csp, char *rdbufp, size_t rdbuflen)
Initializes the XMLRPC parser object.
void urosRpcParserClean (UrosRpcParser *pp, uros_bool_t freeBuffer)
Cleans a UrosRpcParser object.
uros_err_t urosRpcParserRefill (UrosRpcParser *pp)
Refills the parsing buffer.
uros_err_t urosRpcParserRead (UrosRpcParser *pp, void *chunkp, size_t chunklen)
Reads a chunk from the incoming stream.
uros_err_t urosRpcParserExpectQuiet (UrosRpcParser *pp, const char *tokp, size_t toklen)
Expects the parser to be pointing to a token.
uros_err_t urosRpcParserExpect (UrosRpcParser *pp, const char *tokp, size_t toklen)
Expects the parser to be pointing to a token.
uros_err_t urosRpcParserExpectNoCase (UrosRpcParser *pp, const char *tokp, size_t toklen)
Expects the parser to be pointing to a token.
uros_err_t urosRpcParserExpectNoCaseQuiet (UrosRpcParser *pp, const char *tokp, size_t toklen)
Expects the parser to be pointing to a token.
uros_err_t urosRpcParserLookAhead (UrosRpcParser *pp, char c)
Expects the provided look-ahead character.
uros_err_t urosRpcParserLookAheadQuiet (UrosRpcParser *pp, char c)
Expects the provided look-ahead character.
uros_err_t urosRpcParserSkipUntil (UrosRpcParser *pp, char c)
Fast-forwards to a character.
uros_err_t urosRpcParserSkip (UrosRpcParser *pp, size_t length)
Skips some characters.
uros_err_t urosRpcParserSkipAfter (UrosRpcParser *pp, const char *tokp, size_t toklen)
Expects the parser to find a token, and skips it.
uros_err_t urosRpcParserSkipWs (UrosRpcParser *pp)
Skips any whitespace.
uros_err_t urosRpcParserExpectWs (UrosRpcParser *pp)
Expects some whitespace.
uros_err_t urosRpcParserUint32 (UrosRpcParser *pp, uint32_t *valuep)
Reads a decimal unsigned integer (uint32).
uros_err_t urosRpcParserInt32 (UrosRpcParser *pp, int32_t *valuep)
Reads a decimal signed integer (int32).
uros_err_t urosRpcParserDouble (UrosRpcParser *pp, double *valuep)
Reads a decimal double-precision value (double).
uros_err_t urosRpcParserHttpRequest (UrosRpcParser *pp)
Parses an incoming HTTP header section for an XMLRPC request.
uros_err_t urosRpcParserHttpResponse (UrosRpcParser *pp, uint32_t *codep)
Parses an incoming HTTP header section for an XMLRPC response.
uros_err_t urosRpcParserXmlAttrWVal (UrosRpcParser *pp, const char *namep, size_t namelen, const char *valp, size_t vallen)
Expects an XML attribute with a specific value.
uros_err_t urosRpcParserXmlTagBeginNoName (UrosRpcParser *pp)
Expects the beginning of an XML tag, without name.
uros_err_t urosRpcParserXmlTagBegin (UrosRpcParser *pp, const char *tagp, size_t taglen)
Expects the beginning of an XML tag with its name.
uros_err_t urosRpcParserXmlTagEnd (UrosRpcParser *pp)
Expects the end of an XML tag.
uros_err_t urosRpcParserXmlTagSlashEnd (UrosRpcParser *pp)
Expects the end of an empty XML tag.
uros_err_t urosRpcParserXmlTagOpen (UrosRpcParser *pp, const char *tagp, size_t taglen)
Expects an opening XML tag.
uros_err_t urosRpcParserXmlTagClose (UrosRpcParser *pp, const char *tagp, size_t taglen)
Expects a closing XML tag.
uros_err_t urosRpcParserXmlHeader (UrosRpcParser *pp)
Expects an XML header tag.
uros_err_t urosRpcParserParamValueInt (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses an integral XMLRPC parameter value.
uros_err_t urosRpcParserParamValueBoolean (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a boolean XMLRPC parameter value.
uros_err_t urosRpcParserParamValueString (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a string XMLRPC parameter value.
uros_err_t urosRpcParserParamValueDouble (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a double-precision XMLRPC parameter value.
uros_err_t urosRpcParserParamValueBase64 (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a base64 XMLRPC parameter value.
uros_err_t urosRpcParserParamValueStruct (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a struct (key-value map) XMLRPC parameter value.
uros_err_t urosRpcParserParamValueArray (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses an array XMLRPC parameter value.
uros_err_t urosRpcParserParamByTag (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a XMLRPC parameter value by its element tags.
uros_err_t urosRpcParserParamByTagQuiet (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a XMLRPC parameter value by its element tags.
uros_err_t urosRpcParserParamByClass (UrosRpcParser *pp, UrosRpcParam *paramp)
Parses a XMLRPC parameter value by its class.
uros_err_t urosRpcParserParam (UrosRpcParser *pp, UrosRpcParam *paramp, uros_rpcparamclass_t paramclass)
Parses a XMLRPC parameter value.
uros_err_t urosRpcParserMethodResponse (UrosRpcParser *pp, UrosRpcResponse *resp)
Parses an XMLRPC method response.
Function Documentation
void urosRpcParserObjectInit (UrosRpcParser * pp, UrosConn * csp, char * rdbufp, size_t rdbuflen)
Initializes the XMLRPC parser object.
Assigns the connection and the read buffer.
Precondition
The parser is not initialized.
Postcondition
The parser is assigned a connection and an optional temporary buffer. The other fields are reset.
Parameters
[in,out] pp Pointer to an allocated UrosRpcParser object.
[in] csp Pointer to an UrosConn connection from which to receive the stream to be parsed.
[in] rdbufp Pointer to the temporary buffer, used to parse strings ahead. Can be NULL only if rdbuflen is 0.
[in] rdbuflen Length of the temporary read buffer.
Definition at line 181 of file urosRpcParser.c.
References UrosRpcParser::buflen, UrosRpcParser::bufp, UrosRpcParser::contentLength, UrosRpcParser::csp, UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::mark, UrosRpcParser::pending, UrosRpcParser::rdbuflen, UrosRpcParser::rdbufp, UrosRpcParser::total, UROS_OK, and urosAssert.
void urosRpcParserClean (UrosRpcParser * pp, uros_bool_t freeBuffer)
Cleans a UrosRpcParser object.
Resets the state of its internal fields. If needed, the buffer is deallocated. Does not unlink from the assigned connection.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] freeBuffer Deallocates buffers.
Definition at line 213 of file urosRpcParser.c.
References UrosRpcParser::buflen, UrosRpcParser::bufp, UrosRpcParser::contentLength, UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::mark, UrosRpcParser::pending, UrosRpcParser::rdbuflen, UrosRpcParser::rdbufp, UrosRpcParser::total, UROS_OK, urosAssert, and urosFree().
uros_err_t urosRpcParserRefill (UrosRpcParser * pp)
Refills the parsing buffer.
Receives enough data to satisfy the Content-Length (set to ~0u when unknown).
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Definition at line 245 of file urosRpcParser.c.
References UrosRpcParser::buflen, UrosRpcParser::bufp, UrosRpcParser::contentLength, UrosRpcParser::csp, UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::mark, UrosRpcParser::pending, UrosRpcParser::total, UROS_OK, urosAssert, urosConnRecv(), urosError, and urosErrorText().
Referenced by urosRpcParserDouble(), urosRpcParserExpect(), urosRpcParserExpectNoCase(), urosRpcParserExpectNoCaseQuiet(), urosRpcParserExpectQuiet(), urosRpcParserLookAheadQuiet(), urosRpcParserRead(), urosRpcParserSkip(), urosRpcParserSkipAfter(), urosRpcParserSkipWs(), and urosRpcParserUint32().
uros_err_t urosRpcParserRead (UrosRpcParser * pp, void * chunkp, size_t chunklen)
Reads a chunk from the incoming stream.
Copies a chunk of the incoming stream to a pre-allocated buffer.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in,out] chunkp Pointer to the pre-allocated buffer on which the chunk will be copied after reception.
[in] chunklen Length of the chunk to be read. Can be 0.
Returns
Error code.
Definition at line 272 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, and urosRpcParserRefill().
uros_err_t urosRpcParserExpectQuiet (UrosRpcParser * pp, const char * tokp, size_t toklen)
Expects the parser to be pointing to a token.
Does not print any parsing error messages.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tokp Pointer to the expected token string.
[in] toklen Length of the expected token.
Returns
Error code.
Return values
UROS_ERR_PARSE The received token does not match.
Definition at line 316 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, and urosRpcParserRefill().
Referenced by urosRpcParserDouble(), urosRpcParserHttpRequest(), urosRpcParserHttpResponse(), urosRpcParserInt32(), urosRpcParserMethodResponse(), urosRpcParserParam(), urosRpcParserParamByTagQuiet(), urosRpcParserXmlAttrWVal(), urosRpcParserXmlHeader(), and urosRpcParserXmlTagBeginNoName().
uros_err_t urosRpcParserExpect (UrosRpcParser * pp, const char * tokp, size_t toklen)
Expects the parser to be pointing to a token.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tokp Pointer to the expected token string.
[in] toklen Length of the expected token.
Returns
Error code.
Return values
UROS_ERR_PARSE The received token does not match.
Definition at line 374 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, urosError, and urosRpcParserRefill().
Referenced by urosRpcParserDouble(), urosRpcParserHttpRequest(), urosRpcParserHttpResponse(), urosRpcParserMethodResponse(), urosRpcParserParam(), urosRpcParserXmlAttrWVal(), urosRpcParserXmlHeader(), urosRpcParserXmlTagBegin(), urosRpcParserXmlTagBeginNoName(), urosRpcParserXmlTagClose(), urosRpcParserXmlTagEnd(), urosRpcParserXmlTagOpen(), and urosRpcParserXmlTagSlashEnd().
uros_err_t urosRpcParserExpectNoCase (UrosRpcParser * pp, const char * tokp, size_t toklen)
Expects the parser to be pointing to a token.
Ignores the case of alphabetical characters.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tokp Pointer to the expected token string.
[in] toklen Length of the expected token.
Returns
Error code.
Return values
UROS_ERR_PARSE The received token does not match.
Definition at line 441 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, urosError, and urosRpcParserRefill().
uros_err_t urosRpcParserExpectNoCaseQuiet (UrosRpcParser * pp, const char * tokp, size_t toklen)
Expects the parser to be pointing to a token.
Ignores the case of alphabetical characters. Does not print any parsing error messages.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tokp Pointer to the expected token string.
[in] toklen Length of the expected token.
Returns
Error code.
Return values
UROS_ERR_PARSE The received token does not match.
Definition at line 509 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, and urosRpcParserRefill().
Referenced by urosRpcParserHttpRequest(), and urosRpcParserHttpResponse().
uros_err_t urosRpcParserLookAhead (UrosRpcParser * pp, char c)
Expects the provided look-ahead character.
Parameters
[in] pp Pointer to an initialized UrosRpcParser object.
[in] c Expected look-ahead character.
Returns
Error code.
Return values
UROS_ERR_PARSE The look-ahead character does not match.
Definition at line 565 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::total, UROS_ERR_PARSE, urosAssert, urosError, and urosRpcParserLookAheadQuiet().
uros_err_t urosRpcParserLookAheadQuiet (UrosRpcParser * pp, char c)
Expects the provided look-ahead character.
Does not print any parsing error messages.
Parameters
[in] pp Pointer to an initialized UrosRpcParser object.
[in] c Expected look-ahead character.
Returns
Error code.
Return values
UROS_ERR_PARSE The look-ahead character does not match.
Definition at line 589 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UROS_ERR_PARSE, UROS_OK, urosAssert, and urosRpcParserRefill().
Referenced by urosRpcParserLookAhead(), urosRpcParserParam(), urosRpcParserParamValueString(), and urosRpcParserSkipUntil().
uros_err_t urosRpcParserSkipUntil (UrosRpcParser * pp, char c)
Fast-forwards to a character.
Advances the stream until the look-ahead character matches the reference one.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] c Reference character.
Returns
Error code.
Definition at line 613 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, urosAssert, and urosRpcParserLookAheadQuiet().
Referenced by urosRpcParserMethodResponse().
uros_err_t urosRpcParserSkip (UrosRpcParser * pp, size_t length)
Skips some characters.
Advances the stream for the provided number of characters.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] length Number of characters to skip.
Returns
Error code.
Definition at line 635 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, and urosRpcParserRefill().
Referenced by urosRpcParserMethodResponse().
uros_err_t urosRpcParserSkipAfter (UrosRpcParser * pp, const char * tokp, size_t toklen)
Expects the parser to find a token, and skips it.
Advances the stream until the expected token is found, and skips it.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tokp Pointer to the expected token string.
[in] toklen Length of the expected token.
Returns
Error code.
Definition at line 671 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), and urosRpcParserRefill().
Referenced by urosRpcParserHttpRequest(), urosRpcParserHttpResponse(), and urosRpcParserXmlTagBeginNoName().
uros_err_t urosRpcParserSkipWs (UrosRpcParser * pp)
Skips any whitespace.
Skips until a non-whitespace character is found.
Note
The whitespace characters are: ' ', '\r', '\n', '\t', '\v'.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Definition at line 731 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, and urosRpcParserRefill().
Referenced by urosRpcParserExpectWs(), urosRpcParserMethodResponse(), urosRpcParserParam(), urosRpcParserParamValueArray(), urosRpcParserParamValueStruct(), urosRpcParserXmlAttrWVal(), urosRpcParserXmlTagBeginNoName(), urosRpcParserXmlTagClose(), and urosRpcParserXmlTagOpen().
uros_err_t urosRpcParserExpectWs (UrosRpcParser * pp)
Expects some whitespace.
The look-ahead character(s) must be whitespace. Skips until a non-whitespace character is found.
Note
The whitespace characters are: ' ', '\r', '\n', '\t', '\v'.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Return values
UROS_ERR_PARSE No whitespace as look-ahead.
Definition at line 773 of file urosRpcParser.c.
References UrosRpcParser::err, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, urosAssert, urosError, urosErrorText(), and urosRpcParserSkipWs().
Referenced by urosRpcParserXmlHeader().
uros_err_t urosRpcParserUint32 (UrosRpcParser * pp, uint32_t * valuep)
Reads a decimal unsigned integer (uint32).
Warning
Accumulates digits as long as they are found, without any overflow checks.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] valuep Pointer to the allocated output result value address.
Returns
Error code.
Definition at line 801 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_EOF, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, urosError, and urosRpcParserRefill().
Referenced by urosRpcParserHttpRequest(), urosRpcParserHttpResponse(), and urosRpcParserInt32().
uros_err_t urosRpcParserInt32 (UrosRpcParser * pp, int32_t * valuep)
Reads a decimal signed integer (int32).
The sign symbol ('+' or '-') can be placed before the sequence of digits.
Warning
Accumulates digits as long as they are found, without any overflow checks.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] valuep Pointer to the allocated output result value address.
Returns
Error code.
Definition at line 853 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_ERR_PARSE, UROS_FALSE, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosRpcParserExpectQuiet(), and urosRpcParserUint32().
Referenced by urosRpcParserParamValueBoolean(), and urosRpcParserParamValueInt().
uros_err_t urosRpcParserDouble (UrosRpcParser * pp, double * valuep)
Reads a decimal double-precision value (double).
The sign symbol ('+' or '-') can be placed before the sequence of digits.
Warning
Accumulates digits as long as they are found, without any overflow checks.
It works well only for numbers close to the int32 range. This is not a fully-featured parser of floating-point numbers, at least not now.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] valuep Pointer to the allocated output result value address.
Returns
Error code.
Definition at line 896 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_EOF, UROS_ERR_PARSE, UROS_FALSE, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), and urosRpcParserRefill().
Referenced by urosRpcParserParamValueDouble().
uros_err_t urosRpcParserHttpRequest (UrosRpcParser * pp)
Parses an incoming HTTP header section for an XMLRPC request.
Receives the HTTP header section of a POST request at the root, which is in the form:
POST /RPC2 HTTP/1.(0|1)
The required headers are:
Content-Length, which is used by the parser to receive the correct number of pending characters,
Content-Type, which must be text/xml. Any other header is simply ignored.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Definition at line 988 of file urosRpcParser.c.
References UrosRpcParser::contentLength, UrosRpcParser::err, UrosRpcParser::mark, UrosRpcParser::total, UROS_ERR_EOF, UROS_ERR_PARSE, UROS_FALSE, UROS_NOP, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectNoCaseQuiet(), urosRpcParserExpectQuiet(), urosRpcParserSkipAfter(), and urosRpcParserUint32().
uros_err_t urosRpcParserHttpResponse (UrosRpcParser * pp, uint32_t * codep)
Parses an incoming HTTP header section for an XMLRPC response.
Receives the HTTP header section of an XMLRPC response. The required headers are:
Content-Length, which is used by the parser to receive the correct number of pending characters,
Content-Type, which must be text/xml. Any other header is simply ignored.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] codep Pointer to the allocated output HTTP status code address.
Returns
Error code.
Definition at line 1072 of file urosRpcParser.c.
References UrosRpcParser::contentLength, UrosRpcParser::err, UrosRpcParser::mark, UrosRpcParser::total, UROS_ERR_EOF, UROS_ERR_PARSE, UROS_FALSE, UROS_NOP, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectNoCaseQuiet(), urosRpcParserExpectQuiet(), urosRpcParserSkipAfter(), and urosRpcParserUint32().
uros_err_t urosRpcParserXmlAttrWVal (UrosRpcParser * pp, const char * namep, size_t namelen, const char * valp, size_t vallen)
Expects an XML attribute with a specific value.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] namep Pointer to the expected attribute name string.
[in] namelen Length of the expected attribute name.
[in] valp Pointer to the expected attribute value string.
[in] vallen Length of the expected attribute value length.
Returns
Error code.
Return values
UROS_ERR_PARSE Attribute not found, or not matching.
Definition at line 1158 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), and urosRpcParserSkipWs().
Referenced by urosRpcParserXmlHeader().
uros_err_t urosRpcParserXmlTagBeginNoName (UrosRpcParser * pp)
Expects the beginning of an XML tag, without name.
Reads the beginning of a tag, which is simply in the form:
<
Automatically skips any XML comments, and the whitespace after them.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag beginning found.
Definition at line 1206 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), urosRpcParserSkipAfter(), and urosRpcParserSkipWs().
Referenced by urosRpcParserParam(), urosRpcParserXmlTagBegin(), and urosRpcParserXmlTagOpen().
uros_err_t urosRpcParserXmlTagBegin (UrosRpcParser * pp, const char * tagp, size_t taglen)
Expects the beginning of an XML tag with its name.
Reads the beginning of a tag, which is simply in the form:
<NAME
Automatically skips any XML comments, and the whitespace after them.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tagp Pointer to the expected tag name string.
[in] taglen Length of the expected tag name.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag beginning found.
Definition at line 1251 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_OK, urosAssert, urosRpcParserExpect(), and urosRpcParserXmlTagBeginNoName().
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserXmlTagEnd (UrosRpcParser * pp)
Expects the end of an XML tag.
Reads the beginning of a tag, which is simply in the form:
>
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag end found.
Definition at line 1278 of file urosRpcParser.c.
References urosAssert, and urosRpcParserExpect().
uros_err_t urosRpcParserXmlTagSlashEnd (UrosRpcParser * pp)
Expects the end of an empty XML tag.
Reads the end of an empty tag, which is simply in the form:
/>
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag slash/end found.
Definition at line 1297 of file urosRpcParser.c.
References urosAssert, and urosRpcParserExpect().
uros_err_t urosRpcParserXmlTagOpen (UrosRpcParser * pp, const char * tagp, size_t taglen)
Expects an opening XML tag.
Reads the opening tag, which is in the form:
<NAME >
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tagp Pointer to the expected tag name string.
[in] taglen Length of the expected tag name.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag slash/end found.
Definition at line 1320 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_OK, urosAssert, urosRpcParserExpect(), urosRpcParserSkipWs(), and urosRpcParserXmlTagBeginNoName().
Referenced by urosRpcParserMethodResponse(), urosRpcParserParam(), urosRpcParserParamByTag(), and urosRpcParserParamValueArray().
uros_err_t urosRpcParserXmlTagClose (UrosRpcParser * pp, const char * tagp, size_t taglen)
Expects a closing XML tag.
Reads the closing tag, which is in the form:
</NAME >
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[in] tagp Pointer to the expected tag name string.
[in] taglen Length of the expected tag name.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML tag slash/end found.
Definition at line 1353 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_OK, urosAssert, urosRpcParserExpect(), and urosRpcParserSkipWs().
Referenced by urosRpcParserMethodResponse(), urosRpcParserParam(), and urosRpcParserParamValueArray().
uros_err_t urosRpcParserXmlHeader (UrosRpcParser * pp)
Expects an XML header tag.
The XML header tag is in the (conceptual) form:
<?xml version="1.0"[ encoding="US-ASCII"[ standalone="no"]]?>
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
Returns
Error code.
Return values
UROS_ERR_PARSE No XML header tag found.
Definition at line 1384 of file urosRpcParser.c.
References UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_NOP, UROS_OK, urosAssert, urosError, urosErrorText(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), urosRpcParserExpectWs(), and urosRpcParserXmlAttrWVal().
Referenced by urosRpcParserMethodResponse().
uros_err_t urosRpcParserParamValueInt (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses an integral XMLRPC parameter value.
See Also
urosRpcParserInt32()
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1434 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::err, UrosRpcParam::int32, UROS_OK, UROS_RPCP_INT, urosAssert, urosRpcParserInt32(), and UrosRpcParam::value.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueBoolean (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a boolean XMLRPC parameter value.
The boolean value is either 0 or 1.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1459 of file urosRpcParser.c.
References UrosRpcParam::boolean, UrosRpcParam::class, UrosRpcParser::err, UrosRpcParam::int32, UROS_ERR_PARSE, UROS_FALSE, UROS_NOP, UROS_OK, UROS_RPCP_BOOLEAN, UROS_TRUE, urosAssert, urosError, urosRpcParserInt32(), and UrosRpcParam::value.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueString (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a string XMLRPC parameter value.
An XMLRPC string ends where a look-ahead '<' is found.
Warning
Do not write comments inside those string values without <string> tags.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1496 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::curp, UrosString::datap, UrosRpcParser::err, UrosString::length, UrosRpcParser::pending, UrosRpcParser::rdbuflen, UrosRpcParser::rdbufp, UrosRpcParam::string, UrosRpcParser::total, UROS_ERR_PARSE, UROS_NOP, UROS_OK, UROS_RPCP_STRING, urosAlloc(), urosAssert, urosError, urosErrorText(), urosRpcParserLookAheadQuiet(), and UrosRpcParam::value.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueDouble (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a double-precision XMLRPC parameter value.
See Also
urosRpcParserDouble()
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1552 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::err, UrosRpcParam::real, UROS_OK, UROS_RPCP_DOUBLE, urosAssert, urosRpcParserDouble(), and UrosRpcParam::value.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueBase64 (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a base64 XMLRPC parameter value.
Warning
Not implemented.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1577 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::err, UROS_OK, UROS_RPCP_BASE64, and urosAssert.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueStruct (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a struct (key-value map) XMLRPC parameter value.
Warning
Not implemented.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1604 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::err, UROS_OK, UROS_RPCP_STRUCT, urosAssert, and urosRpcParserSkipWs().
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamValueArray (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses an array XMLRPC parameter value.
The array valued (fields) are stored into a parameter with UrosRpcParamList nature.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1634 of file urosRpcParser.c.
References UrosRpcParam::class, UrosRpcParser::curp, UrosRpcParser::err, UrosRpcParam::listp, UrosRpcParamNode::param, UrosRpcParser::pending, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_RPCP_ARRAY, UROS_TRUE, urosAssert, urosError, urosErrorText(), urosNew, urosRpcParamListAppendNode(), urosRpcParamListDelete(), urosRpcParamListObjectInit(), urosRpcParamListUnlinkNode(), urosRpcParamNodeDelete(), urosRpcParamNodeObjectInit(), urosRpcParserParamByTagQuiet(), urosRpcParserSkipWs(), urosRpcParserXmlTagClose(), urosRpcParserXmlTagOpen(), and UrosRpcParam::value.
Referenced by urosRpcParserParam().
uros_err_t urosRpcParserParamByTag (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a XMLRPC parameter value by its element tags.
The XMLRPC parameter class is decoded by reading its opening XML tag.
Note
The parameter value is expected to be enclosed within a value XML element.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1693 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_OK, urosAssert, and urosRpcParserXmlTagOpen().
Referenced by urosRpcParserMethodResponse().
uros_err_t urosRpcParserParamByTagQuiet (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a XMLRPC parameter value by its element tags.
The XMLRPC parameter class is decoded by reading its opening XML tag. Does not print any parsing error messages.
Note
The parameter value is expected to be enclosed within a value XML element.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1718 of file urosRpcParser.c.
References UrosRpcParser::err, UROS_OK, urosAssert, and urosRpcParserExpectQuiet().
Referenced by urosRpcParserParamValueArray().
uros_err_t urosRpcParserParamByClass (UrosRpcParser * pp, UrosRpcParam * paramp)
Parses a XMLRPC parameter value by its class.
The XMLRPC parameter class is already written inside the alloacted result value.
Note
The parameter value is expected to be enclosed within a value XML element.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
Returns
Error code.
Definition at line 1743 of file urosRpcParser.c.
References UrosRpcParam::class, urosAssert, and urosRpcParserParam().
uros_err_t urosRpcParserParam (UrosRpcParser * pp, UrosRpcParam * paramp, uros_rpcparamclass_t paramclass)
Parses a XMLRPC parameter value.
Note
The parameter value is expected to be enclosed within a value XML element.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] paramp Pointer to the allocated UrosRpcParam result.
[in] paramclass Expected parameter class.
Returns
Error code.
Definition at line 1766 of file urosRpcParser.c.
References UrosString::datap, UrosRpcParser::err, UrosRpcParam::string, UROS_ERR_BADPARAM, UROS_ERR_PARSE, UROS_NOP, UROS_OK, UROS_RPCP_ARRAY, UROS_RPCP_BASE64, UROS_RPCP_BOOLEAN, UROS_RPCP_DOUBLE, UROS_RPCP_INT, UROS_RPCP_STRING, UROS_RPCP_STRUCT, urosAssert, urosError, urosFree(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), urosRpcParserLookAheadQuiet(), urosRpcParserParamValueArray(), urosRpcParserParamValueBase64(), urosRpcParserParamValueBoolean(), urosRpcParserParamValueDouble(), urosRpcParserParamValueInt(), urosRpcParserParamValueString(), urosRpcParserParamValueStruct(), urosRpcParserSkipWs(), urosRpcParserXmlTagBegin(), urosRpcParserXmlTagBeginNoName(), urosRpcParserXmlTagClose(), urosRpcParserXmlTagOpen(), and UrosRpcParam::value.
Referenced by urosRpcParserMethodResponse(), and urosRpcParserParamByClass().
uros_err_t urosRpcParserMethodResponse (UrosRpcParser * pp, UrosRpcResponse * resp)
Parses an XMLRPC method response.
The expected response starts at the declaration of the XML header. The method response is parsed, and its decoded values are stored into a pre-allocated response descriptor.
Parameters
[in,out] pp Pointer to an initialized UrosRpcParser object.
[out] resp Pointer to an allocated UrosRpcResponse response descriptor.
Returns
Error code.
Definition at line 1879 of file urosRpcParser.c.
References UrosRpcResponse::code, UrosRpcParser::contentLength, UrosRpcParser::err, UrosRpcParam::int32, UrosRpcParser::mark, UrosRpcResponse::statusMsgp, UrosRpcParam::string, UrosRpcParser::total, UROS_ERR_PARSE, UROS_OK, UROS_RPCP_INT, UROS_RPCP_STRING, UROS_TRUE, urosAssert, urosNew, urosRpcParamClean(), urosRpcParamObjectInit(), urosRpcParserExpect(), urosRpcParserExpectQuiet(), urosRpcParserParam(), urosRpcParserParamByTag(), urosRpcParserSkip(), urosRpcParserSkipUntil(), urosRpcParserSkipWs(), urosRpcParserXmlHeader(), urosRpcParserXmlTagClose(), urosRpcParserXmlTagOpen(), urosRpcResponseObjectInit(), urosStringNew(), UrosRpcParam::value, and UrosRpcResponse::valuep.