μROSnode
Slave API functions
XMLRPC
Detailed Description
Functions
uros_err_t urosRpcSlaveConnectToPublishers (const UrosString *topicp, const UrosList *addrlstp)
Connects to a list of publishers.
uros_err_t urosRpcSlaveListenerThread (void *data)
XMLRPC Slave API listener thread.
uros_err_t urosRpcSlaveServerThread (UrosConn *csp)
XMLRPC Slave API processing thread.
Function Documentation
uros_err_t urosRpcSlaveConnectToPublishers (const UrosString * topicp, const UrosList * addrlstp)
Connects to a list of publishers.
Given the topic name and a list of publishers, tries to connect to all of them.
Precondition
There are no duplicates inside the publishers list.
The publishers exist.
Parameters
[in] topicp Pointer to a non-empty string which names the related topic.
[in] addrlstp Pointer to a valid list of publisher URIs.
Returns
Error code.
Definition at line 1034 of file urosRpcSlave.c.
References UrosListNode::datap, UrosList::headp, UrosListNode::nextp, uros_tcpcliargs_t::remoteAddr, UrosNode::status, UrosNodeStatus::tcpcliThdPool, uros_tcpcliargs_t::topicName, UROS_ERR_NOMEM, UROS_NOP, UROS_OK, UROS_STRARG, urosAssert, urosError, urosErrorText(), urosNew, urosNode, urosStringClone(), urosStringNotEmpty(), urosThreadPoolStartWorker(), and urosTopicSubParamsDelete().
uros_err_t urosRpcSlaveListenerThread (void * data)
XMLRPC Slave API listener thread.
This thread listens for any incoming XMLRPC calls to the Slave API.
     When a new connection request is received, a dedicated
     communication channel is spawned and handled by a new thread. This
     thread is allocated from the Slave thread pool. If no threads are
     free, it waits until one becomes available again.
See Also
urosRpcSlaveServerThread()
Precondition
There are no other XMLRPC listener threads with the same connection port.
Parameters
[in] data Ignored.
Returns
Error code.
Definition at line 1084 of file urosRpcSlave.c.
References UrosNode::config, UrosIp::dword, UrosAddr::ip, UrosAddr::port, UrosConn::remaddr, UrosNodeStatus::slaveThdPool, UrosNode::status, UROS_ADDRARG, UROS_ADDRFMT, UROS_ANY_IP, UROS_NOP, UROS_OK, UROS_PROTO_TCP, UROS_TRUE, UROS_XMLRPC_LISTENER_BACKLOG, UROS_XMLRPC_RECVTIMEOUT, UROS_XMLRPC_SENDTIMEOUT, urosAssert, urosConnAccept(), urosConnBind(), urosConnClose(), urosConnCreate(), urosConnListen(), urosConnObjectInit(), urosConnSetRecvTimeout(), urosConnSetSendTimeout(), urosError, urosErrorText(), urosFree(), urosMutexLock(), urosMutexUnlock(), urosNew, urosNode, urosThreadPoolStartWorker(), urosThreadSelf(), UrosNodeConfig::xmlrpcAddr, UrosNodeStatus::xmlrpcPid, and UrosNodeStatus::xmlrpcPidLock.
uros_err_t urosRpcSlaveServerThread (UrosConn * csp)
XMLRPC Slave API processing thread.
This worker thread processes an incoming XMLRPC connection accepted by the XMLRPC listener.
See Also
urosRpcSlaveListenerThread()
Precondition
The provided connection was accepted by the XMLRPC Listener.
The connection was alloacted with urosAlloc().
Postcondition
The connection is closed and deallocated.
Parameters
[in] csp Pointer to an UrosConn object, which is the connection accepted by the XMLRPC Slave API listener, and csp points to an invalid address.
Returns
Error code.
Definition at line 1174 of file urosRpcSlave.c.
References UROS_NOP, UROS_OK, urosAssert, urosConnClose(), urosError, urosErrorText(), and urosFree().
Referenced by urosNodeObjectInit().