μROSnode
Low-level functions
Connectivity
Detailed Description
Functions
uros_err_t uros_lld_hostnametoip (const UrosString *hostnamep, UrosIp *ipp)
Resolves an hostname to an IP address.
void uros_lld_conn_objectinit (UrosConn *cp)
Initializes a connection object.
uros_bool_t uros_lld_conn_isvalid (UrosConn *cp)
Checks if pointing to a valid connection object.
uros_err_t uros_lld_conn_create (UrosConn *cp, uros_connproto_t protocol)
Creates a new connection.
uros_err_t uros_lld_conn_bind (UrosConn *cp, const UrosAddr *locaddrp)
Binds to a local address.
uros_err_t uros_lld_conn_accept (UrosConn *cp, UrosConn *spawnedp)
Accepts an incoming connection.
uros_err_t uros_lld_conn_listen (UrosConn *cp, uros_cnt_t backlog)
Initializes the listening mode.
uros_err_t uros_lld_conn_connect (UrosConn *cp, const UrosAddr *remaddrp)
Connects to a remote address.
uros_err_t uros_lld_conn_recv (UrosConn *cp, void **bufpp, size_t *buflenp)
Receives some data.
uros_err_t uros_lld_conn_recvfrom (UrosConn *cp, void **bufpp, size_t *buflenp, const UrosAddr *remaddrp)
Receives some data from a remote address.
uros_err_t uros_lld_conn_send (UrosConn *cp, const void *bufp, size_t buflen)
Sends some data.
uros_err_t uros_lld_conn_sendconst (UrosConn *cp, const void *bufp, size_t buflen)
Sends some data.
uros_err_t uros_lld_conn_sendto (UrosConn *cp, const void *bufp, size_t buflen, const UrosAddr *remaddrp)
Sends some data to a remote address.
uros_err_t uros_lld_conn_sendtoconst (UrosConn *cp, const void *bufp, size_t buflen, const UrosAddr *remaddrp)
Sends some data to a remote address.
uros_err_t uros_lld_conn_shutdown (UrosConn *cp, uros_bool_t rx, uros_bool_t tx)
Terminates soem ends of a full-duplex channel.
uros_err_t uros_lld_conn_close (UrosConn *cp)
Closes a connection.
uros_err_t uros_lld_conn_gettcpnodelay (UrosConn *cp, uros_bool_t *enablep)
Gets the Nagle algorithm state.
uros_err_t uros_lld_conn_settcpnodelay (UrosConn *cp, uros_bool_t enable)
Sets the Nagle algorithm state.
uros_err_t uros_lld_conn_getrecvtimeout (UrosConn *cp, uint32_t *msp)
Gets the receiver timeout.
uros_err_t uros_lld_conn_setrecvtimeout (UrosConn *cp, uint32_t ms)
Sets the receiver timeout.
uros_err_t uros_lld_conn_getsendtimeout (UrosConn *cp, uint32_t *msp)
Gets the sender timeout.
uros_err_t uros_lld_conn_setsendtimeout (UrosConn *cp, uint32_t ms)
Sets the sender timeout.
const char * uros_lld_conn_lasterrortext (const UrosConn *cp)
Gets the last low-level connectivity library error text.
Function Documentation
uros_err_t uros_lld_hostnametoip (const UrosString * hostnamep, UrosIp * ipp)
Resolves an hostname to an IP address.
Executes a DNS call to resolve the hostname string to an IP address which can be used by the connectivity library.
Parameters
[in] hostnamep Pointer to a hostname string.
[out] ipp Pointer to an allocated UrosIp object.
Returns
Error code.
Definition at line 75 of file uros_lld_conn.c.
Referenced by urosHostnameToIp().
void uros_lld_conn_objectinit (UrosConn * cp)
Initializes a connection object.
Invalidates the connection fields and initializes the low-level ones.
Parameters
[in,out] cp Pointer to an allocated UrosConn object.
Definition at line 91 of file uros_lld_conn.c.
References urosAssert.
Referenced by urosConnObjectInit().
uros_bool_t uros_lld_conn_isvalid (UrosConn * cp)
Checks if pointing to a valid connection object.
cp points to a valid connection if it is not NULL and its low-level fields are in a valid state.
Parameters
[in] cp Pointer to a presumed valid UrosConn object.
Returns
true if cp addresses a valid UrosConn object.
Definition at line 109 of file uros_lld_conn.c.
Referenced by urosConnIsValid().
uros_err_t uros_lld_conn_create (UrosConn * cp, uros_connproto_t protocol)
Creates a new connection.
The connection object is initialized for a new connection.
Note
Conceptually equivalent to POSIX create().
Precondition
The connection object is initialized but no connection has been created with it.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] protocol Connection protocol.
Returns
Error code.
Definition at line 130 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, UROS_PROTO_TCP, UROS_PROTO_UDP, and urosAssert.
Referenced by urosConnCreate().
uros_err_t uros_lld_conn_bind (UrosConn * cp, const UrosAddr * locaddrp)
Binds to a local address.
The local side of a connection object is bound to the provided address.
Note
Conceptually equivalent to POSIX bind().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] locaddrp Pointer to the local address descriptor to be bound.
Returns
Error code.
Definition at line 158 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnBind().
uros_err_t uros_lld_conn_accept (UrosConn * cp, UrosConn * spawnedp)
Accepts an incoming connection.
A listener connection waits until a remote connection is instantiated. A new dedicated connection channel is spawned and returned, and the spawning connection is put back into listening state.
Note
Conceptually equivalent to POSIX accept().
Precondition
The cp connection object is listening.
Parameters
[in,out] cp Pointer to the listener connection object.
[out] spawnedp Pointer to an allocated UrosConn object with which the new dedicated communication channel is created.
Returns
Error code.
Definition at line 187 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnAccept().
uros_err_t uros_lld_conn_listen (UrosConn * cp, uros_cnt_t backlog)
Initializes the listening mode.
The connection object is initialized for listening.
Note
Conceptually equivalent to POSIX listen().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] backlog Maximum number of incoming connection simultaneously waiting to be accepdted with urosConnAccept().
Returns
Error code.
Definition at line 215 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnListen().
uros_err_t uros_lld_conn_connect (UrosConn * cp, const UrosAddr * remaddrp)
Connects to a remote address.
Note
Conceptually equivalent to POSIX connect().
Precondition
The connection object is only created.
Parameters
[in,out] cp Pointer to an initialized UrosConn object.
[in] remaddrp Pointer to the remote address descriptor to connect to.
Returns
Error code.
Definition at line 238 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnConnect().
uros_err_t uros_lld_conn_recv (UrosConn * cp, void ** bufpp, size_t * buflenp)
Receives some data.
The connection object waits until some data is received from the remote address. The pointer to the received data is returned, with a length up to the requested one.
Warning
Not conceptually equivalent to POSIX connect(), as the buffer is not provided by the user, but by the middleware.
Precondition
The connection must be open and working.
Postcondition
Either data is received, or an UROS_ERR_EOF is returned when there is no more pending data (connection closed by remote).
Parameters
[in,out] cp Pointer to a communicating connection object.
[out] bufpp Indirect pointer to the received data buffer.
[in,out] buflenp Pointer to the buffer length in bytes, with the following meaning:
At call, it indicates the maximum length of the received data.
At return, it is the actual length of the received data.
Returns
Error code.
Definition at line 272 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnRecv().
uros_err_t uros_lld_conn_recvfrom (UrosConn * cp, void ** bufpp, size_t * buflenp, const UrosAddr * remaddrp)
Receives some data from a remote address.
The connection object waits until some data is received from the remote address. The pointer to the received data is returned, with a length up to the requested one.
Note
Not available for TCP connections.
Warning
Not conceptually equivalent to POSIX connect(), as the buffer is not provided by the user, but by the middleware.
Parameters
[in,out] cp Pointer to a communicating connection object.
[out] bufpp Indirect pointer to the received data buffer.
[in,out] buflenp Pointer to the buffer length in bytes, with the following meaning:
At call, it indicates the maximum length of the received data.
At return, it is the actual length of the received data.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 308 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnRecvFrom().
uros_err_t uros_lld_conn_send (UrosConn * cp, const void * bufp, size_t buflen)
Sends some data.
Sends the buffered data to the remote address. The data is copied to an internal buffer while streaming.
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
Returns
Error code.
Definition at line 345 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSend().
uros_err_t uros_lld_conn_sendconst (UrosConn * cp, const void * bufp, size_t buflen)
Sends some data.
Sends the buffered data to the remote address. The data is not copied to internal buffers.
Note
If the low-level connectivity library does not support no-copy streaming, this is simply an alias to urosConnSend().
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The buffered data is granted not to change while it is still being streamed by the asynchronous low-level library thread.
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
Returns
Error code.
Definition at line 382 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSendConst().
uros_err_t uros_lld_conn_sendto (UrosConn * cp, const void * bufp, size_t buflen, const UrosAddr * remaddrp)
Sends some data to a remote address.
Sends the buffered data to the remote address. The data is copied to an internal buffer while streaming.
Note
Not available for TCP connections.
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 418 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSendTo().
uros_err_t uros_lld_conn_sendtoconst (UrosConn * cp, const void * bufp, size_t buflen, const UrosAddr * remaddrp)
Sends some data to a remote address.
Sends the buffered data to the remote address. The data is not copied to internal buffers.
Note
Not available for TCP connections.
If the low-level connectivity library does not support no-copy streaming, this is simply an alias to urosConnSend().
Warning
Not conceptually equivalent to POSIX send(), as all the data is granted to be sent with a single call to this function (if no connection errors occurred).
Precondition
The buffered data is granted not to change while it is still being streamed by the asynchronous low-level library thread.
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating connection object.
[in] bufp Pointer to the buffered data to be sent.
[in] buflen Length of the buffered data, in bytes.
[in] remaddrp Pointer to the remote address descriptor.
Returns
Error code.
Definition at line 461 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSendToConst().
uros_err_t uros_lld_conn_shutdown (UrosConn * cp, uros_bool_t rx, uros_bool_t tx)
Terminates soem ends of a full-duplex channel.
The reception or the transission channels are closed.
Note
Conceptually equivalent to POSIX shutdown().
Warning
The connection is not actually closed after a call to this function, even with both rx and tx true.
Precondition
The connection must be open and working.
Postcondition
All the buffered data ise sent.
Parameters
[in,out] cp Pointer to a communicating UrosConn object.
[in] rx Close the receiver channel.
[in] tx Close the reansmitter channel.
Returns
Error code.
Definition at line 496 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnShutdown().
uros_err_t uros_lld_conn_close (UrosConn * cp)
Closes a connection.
Terminates all connection channels and releases any internal buffers.
Note
Conceptually equivalent to POSIX close().
Precondition
The connection must be open and working.
Postcondition
The connection is closed.
Any internal buffers are freed.
Parameters
[in,out] cp Pointer to a communicating UrosConn object.
Returns
Error code.
Definition at line 523 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, and urosAssert.
Referenced by urosConnClose().
uros_err_t uros_lld_conn_gettcpnodelay (UrosConn * cp, uros_bool_t * enablep)
Gets the Nagle algorithm state.
Checks if the Nagle algorithm is enabled on the provided connection.
Note
Available only for TCP connections.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] enablep Pointer to the check result.
Returns
Error code.
Definition at line 545 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnGetTcpNoDelay().
uros_err_t uros_lld_conn_settcpnodelay (UrosConn * cp, uros_bool_t enable)
Sets the Nagle algorithm state.
When the Nagle algorithm is enabled, small packets are not immediately sent, but possibl enqueued, so that the TCP overhead is minimized. When it is disabled, even one-byte packets are immediately sent, to minimize latency despite the TCP overhead.
Note
Available only for TCP connections.
Parameters
[in,out] cp Pointer to a valid UrosConn object.
[in] enable Nagle algorithm activation switch.
Returns
Error code.
Definition at line 571 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSetTcpNoDelay().
uros_err_t uros_lld_conn_getrecvtimeout (UrosConn * cp, uint32_t * msp)
Gets the receiver timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] msp Pointer to the timeout value, in milliseconds.
Returns
Error code.
Definition at line 592 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnGetRecvTimeout().
uros_err_t uros_lld_conn_setrecvtimeout (UrosConn * cp, uint32_t ms)
Sets the receiver timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] ms Timeout value, in milliseconds.
Returns
Error code.
Definition at line 614 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSetRecvTimeout().
uros_err_t uros_lld_conn_getsendtimeout (UrosConn * cp, uint32_t * msp)
Gets the sender timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] msp Pointer to the timeout value, in milliseconds.
Returns
Error code.
Definition at line 635 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnGetSendTimeout().
uros_err_t uros_lld_conn_setsendtimeout (UrosConn * cp, uint32_t ms)
Sets the sender timeout.
Warning
May not be implemented on all platforms.
Parameters
[in] cp Pointer to a valid UrosConn object.
[out] ms Timeout value, in milliseconds.
Returns
Error code.
Definition at line 657 of file uros_lld_conn.c.
References UROS_ERR_NOTIMPL, urosAssert, and urosConnIsValid().
Referenced by urosConnSetSendTimeout().
const char* uros_lld_conn_lasterrortext (const UrosConn * cp)
Gets the last low-level connectivity library error text.
Parameters
[in] cp Pointer to the connection which generated the error to be analyzed.
Returns
Textural description of the last low-level connectovity error, null-terminated string.
Definition at line 676 of file uros_lld_conn.c.
References urosAssert.
Referenced by urosConnLastErrorText().