μROSnode
XMLRPC functions
XMLRPC
Detailed Description
XMLRPC parameter
void urosRpcParamClean (UrosRpcParam *paramp, uros_bool_t deep)
Cleans a XMLRPC parameter.
void urosRpcParamDelete (UrosRpcParam *paramp, uros_bool_t deep)
Deallocates a XMLRPC parameter.
void urosRpcParamObjectInit (UrosRpcParam *paramp, uros_rpcparamclass_t class)
Initializes a XMLRPC parameter object.
XMLRPC parameter list
void urosRpcParamNodeClean (UrosRpcParamNode *nodep, uros_bool_t deep)
Cleans a XMLRPC parameter list node.
void urosRpcParamNodeDelete (UrosRpcParamNode *nodep, uros_bool_t deep)
Deallocates a XMLRPC parameter list node.
void urosRpcParamNodeObjectInit (UrosRpcParamNode *nodep, uros_rpcparamclass_t class)
Initializes a XMLRPC parameter list node object.
void urosRpcParamListClean (UrosRpcParamList *listp, uros_bool_t deep)
Cleans a XMLRPC parameter list.
void urosRpcParamListDelete (UrosRpcParamList *listp, uros_bool_t deep)
Deletes a XMLRPC parameter list object.
void urosRpcParamListObjectInit (UrosRpcParamList *listp)
Initializes a XMLRPC parameter list.
void urosRpcParamListAppendNode (UrosRpcParamList *listp, UrosRpcParamNode *nodep)
Appends a node to the XMLRPC parameter list.
UrosRpcParamNode * urosRpcParamListUnlinkNode (UrosRpcParamList *listp, UrosRpcParamNode *nodep)
Removes a node from the XMLRPC parameter list.
XMLRPC response
void urosRpcResponseObjectInit (UrosRpcResponse *rp)
Initializes a XMLRPC response.
void urosRpcResponseClean (UrosRpcResponse *rp)
Cleans a XMLRPC resposnse.
Function Documentation
void urosRpcParamClean (UrosRpcParam * paramp, uros_bool_t deep)
Cleans a XMLRPC parameter.
Deallocates any memory chunks allocated by the parameter, and invalidates it.
Precondition
The parameter is initialized.
The parameter data must have been allocated with urosAlloc().
Postcondition
paramp points to an invalidated UrosRpcParam object.
The parameter class is unchanged.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] paramp Pointer to an initialized UrosRpcParam object.
[in] deep Performs deallocation of private members.
Definition at line 520 of file urosRpcCall.c.
References UrosRpcParam::base64, UrosRpcParam::class, UrosString::datap, UrosString::length, UrosRpcParam::listp, UrosRpcParam::string, UROS_RPCP_ARRAY, UROS_RPCP_BASE64, UROS_RPCP_BOOLEAN, UROS_RPCP_DOUBLE, UROS_RPCP_INT, UROS_RPCP_STRING, UROS_RPCP_STRUCT, urosAssert, urosFree(), urosRpcParamListDelete(), urosStringClean(), and UrosRpcParam::value.
Referenced by urosRpcParamDelete(), urosRpcParamNodeClean(), and urosRpcParserMethodResponse().
void urosRpcParamDelete (UrosRpcParam * paramp, uros_bool_t deep)
Deallocates a XMLRPC parameter.
Invalidates the private members. Optionally, deallocates their data.
Precondition
The parameter is initilized.
Postcondition
paramp points to an invalid address.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] paramp Pointer to an initialized UrosRpcParam object.
[in] deep Performs deallocation of private members.
Definition at line 578 of file urosRpcCall.c.
References UROS_TRUE, urosFree(), and urosRpcParamClean().
Referenced by urosRpcResponseClean().
void urosRpcParamObjectInit (UrosRpcParam * paramp, uros_rpcparamclass_t class)
Initializes a XMLRPC parameter object.
Initializes the object to the desired class, with invalidated safe values.
Parameters
[in,out] paramp Pointer to an allocated UrosRpcParam object.
[in] class Parameter class.
Definition at line 598 of file urosRpcCall.c.
References UrosRpcParam::base64, UrosRpcParam::class, UrosString::datap, UrosString::length, UrosRpcParam::listp, UrosRpcParam::string, UROS_RPCP_ARRAY, UROS_RPCP_BASE64, UROS_RPCP_BOOLEAN, UROS_RPCP_DOUBLE, UROS_RPCP_INT, UROS_RPCP_STRING, UROS_RPCP_STRUCT, urosAssert, and UrosRpcParam::value.
Referenced by urosRpcParamNodeObjectInit(), and urosRpcParserMethodResponse().
void urosRpcParamNodeClean (UrosRpcParamNode * nodep, uros_bool_t deep)
Cleans a XMLRPC parameter list node.
Deallocates any memory chunks allocated by the node, and invalidates it.
Precondition
The parameter node is initialized.
The parameter data must have been allocated with urosAlloc().
Postcondition
nodep points to an invalidated UrosRpcParam object.
The parameter class is unchanged.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] nodep Pointer to an initialized UrosRpcParamNode object.
[in] deep Performs deallocation of private members.
Definition at line 659 of file urosRpcCall.c.
References UrosRpcParamNode::nextp, UrosRpcParamNode::param, urosAssert, and urosRpcParamClean().
Referenced by urosRpcParamNodeDelete().
void urosRpcParamNodeDelete (UrosRpcParamNode * nodep, uros_bool_t deep)
Deallocates a XMLRPC parameter list node.
Invalidates the private members. Optionally, deallocates their data.
Precondition
The parameter node is initialized.
Postcondition
nodep points to an invalid address.
If desidred so, private members are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] nodep Pointer to an initialized UrosRpcParamNode object.
[in] deep Performs deallocation of private members.
Definition at line 681 of file urosRpcCall.c.
References UROS_TRUE, urosFree(), and urosRpcParamNodeClean().
Referenced by urosRpcParamListClean(), and urosRpcParserParamValueArray().
void urosRpcParamNodeObjectInit (UrosRpcParamNode * nodep, uros_rpcparamclass_t class)
Initializes a XMLRPC parameter list node object.
Initializes the parameter to the desired class, with invalidated safe values.
Parameters
[in,out] nodep Pointer to an allocated UrosRpcParamNode object.
[in] class Parameter class.
Definition at line 701 of file urosRpcCall.c.
References UrosRpcParamNode::nextp, UrosRpcParamNode::param, urosAssert, and urosRpcParamObjectInit().
Referenced by urosRpcParserParamValueArray().
void urosRpcParamListClean (UrosRpcParamList * listp, uros_bool_t deep)
Cleans a XMLRPC parameter list.
Removes all the nodes from a list. If desired, also all the nodes are deallcoated.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
listp points to an empty list.
If desidred so, all the nodes are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] listp Pointer to an initialized UrosRpcParamList object.
[in] deep Performs deallocation of al the nodes.
Definition at line 726 of file urosRpcCall.c.
References UrosRpcParamList::headp, UrosRpcParamList::length, UrosRpcParamNode::nextp, UrosRpcParamList::tailp, urosAssert, urosRpcParamListUnlinkNode(), and urosRpcParamNodeDelete().
Referenced by urosRpcParamListDelete().
void urosRpcParamListDelete (UrosRpcParamList * listp, uros_bool_t deep)
Deletes a XMLRPC parameter list object.
Removes all the nodes from a list. If desired, also all the nodes are deallcoated. The list object is the deallocated.
Precondition
The list is allocated with urosAlloc() and initialized.
Postcondition
listp points to an invalid address.
If desidred so, all the nodes are deallocated. They must have been allocated with urosAlloc().
Parameters
[in,out] listp Pointer to an initialized UrosRpcParamList object.
[in] deep Performs deallocation of all the nodes.
Definition at line 759 of file urosRpcCall.c.
References UROS_TRUE, urosFree(), and urosRpcParamListClean().
Referenced by urosRpcParamClean(), and urosRpcParserParamValueArray().
void urosRpcParamListObjectInit (UrosRpcParamList * listp)
Initializes a XMLRPC parameter list.
Initializes to an empty list.
Postcondition
The list is empty.
Parameters
[in,out] listp Pointer to an allocated UrosRpcParamList object.
Definition at line 778 of file urosRpcCall.c.
References UrosRpcParamList::headp, UrosRpcParamList::length, UrosRpcParamList::tailp, and urosAssert.
Referenced by urosRpcParserParamValueArray().
void urosRpcParamListAppendNode (UrosRpcParamList * listp, UrosRpcParamNode * nodep)
Appends a node to the XMLRPC parameter list.
Precondition
The node does not belong to the list.
The node has no successors.
Postcondition
The provided node is at the end of the list.
The list length is incremented by one.
Parameters
[in,out] listp Pointer to an initialized UrosRpcParamList object.
[in,out] nodep Pointer to an initialized UrosRpcParamNode object with no successors.
Definition at line 801 of file urosRpcCall.c.
References UrosRpcParamList::headp, UrosRpcParamList::length, UrosRpcParamNode::nextp, UrosRpcParamList::tailp, and urosAssert.
Referenced by urosRpcParserParamValueArray().
UrosRpcParamNode* urosRpcParamListUnlinkNode (UrosRpcParamList * listp, UrosRpcParamNode * nodep)
Removes a node from the XMLRPC parameter list.
The node, if found, is unlinked from the list and returned.
Postcondition
The node does not belong to the list.
The node has no successors.
The list length is decremented by one.
The list is consistent.
Parameters
[in,out] listp Pointer to an initialized UrosRpcParamList object.
[in] nodep Pointer to the node to be removed from the list.
Returns
Pointer to the removed (unlinked) node.
Return values
nodep The addressed node, if found inside the list.
NULL No such node found inside the list.
Definition at line 837 of file urosRpcCall.c.
References UrosRpcParamList::headp, UrosRpcParamList::length, UrosRpcParamNode::nextp, UrosRpcParamList::tailp, and urosAssert.
Referenced by urosRpcParamListClean(), and urosRpcParserParamValueArray().
void urosRpcResponseObjectInit (UrosRpcResponse * rp)
Initializes a XMLRPC response.
Initializes to an empty response.
Parameters
[in,out] rp Pointer to an allocated UrosRpcResponse object.
Definition at line 877 of file urosRpcCall.c.
References UrosRpcResponse::code, UrosRpcResponse::httpcode, UrosRpcResponse::statusMsgp, UROS_RPCC_ERROR, urosAssert, and UrosRpcResponse::valuep.
Referenced by urosNodePublishServiceByDesc(), urosNodePublishTopicByDesc(), urosNodeSubscribeParamByDesc(), urosNodeSubscribeTopicByDesc(), urosNodeUnsubscribeParam(), urosRpcCallParamUpdate(), urosRpcCallPublisherUpdate(), urosRpcCallRequestTopic(), urosRpcCallSetParam(), urosRpcCallSubscribeParam(), and urosRpcParserMethodResponse().
void urosRpcResponseClean (UrosRpcResponse * rp)
Cleans a XMLRPC resposnse.
Deallocates the memory chunk of the object and all its fields.
Precondition
The object and its fields must have been allocated with urosAlloc().
Postcondition
rp points to an invalid address.
Parameters
[in] rp Pointer to an initialized UrosRpcResponse object.
Definition at line 898 of file urosRpcCall.c.
References UrosRpcResponse::code, UrosRpcResponse::httpcode, UrosRpcResponse::statusMsgp, UROS_RPCC_ERROR, UROS_TRUE, urosAssert, urosRpcParamDelete(), urosStringDelete(), and UrosRpcResponse::valuep.