μROSnode
Streamer methods
XMLRPC
Detailed Description
Functions
void urosRpcStreamerObjectInit (UrosRpcStreamer *sp, UrosConn *csp, char *bufp, size_t buflen)
Initializes a XMLRPC streamer.
void urosRpcStreamerClean (UrosRpcStreamer *sp, uros_bool_t freeBuffer)
Cleans a UrosRpcStreamer object.
uros_err_t urosRpcStreamerFlush (UrosRpcStreamer *sp)
Flushes the write buffer.
uros_err_t urosRpcStreamerWrite (UrosRpcStreamer *sp, const void *chunkp, size_t chunklen)
Writes some data.
uros_err_t urosRpcStreamerUint32 (UrosRpcStreamer *sp, uint32_t value)
Writes a decimal unsigned integer (uint32).
uros_err_t urosRpcStreamerInt32 (UrosRpcStreamer *sp, int32_t value)
Writes a decimal signed integer (int32).
uros_err_t urosRpcStreamerIp (UrosRpcStreamer *sp, UrosIp ip)
Writes an IPv4 address.
uros_err_t urosRpcStreamerHttpPost (UrosRpcStreamer *sp)
Writes an HTTP POST line.
uros_err_t urosRpcStreamerHttpStatus (UrosRpcStreamer *sp, uint32_t code)
Writes an HTTP status line.
uros_err_t urosRpcStreamerHttpHeader (UrosRpcStreamer *sp, const char *keyp, size_t keylen, const char *valp, size_t vallen)
Writes an HTTP header.
uros_err_t urosRpcStreamerHttpEnd (UrosRpcStreamer *sp)
Writes the end of HTTP headers section.
uros_err_t urosRpcStreamerHttpContentLength (UrosRpcStreamer *sp)
Writes a hacked Content-Length HTTP header.
uros_err_t urosRpcStreamerXmlEndHack (UrosRpcStreamer *sp)
Hacks the XMLRPC message length.
uros_err_t urosRpcStreamerXmlAttrWVal (UrosRpcStreamer *sp, const char *namep, size_t namelen, const char *valp, size_t vallen, const char quotec)
Writes an XML attribute.
uros_err_t urosRpcStreamerXmlTagBegin (UrosRpcStreamer *sp, const char *tagp, size_t taglen)
Writes the beginning of a XML tag.
uros_err_t urosRpcStreamerXmlTagEnd (UrosRpcStreamer *sp)
Writes the end of a XML tag.
uros_err_t urosRpcStreamerXmlTagSlashEnd (UrosRpcStreamer *sp)
Writes the end of an empty XML tag.
uros_err_t urosRpcStreamerXmlTagOpen (UrosRpcStreamer *sp, const char *tagp, size_t taglen)
Writes a simple opening tag for a non-empty XML element.
uros_err_t urosRpcStreamerXmlTagClose (UrosRpcStreamer *sp, const char *tagp, size_t taglen)
Writes the closing tag for a non-empty XML element.
uros_err_t urosRpcStreamerXmlHeader (UrosRpcStreamer *sp)
Writes the XML header special tag.
uros_err_t urosRpcStreamerParamValueInt (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of an <i4> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueBoolean (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a <boolean> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueString (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a <string> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueDouble (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a <double> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueBase64 (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a <base64> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueStruct (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a <struct> XMLRPC parameter.
uros_err_t urosRpcStreamerParamValueArray (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of an <array> XMLRPC parameter.
uros_err_t urosRpcStreamerParam (UrosRpcStreamer *sp, const UrosRpcParam *paramp)
Writes the value of a XMLRPC parameter.
Function Documentation
void urosRpcStreamerObjectInit (UrosRpcStreamer * sp, UrosConn * csp, char * bufp, size_t buflen)
Initializes a XMLRPC streamer.
All the fields are initialized. A connection and a buffer are assigned to this object.
Precondition
The streamer is uninitialized.
Parameters
[in,out] sp Pointer to an uninitialized UrosRpcStreamer object.
[in] csp Pointer to an allocated UrosConn connection object.
[in] bufp Pointer to the write buffer.
[in] buflen Length of the write buffer, in bytes.
Definition at line 80 of file urosRpcStreamer.c.
References UrosRpcStreamer::buflen, UrosRpcStreamer::bufp, UrosRpcStreamer::csp, UrosRpcStreamer::curp, UrosRpcStreamer::err, UrosRpcStreamer::free, UrosRpcStreamer::mark, UrosRpcStreamer::total, UROS_OK, and urosAssert.
void urosRpcStreamerClean (UrosRpcStreamer * sp, uros_bool_t freeBuffer)
Cleans a UrosRpcStreamer object.
Resets the state of its internal fields. If needed, the buffer is deallocated. Does not unlink from the assigned connection.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] freeBuffer Deallocates buffers.
Definition at line 110 of file urosRpcStreamer.c.
References UrosRpcStreamer::buflen, UrosRpcStreamer::bufp, UrosRpcStreamer::curp, UrosRpcStreamer::err, UrosRpcStreamer::free, UrosRpcStreamer::mark, UrosRpcStreamer::total, UROS_OK, urosAssert, and urosFree().
uros_err_t urosRpcStreamerFlush (UrosRpcStreamer * sp)
Flushes the write buffer.
Waits untill all the data of the write buffer is streamed.
Parameters
[in,out] sp Pointer to an initialzied UrosRpcStreamer object.
Returns
Error code.
Definition at line 138 of file urosRpcStreamer.c.
References UrosRpcStreamer::buflen, UrosRpcStreamer::bufp, UrosRpcStreamer::csp, UrosRpcStreamer::curp, UrosRpcStreamer::err, UrosRpcStreamer::free, UROS_OK, urosAssert, urosConnSend(), urosError, and urosErrorText().
Referenced by urosRpcStreamerWrite().
uros_err_t urosRpcStreamerWrite (UrosRpcStreamer * sp, const void * chunkp, size_t chunklen)
Writes some data.
The data chunk is written to the write buffer. Every time it becomes full, buffered data is flushed. The write counter is incremented by the chunk length.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] chunkp Pointer to the data chunk to be sent. Can be NULL only if chunklen is 0.
[in] chunklen Length of the data chunk, in bytes. Can be 0.
Returns
Error code.
Definition at line 173 of file urosRpcStreamer.c.
References UrosRpcStreamer::buflen, UrosRpcStreamer::bufp, UrosRpcStreamer::curp, UrosRpcStreamer::err, UrosRpcStreamer::free, UrosRpcStreamer::total, UROS_ERR_BADPARAM, UROS_OK, UROS_TRUE, urosAssert, urosError, urosErrorText(), and urosRpcStreamerFlush().
Referenced by urosRpcStreamerHttpContentLength(), urosRpcStreamerHttpEnd(), urosRpcStreamerHttpHeader(), urosRpcStreamerHttpPost(), urosRpcStreamerHttpStatus(), urosRpcStreamerInt32(), urosRpcStreamerIp(), urosRpcStreamerParamValueDouble(), urosRpcStreamerParamValueString(), urosRpcStreamerUint32(), urosRpcStreamerXmlAttrWVal(), urosRpcStreamerXmlEndHack(), urosRpcStreamerXmlHeader(), urosRpcStreamerXmlTagBegin(), urosRpcStreamerXmlTagClose(), urosRpcStreamerXmlTagEnd(), urosRpcStreamerXmlTagOpen(), and urosRpcStreamerXmlTagSlashEnd().
uros_err_t urosRpcStreamerUint32 (UrosRpcStreamer * sp, uint32_t value)
Writes a decimal unsigned integer (uint32).
Decimal format without leading zeroes.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] value Value to be written.
Returns
Error code.
Definition at line 222 of file urosRpcStreamer.c.
References urosAssert, and urosRpcStreamerWrite().
Referenced by urosRpcStreamerHttpContentLength(), urosRpcStreamerHttpStatus(), urosRpcStreamerInt32(), urosRpcStreamerParamValueBoolean(), and urosRpcStreamerParamValueDouble().
uros_err_t urosRpcStreamerInt32 (UrosRpcStreamer * sp, int32_t value)
Writes a decimal signed integer (int32).
Decimal format without leading zeroes. Sign symbol only for negative values ('-').
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] value Value to be written.
Returns
Error code.
Definition at line 254 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, urosRpcStreamerUint32(), and urosRpcStreamerWrite().
Referenced by urosRpcStreamerIp(), and urosRpcStreamerParamValueInt().
uros_err_t urosRpcStreamerIp (UrosRpcStreamer * sp, UrosIp ip)
Writes an IPv4 address.
Using the standard format, for example:
192.168.1.1
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] ip IPv4 address to write.
Returns
Error code.
Definition at line 278 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UrosIp::field1, UrosIp::field2, UrosIp::field3, UrosIp::field4, UrosIp::fields, UROS_OK, urosAssert, urosRpcStreamerInt32(), and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerHttpPost (UrosRpcStreamer * sp)
Writes an HTTP POST line.
Using HTTP 1.0. Automatically appends CR-LF.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
Returns
Error code.
FIXME: Is /RPC2 broken in ROS itself?
Definition at line 304 of file urosRpcStreamer.c.
References urosRpcStreamerWrite().
uros_err_t urosRpcStreamerHttpStatus (UrosRpcStreamer * sp, uint32_t code)
Writes an HTTP status line.
Using HTTP 1.0. Writes also the human-readable description. Automatically appends CR-LF.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] code Code of the HTTP status. Currently supporting: 200, 201, 202, 204, 400, 401, 403, 404, 500, 501, 502, 503.
Returns
Error code.
Definition at line 323 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_ERR_BADPARAM, UROS_NOP, UROS_OK, urosAssert, urosError, urosRpcStreamerUint32(), and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerHttpHeader (UrosRpcStreamer * sp, const char * keyp, size_t keylen, const char * valp, size_t vallen)
Writes an HTTP header.
Automatically appends CR-LF.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] keyp Pointer to the key string.
[in] keylen Length of the key string, in bytes.
[in] valp Pointer to the value string.
[in] vallen Length of the value string, in bytes.
Returns
Error code.
Definition at line 377 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerHttpEnd (UrosRpcStreamer * sp)
Writes the end of HTTP headers section.
Simply writes a CR-LF.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
Returns
Error code.
Definition at line 405 of file urosRpcStreamer.c.
References urosRpcStreamerWrite().
uros_err_t urosRpcStreamerHttpContentLength (UrosRpcStreamer * sp)
Writes a hacked Content-Length HTTP header.
Writes the Content-Length header, with the value of UROS_RPCSTREAMER_FIXLEN.
See Also
UROS_RPCSTREAMER_FIXLEN
urosRpcStreamerXmlEndHack()
Precondition
The Content-Length HTTP header is the last header.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
Returns
Error code.
Definition at line 424 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UrosRpcStreamer::mark, UrosRpcStreamer::total, UROS_OK, UROS_RPCSTREAMER_FIXLEN, urosAssert, urosRpcStreamerUint32(), and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlEndHack (UrosRpcStreamer * sp)
Hacks the XMLRPC message length.
This function is called to end a XMLRPC message. It behaves in two ways, depending on the status of the write buffer.
If the write buffer of the UrosRpcStream was flushed since the beginning of the message, then a sequence of LF ('\n') is appended to match the UROS_RPCSTREAMER_FIXLEN body length.
If the write buffer was not flushed, then it is possible to overwrite the Content-Length. It is adjusted so that it matches the current body length.
See Also
UROS_RPCSTREAMER_FIXLEN
urosRpcStreamerHttpContentLength()
Precondition
No XMLRPC message can exceed UROS_RPCSTREAMER_FIXLEN.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
Returns
Error code.
Definition at line 459 of file urosRpcStreamer.c.
References UrosRpcStreamer::buflen, UrosRpcStreamer::bufp, UrosRpcStreamer::err, UrosRpcStreamer::mark, UrosRpcStreamer::total, UROS_OK, UROS_RPCSTREAMER_FIXLEN, UROS_STRINGIFY2, urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlAttrWVal (UrosRpcStreamer * sp, const char * namep, size_t namelen, const char * valp, size_t vallen, const char quotec)
Writes an XML attribute.
Parameters
[in,out] sp Pointer to an initialized UrosRpcStreamer object.
[in] namep Pointer to the name string.
[in] namelen Name string length, in bytes.
[in] valp Pointer to the value string.
[in] vallen Value string length, in bytes.
[in] quotec XML quote character. Can be either '"' or '\''.
Returns
Error code.
Definition at line 522 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlTagBegin (UrosRpcStreamer * sp, const char * tagp, size_t taglen)
Writes the beginning of a XML tag.
The beginning has format:
<TAG
.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] tagp Pointer to the tag name string.
[in] taglen Length of the tag name.
Returns
Error code.
Definition at line 564 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlTagEnd (UrosRpcStreamer * sp)
Writes the end of a XML tag.
The end has format:
>
.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
Returns
Error code.
Definition at line 589 of file urosRpcStreamer.c.
References urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlTagSlashEnd (UrosRpcStreamer * sp)
Writes the end of an empty XML tag.
The end has format:
/>
.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
Returns
Error code.
Definition at line 606 of file urosRpcStreamer.c.
References urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerXmlTagOpen (UrosRpcStreamer * sp, const char * tagp, size_t taglen)
Writes a simple opening tag for a non-empty XML element.
The tag has format:
<TAG>
.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] tagp Pointer to the tag name string.
[in] taglen Length of the tag name.
Returns
Error code.
Definition at line 627 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, and urosRpcStreamerWrite().
Referenced by urosRpcStreamerParam(), and urosRpcStreamerParamValueArray().
uros_err_t urosRpcStreamerXmlTagClose (UrosRpcStreamer * sp, const char * tagp, size_t taglen)
Writes the closing tag for a non-empty XML element.
The tag has format:
</TAG>
.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] tagp Pointer to the tag name string.
[in] taglen Length of the tag name.
Returns
Error code.
Definition at line 657 of file urosRpcStreamer.c.
References UrosRpcStreamer::err, UROS_OK, urosAssert, and urosRpcStreamerWrite().
Referenced by urosRpcStreamerParam(), and urosRpcStreamerParamValueArray().
uros_err_t urosRpcStreamerXmlHeader (UrosRpcStreamer * sp)
Writes the XML header special tag.
The header has format:
<?xml version="1.0"?>
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
Returns
Error code.
Definition at line 683 of file urosRpcStreamer.c.
References urosAssert, and urosRpcStreamerWrite().
uros_err_t urosRpcStreamerParamValueInt (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of an <i4> XMLRPC parameter.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding an <i4> value.
Returns
Error code.
Definition at line 700 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcParam::int32, UROS_RPCP_INT, urosAssert, urosRpcStreamerInt32(), and UrosRpcParam::value.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueBoolean (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a <boolean> XMLRPC parameter.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding an <boolean> value.
Returns
Error code.
Definition at line 720 of file urosRpcStreamer.c.
References UrosRpcParam::boolean, UrosRpcParam::class, UROS_RPCP_BOOLEAN, urosAssert, urosRpcStreamerUint32(), and UrosRpcParam::value.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueString (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a <string> XMLRPC parameter.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding an <string> value.
Returns
Error code.
Definition at line 740 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosString::datap, UrosString::length, UrosRpcParam::string, UROS_RPCP_STRING, urosAssert, urosRpcStreamerWrite(), and UrosRpcParam::value.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueDouble (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a <double> XMLRPC parameter.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding a <double> value.
Returns
Error code.
Definition at line 763 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcStreamer::err, UrosRpcParam::real, UROS_OK, UROS_RPCP_DOUBLE, urosAssert, urosRpcStreamerUint32(), urosRpcStreamerWrite(), and UrosRpcParam::value.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueBase64 (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a <base64> XMLRPC parameter.
Warning
Not implemented.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding an <base64> value.
Returns
Error code.
Definition at line 803 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcStreamer::err, UROS_OK, UROS_RPCP_BASE64, and urosAssert.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueStruct (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a <struct> XMLRPC parameter.
Warning
Not implemented.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding a <struct> value.
Returns
Error code.
Definition at line 830 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcStreamer::err, UROS_OK, UROS_RPCP_STRUCT, and urosAssert.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParamValueArray (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of an <array> XMLRPC parameter.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter holding an <array> value.
Returns
Error code.
Definition at line 856 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcStreamer::err, UrosRpcParamList::headp, UrosRpcParamList::length, UrosRpcParam::listp, UrosRpcParamNode::nextp, UrosRpcParamNode::param, UROS_OK, UROS_RPCP_ARRAY, urosAssert, urosRpcStreamerParam(), urosRpcStreamerXmlTagClose(), urosRpcStreamerXmlTagOpen(), and UrosRpcParam::value.
Referenced by urosRpcStreamerParam().
uros_err_t urosRpcStreamerParam (UrosRpcStreamer * sp, const UrosRpcParam * paramp)
Writes the value of a XMLRPC parameter.
The value is enclosed between a value XML element.
Parameters
[in,out] sp Pointer to an initialized @è UrosRpcStreamer object.
[in] paramp Pointer to the XMLRPC parameter.
Returns
Error code.
Definition at line 889 of file urosRpcStreamer.c.
References UrosRpcParam::class, UrosRpcStreamer::err, UROS_ERR_BADPARAM, UROS_NOP, UROS_OK, UROS_RPCP_ARRAY, UROS_RPCP_BASE64, UROS_RPCP_BOOLEAN, UROS_RPCP_DOUBLE, UROS_RPCP_INT, UROS_RPCP_STRING, UROS_RPCP_STRUCT, urosAssert, urosError, urosRpcStreamerParamValueArray(), urosRpcStreamerParamValueBase64(), urosRpcStreamerParamValueBoolean(), urosRpcStreamerParamValueDouble(), urosRpcStreamerParamValueInt(), urosRpcStreamerParamValueString(), urosRpcStreamerParamValueStruct(), urosRpcStreamerXmlTagClose(), and urosRpcStreamerXmlTagOpen().
Referenced by urosRpcStreamerParamValueArray().